OpticsBenchUI: ComediWindow Class Reference
ComediWindow Class Reference
UI
#include <ComediWindow.h>
Public Slots
void update ()
Update database-backed tables.
void remove ()
Remove selected entries.
void load ()
Load configuration into runtime.
void setDbPath (QString path)
Public Member Functions
ComediWindow (QMainWindow *parent=nullptr, Qt::WindowFlags fl=Qt::Window, Comedi *comedi=nullptr)
~ComediWindow () override
Destructor.
Public Attributes
ComediCounterControlWidget * comediWidget
Comedi counter control widget.
ComediDacControlWidget * daccomediWidget
Comedi DAC control widget.
Protected Member Functions
void closeEvent (QCloseEvent *event) override
Detailed Description
Window for Comedi device configuration and control.
Definition at line 33 of file ComediWindow.h.
Constructor & Destructor Documentation
ComediWindow()
ComediWindow::ComediWindow (QMainWindow * parent = nullptr, Qt::WindowFlags fl = Qt::Window, Comedi * comedi = nullptr)
Construct a Comedi window.
Parameters
parent Parent window.
fl Window flags.
comedi Comedi controller instance.
Definition at line 32 of file ComediWindow.cpp.
References Utils::ConfigureSqlTableView(), load(), Comedi::path, QLOG_INFO, remove(), and update().
~ComediWindow()
ComediWindow::~ComediWindow () override
Destructor.
Definition at line 85 of file ComediWindow.cpp.
References comediWidget, daccomediWidget, and QLOG_DEBUG.
Member Function Documentation
closeEvent()
void ComediWindow::closeEvent (QCloseEvent * event) override protected
Handle window close events.
Parameters
event Close event.
Definition at line 106 of file ComediWindow.cpp.
References Comedi::comeditype, comediWidget, QLOG_DEBUG, and ComediCounterControlWidget::setButtonList.
load
void ComediWindow::load () slot
Load configuration into runtime.
Definition at line 134 of file ComediWindow.cpp.
Referenced by ComediWindow().
remove
void ComediWindow::remove () slot
Remove selected entries.
Definition at line 138 of file ComediWindow.cpp.
Referenced by ComediWindow().
setDbPath
void ComediWindow::setDbPath (QString path) slot
Set the database path for tables.
Parameters
path Filesystem path to the Comedi DB.
Definition at line 92 of file ComediWindow.cpp.
References Utils::ConfigureSqlTableView(), Comedi::path, and Comedi::setDbPath().
update
void ComediWindow::update () slot
Update database-backed tables.
Definition at line 130 of file ComediWindow.cpp.
Referenced by ComediWindow().
Member Data Documentation
comediWidget
ComediCounterControlWidget* ComediWindow::comediWidget
Comedi counter control widget.
Definition at line 49 of file ComediWindow.h.
Referenced by closeEvent(), and ~ComediWindow().
daccomediWidget
ComediDacControlWidget* ComediWindow::daccomediWidget
Comedi DAC control widget.
Definition at line 51 of file ComediWindow.h.
Referenced by ~ComediWindow().
The documentation for this class was generated from the following files:
ComediWindow.h
ComediWindow.cpp