OpticsBenchUI: AcquisitionSequence Class Reference
AcquisitionSequence Class Reference
#include <AcquisitionSequence.h>
Public Types
enum { IS_LOOP = 0 , LOOP_START = 1 , LOOP_END = 2 }
Public Member Functions
AcquisitionSequence ()
Create a new sequence with default values.
~AcquisitionSequence ()
Destructor.
void setImage (uchar *buffer, int width, int height)
void setImage16 (ushort *buffer16, int width, int height)
void setImage32 (int *buffer32, int width, int height)
bool setImage (AcquisitionSequence *sequenceLeft)
void setImageMin (int _imageMin)
void setImageMax (int _imageMax)
void prepare ()
Prepare transient buffers and derived data before acquisition.
bool getFileData ()
Load or refresh file-based data for this sequence.
uchar * getImage ()
Return the current 8-bit image buffer.
ushort * getImage16 ()
Return the current 16-bit image buffer.
int * getImage32 ()
Return the current 32-bit image buffer.
uchar * getImageFromFile ()
Read an image buffer from the backing file.
bool setAvg (AcquisitionSequence *sequenceLeft, AcquisitionSequence *sequenceRight)
bool setPhase (AcquisitionSequence *sequenceLeft, AcquisitionSequence *sequenceRight)
bool setAmplitude (AcquisitionSequence *sequenceLeft, AcquisitionSequence *sequenceRight)
Public Attributes
double etime
Elapsed time for the sequence (seconds).
int record
Current record index.
int seq_record
Sequence record index.
bool status
Status flag for the sequence.
QString instrumentName
Instrument name.
QString instrumentType
Instrument type identifier.
QString settings
Settings string.
QString scanplan
Scan plan description.
int loop
Loop index.
int loopends
Loop end index.
int loopNumber
Total number of loops.
int remainingLoops
Remaining loop count.
bool loopSnake
Whether loop uses snake pattern.
bool loopReverse
Whether loop is reversed.
FileParser * fileParser
File parser used for loading input data.
QString avg
Averaging mode identifier.
bool reset
Whether to reset treatment state.
QString treatment
Treatment identifier.
QString avgOp
Averaging operation.
int avgSuccess
Average success flag.
int avgRight
Average right-side count.
int avgLeft
Average left-side count.
QString instrumentRef
Instrument reference string.
int sleep
Sleep duration between operations (ms).
QString motorAction
Motor action string.
QString superkAction
SuperK action string.
float motorValue
Motor value for the action.
float position
Cached motor position.
float superkPowerValue
SuperK power value.
float superkNdValue
SuperK ND value.
float superkSwpValue
SuperK SWP value.
float superkLwpValue
SuperK LWP value.
float superkCwValue
SuperK center wavelength value.
float superkBwValue
SuperK bandwidth value.
float superkRPowerValue
SuperK raw power value.
float superkRNdValue
SuperK raw ND value.
float superkRSwpValue
SuperK raw SWP value.
float superkRLwpValue
SuperK raw LWP value.
float superkRCwValue
SuperK raw center wavelength value.
float superkRBwValue
SuperK raw bandwidth value.
double dacValue
DAC value (engineering units).
double dacRValue
DAC value (raw units).
int dacOutput
DAC output index.
int comediValue
Comedi value (integer).
double comediData
Comedi data (engineering units).
int comediOutput
Comedi output index.
QString fullpath
Full path to SLM image set.
QString imagepath
Current image path.
QString imagetype
Image type/extension.
QString keepzero
Keep-zero flag for SLM.
QImage * slmimage
Loaded SLM image.
int imgnum
Image number.
int startnum
Start number for sequence.
int stepnum
Step number for sequence.
int slmwidth
SLM width in pixels.
int slmheight
SLM height in pixels.
int screen_x
Screen X coordinate.
int screen_y
Screen Y coordinate.
QLabel * slmLabel
Label used for SLM display.
float * data_2D_FLOAT
2D float image buffer.
int data_2D_FLOAT_DIM_X
2D float image width.
int data_2D_FLOAT_DIM_Y
2D float image height.
float data_2D_FLOAT_MIN
2D float image minimum.
float data_2D_FLOAT_MAX
2D float image maximum.
uchar * image
8-bit image buffer.
ushort * image16
16-bit image buffer.
int * image32
32-bit image buffer.
int imageMin
Image minimum.
int imageMax
Image maximum.
int imageWidth
Image width.
int imageHeight
Image height.
QString group
HDF5 group name.
QString datagroup
HDF5 data group name.
QString dataname
HDF5 dataset name.
int inc_group
Group increment index.
hid_t refgrp
HDF5 reference group handle.
hid_t grp
HDF5 group handle.
hid_t tmpgrp
HDF5 temporary group handle.
QString grpname
HDF5 group name string.
Detailed Description
Holds the full state of one acquisition step.
This structure aggregates scan parameters, device actions, and buffers used during acquisition. It is passed between acquisition coordination components and file persistence logic.
Definition at line 39 of file AcquisitionSequence.h.
Member Function Documentation
setAmplitude()
bool AcquisitionSequence::setAmplitude (AcquisitionSequence * sequenceLeft, AcquisitionSequence * sequenceRight)
Compute amplitude data from two sequences.
Parameters
sequenceLeft Left sequence.
sequenceRight Right sequence.
Returns
True on success.
Definition at line 620 of file AcquisitionSequence.cpp.
References data_2D_FLOAT, data_2D_FLOAT_DIM_X, data_2D_FLOAT_DIM_Y, instrumentRef, instrumentType, reset, and status.
setAvg()
bool AcquisitionSequence::setAvg (AcquisitionSequence * sequenceLeft, AcquisitionSequence * sequenceRight)
Compute averaged data from two sequences.
Parameters
sequenceLeft Left sequence.
sequenceRight Right sequence.
Returns
True on success.
Definition at line 472 of file AcquisitionSequence.cpp.
References avgOp, comediData, dacValue, data_2D_FLOAT, data_2D_FLOAT_DIM_X, data_2D_FLOAT_DIM_Y, getImage(), getImage32(), imageHeight, imageWidth, instrumentRef, instrumentType, reset, and status.
setImage() [1/2]
bool AcquisitionSequence::setImage (AcquisitionSequence * sequenceLeft)
Copy or derive an image from another sequence.
Parameters
sequenceLeft Source sequence.
Returns
True if an image was set successfully.
Definition at line 695 of file AcquisitionSequence.cpp.
References data_2D_FLOAT, data_2D_FLOAT_DIM_X, data_2D_FLOAT_DIM_Y, data_2D_FLOAT_MAX, data_2D_FLOAT_MIN, image, imageHeight, imageWidth, instrumentRef, instrumentType, reset, setImage(), and status.
setImage() [2/2]
void AcquisitionSequence::setImage (uchar * buffer, int width, int height)
Attach an 8-bit image buffer.
Parameters
buffer Pointer to the image data.
width Image width in pixels.
height Image height in pixels.
Definition at line 122 of file AcquisitionSequence.cpp.
References image, image16, image32, imageHeight, and imageWidth.
Referenced by setImage().
setImage16()
void AcquisitionSequence::setImage16 (ushort * buffer16, int width, int height)
Attach a 16-bit image buffer.
Parameters
buffer16 Pointer to the image data.
width Image width in pixels.
height Image height in pixels.
Definition at line 136 of file AcquisitionSequence.cpp.
References image, image16, imageHeight, and imageWidth.
setImage32()
void AcquisitionSequence::setImage32 (int * buffer32, int width, int height)
Attach a 32-bit image buffer.
Parameters
buffer32 Pointer to the image data.
width Image width in pixels.
height Image height in pixels.
Definition at line 150 of file AcquisitionSequence.cpp.
References image, image32, imageHeight, and imageWidth.
setImageMax()
void AcquisitionSequence::setImageMax (int _imageMax)
Set the image maximum for display scaling.
Parameters
_imageMax Maximum pixel value.
Definition at line 168 of file AcquisitionSequence.cpp.
References imageMax.
setImageMin()
void AcquisitionSequence::setImageMin (int _imageMin)
Set the image minimum for display scaling.
Parameters
_imageMin Minimum pixel value.
Definition at line 163 of file AcquisitionSequence.cpp.
References imageMin.
setPhase()
bool AcquisitionSequence::setPhase (AcquisitionSequence * sequenceLeft, AcquisitionSequence * sequenceRight)
Compute phase data from two sequences.
Parameters
sequenceLeft Left sequence.
sequenceRight Right sequence.
Returns
True on success.
Definition at line 658 of file AcquisitionSequence.cpp.
References data_2D_FLOAT, data_2D_FLOAT_DIM_X, data_2D_FLOAT_DIM_Y, instrumentRef, instrumentType, reset, and status.
The documentation for this class was generated from the following files:
AcquisitionSequence.h
AcquisitionSequence.cpp