OpticsBenchUI: Driver Class Reference
Driver Class Reference abstract
Hardware » Motors
#include <Driver.h>
Public Member Functions
Driver ()
Constructor.
Driver (ACCom *commChannel)
Constructor with communication channel.
Driver (const Driver &actuatorDrv, ACCom *commChannel)
Constructor with driver reference and communication channel.
Driver (const Driver &actuatorDrv)
Copy Constructor.
virtual ~Driver ()
Destructor.
Driver & operator= (Driver &actuatorDrv)
Affectation Operator.
virtual int Init (string &rstateData) const =0
virtual int InitActuator (string actuatorSetting, float position) const =0
Initializes the hardware device.
virtual int GetPos (string actuatorSetting, float &position) const =0
Retrieves the current position of the actuator.
virtual int Move (string actuatorSetting, float nbSteps, int unit) const =0
Performs a relative movement of the actuator.
virtual int MoveAbs (string actuatorSetting, float absPos, int unit) const =0
Performs an absolute movement of the actuator.
virtual int Stop (string actuatorSetting) const =0
Stops the current movement of the actuator.
virtual int OperationComplete (string &rstateData, string actuatorSetting, DriverDefinition::ADLimitSwitch &rlimitSwitch) const =0
Checks if an operation has been finished or not.
virtual int GetLastError (DriverDefinition::ADErrorCode &lastError)
code of the last error
virtual int GetActuatorFeature (DriverDefinition::DriverFeature &ractuatorFeature) const =0
virtual int ConvertUnit (int unit, float valueToConvert, float &rconvertedValue, float &rrange) const =0
virtual int SendGeneralCommand (char *buffer, string &rply) const
virtual int Exit (string actuatorSetting)
Static Public Member Functions
static Driver * Create (string driverType, string setting, ACCom *channel)
Driver type to instantiate and settings.
static Driver * Create (const Driver *prefActuatorDrv, ACCom *prefChannel)
pointer on the reference driver and channel
Static Public Attributes
static const string PI_C862 = "PI_C862"
Identifier for the PIezo driver.
static const string NEWFOCUS_8750_OL = "NewFocus_8750_Ol"
Identifier for the Ethernet-PIcomotor driver.
static const string NEWFOCUS_8750_CL = "NewFocus_8750_Cl"
Identifier for the Ethernet-Closed-Loop-PIcomotor driver.
static const string PI_C509 = "PI_C509"
Identifier for the Translation Stage driver.
static const string MICOS_POLLUX = "Micos_Pollux"
Identifier for the Rotor driver.
static const string NEWPORT_NSC200 = "NewPort_NSC200"
Identifier for the NSA driver.
static const string STANDA_USMC = "Standa_uSMC"
Identifier for the STANDA (old) driver.
static const string STANDA_USMC2 = "Standa_uSMC2"
Identifier for the STANDA driver.
static const string NULL_DRV_ID
Identifier for the NULL driver.
static const string PI_E725 = "PI_E725"
Identifier for the PI_E725 driver.
static const string NEWPORT_AGUC2 = "NewPort_AGUC2"
Identifier for the NEWPORT_AGUC2.
Protected Member Functions
void Tokenize (const string &str, vector< string > &tokens, const string &delimiters=" ") const
void ReportWarning (DriverDefinition::ADErrorCode code, const QString &message) const
void ReportError (DriverDefinition::ADErrorCode code, const QString &message) const
void ReportSettingError (const QString &message) const
void ReportCommError (const QString &message) const
void ReportRangeError (const QString &message) const
Protected Attributes
DriverDefinition::ADErrorCode _lastError
Code of the last error.
string _setting
Driver setting string.
ACCom * _pcommChannel
Actuator communication channel.
Detailed Description
Abstract interface for actuator driver implementations.
Definition at line 39 of file Driver.h.
Constructor & Destructor Documentation
Driver() [1/4]
Driver::Driver () inline
Constructor.
Definition at line 70 of file Driver.h.
References _lastError.
Referenced by Create(), Create(), Driver(), Driver(), DriverMicos_Pollux::DriverMicos_Pollux(), DriverMicos_Pollux::DriverMicos_Pollux(), DriverMicos_Pollux::DriverMicos_Pollux(), DriverNewFocus_8750_Cl::DriverNewFocus_8750_Cl(), DriverNewFocus_8750_Cl::DriverNewFocus_8750_Cl(), DriverNewFocus_8750_Cl::DriverNewFocus_8750_Cl(), DriverNewFocus_8750_Ol::DriverNewFocus_8750_Ol(), DriverNewFocus_8750_Ol::DriverNewFocus_8750_Ol(), DriverNewFocus_8750_Ol::DriverNewFocus_8750_Ol(), DriverNewPort_AGUC2::DriverNewPort_AGUC2(), DriverNewPort_AGUC2::DriverNewPort_AGUC2(), DriverNewPort_AGUC2::DriverNewPort_AGUC2(), DriverNewPort_NSC200::DriverNewPort_NSC200(), DriverNewPort_NSC200::DriverNewPort_NSC200(), DriverNewPort_NSC200::DriverNewPort_NSC200(), DriverPI_C509::DriverPI_C509(), DriverPI_C509::DriverPI_C509(), DriverPI_C509::DriverPI_C509(), DriverPI_C862::DriverPI_C862(), DriverPI_C862::DriverPI_C862(), DriverPI_C862::DriverPI_C862(), DriverPI_E725::DriverPI_E725(), DriverPI_E725::DriverPI_E725(), DriverPI_E725::DriverPI_E725(), DriverStanda_uSMC::DriverStanda_uSMC(), DriverStanda_uSMC::DriverStanda_uSMC(), DriverStanda_uSMC::DriverStanda_uSMC(), DriverStanda_uSMC2::DriverStanda_uSMC2(), DriverStanda_uSMC2::DriverStanda_uSMC2(), DriverStanda_uSMC2::DriverStanda_uSMC2(), and operator=().
Driver() [2/4]
Driver::Driver (ACCom * commChannel) inline
Constructor with communication channel.
Definition at line 76 of file Driver.h.
References _pcommChannel.
Driver() [3/4]
Driver::Driver (const Driver & actuatorDrv, ACCom * commChannel) inline
Constructor with driver reference and communication channel.
Definition at line 82 of file Driver.h.
References _lastError, _pcommChannel, _setting, and Driver().
Driver() [4/4]
Driver::Driver (const Driver & actuatorDrv) inline
Copy Constructor.
Definition at line 91 of file Driver.h.
References _lastError, _pcommChannel, _setting, and Driver().
~Driver()
virtual Driver::~Driver () inline virtual
Destructor.
Definition at line 98 of file Driver.h.
Member Function Documentation
ConvertUnit()
virtual int Driver::ConvertUnit (int unit, float valueToConvert, float & rconvertedValue, float & rrange) const pure virtual
Converts a default unit value into a custom one
Parameters
unit Unit selector.
valueToConvert Input value.
rconvertedValue Output converted value.
rrange Output range.
Implemented in DriverMicos_Pollux, DriverNewFocus_8750_Cl, DriverNewFocus_8750_Ol, DriverNewPort_AGUC2, DriverNewPort_NSC200, DriverPI_C509, DriverPI_C862, DriverPI_E725, DriverStanda_uSMC2, and DriverStanda_uSMC.
Create() [1/2]
Driver * Driver::Create (const Driver * prefActuatorDrv, ACCom * prefChannel) static
pointer on the reference driver and channel
Creates a new driver instance.
Parameters
prefActuatorDrv Reference driver to copy.
prefChannel Communication channel instance.
Operation : Create Instantiates a subclass and returns a pointer on it
Definition at line 123 of file Driver.cpp.
References Driver().
Create() [2/2]
Driver * Driver::Create (string driverType, string setting, ACCom * channel) static
Driver type to instantiate and settings.
Creates a new driver instance.
Parameters
driverType Driver identifier.
setting Driver settings string.
channel Communication channel instance.
Operation : Create Instantiates a subclass and returns a pointer on it
Definition at line 56 of file Driver.cpp.
References _lastError, _setting, Driver(), MICOS_POLLUX, NEWFOCUS_8750_CL, NEWFOCUS_8750_OL, NEWPORT_AGUC2, NEWPORT_NSC200, PI_C509, PI_C862, PI_E725, STANDA_USMC, and STANDA_USMC2.
Referenced by Motor::connectMotor().
Exit()
virtual int Driver::Exit (string actuatorSetting) inline virtual
Optional shutdown hook; default is no-op.
Parameters
actuatorSetting Settings string for shutdown.
Reimplemented in DriverStanda_uSMC.
Definition at line 215 of file Driver.h.
GetActuatorFeature()
virtual int Driver::GetActuatorFeature (DriverDefinition::DriverFeature & ractuatorFeature) const pure virtual
Gives the features of the steered actuator
Parameters
ractuatorFeature steered actuator feature
Implemented in DriverMicos_Pollux, DriverNewFocus_8750_Cl, DriverNewFocus_8750_Ol, DriverNewPort_AGUC2, DriverNewPort_NSC200, DriverPI_C509, DriverPI_C862, DriverPI_E725, DriverStanda_uSMC2, and DriverStanda_uSMC.
GetLastError()
int Driver::GetLastError (DriverDefinition::ADErrorCode & lastError) virtual
code of the last error
Gives the code of the last problem
Parameters
lastError code of the last error
Operation : GetLastError Gives the code of the last problem
Definition at line 195 of file Driver.cpp.
References _lastError.
GetPos()
virtual int Driver::GetPos (string actuatorSetting, float & position) const pure virtual
Retrieves the current position of the actuator.
Parameters
actuatorSetting This string contains the settings that have to be applied for getting the position
position Returns the current position
Implemented in DriverMicos_Pollux, DriverNewFocus_8750_Cl, DriverNewFocus_8750_Ol, DriverNewPort_AGUC2, DriverNewPort_NSC200, DriverPI_C509, DriverPI_C862, DriverPI_E725, DriverStanda_uSMC2, and DriverStanda_uSMC.
Init()
virtual int Driver::Init (string & rstateData) const pure virtual
Initializes the driver.
Parameters
rstateData Output state data string.
Implemented in DriverMicos_Pollux, DriverNewFocus_8750_Cl, DriverNewFocus_8750_Ol, DriverNewPort_AGUC2, DriverNewPort_NSC200, DriverPI_C509, DriverPI_C862, DriverPI_E725, DriverStanda_uSMC2, and DriverStanda_uSMC.
Referenced by Motor::connectMotor().
InitActuator()
virtual int Driver::InitActuator (string actuatorSetting, float position) const pure virtual
Initializes the hardware device.
Parameters
actuatorSetting
position This string contains the information for the setting to be applied during the harwdare initialization
Implemented in DriverMicos_Pollux, DriverNewFocus_8750_Cl, DriverNewFocus_8750_Ol, DriverNewPort_AGUC2, DriverNewPort_NSC200, DriverPI_C509, DriverPI_C862, DriverPI_E725, DriverStanda_uSMC2, and DriverStanda_uSMC.
Move()
virtual int Driver::Move (string actuatorSetting, float nbSteps, int unit) const pure virtual
Performs a relative movement of the actuator.
Parameters
actuatorSetting This string contains the settings that have to be applied for the moving action
nbSteps Defines the relative displacement that should be applied
unit unit used for the motion.0 = default unit, 1 = custom one
Implemented in DriverMicos_Pollux, DriverNewFocus_8750_Cl, DriverNewFocus_8750_Ol, DriverNewPort_AGUC2, DriverNewPort_NSC200, DriverPI_C509, DriverPI_C862, DriverPI_E725, DriverStanda_uSMC2, and DriverStanda_uSMC.
MoveAbs()
virtual int Driver::MoveAbs (string actuatorSetting, float absPos, int unit) const pure virtual
Performs an absolute movement of the actuator.
Parameters
actuatorSetting This string contains the settings that have to be applied for the moving action
absPos Defines the absolute position where the actuator should be moved to
unit unit used for the motion.0 = default unit, 1 = custom one
Implemented in DriverMicos_Pollux, DriverNewFocus_8750_Cl, DriverNewFocus_8750_Ol, DriverNewPort_AGUC2, DriverNewPort_NSC200, DriverPI_C509, DriverPI_C862, DriverPI_E725, DriverStanda_uSMC2, and DriverStanda_uSMC.
OperationComplete()
virtual int Driver::OperationComplete (string & rstateData, string actuatorSetting, DriverDefinition::ADLimitSwitch & rlimitSwitch) const pure virtual
Checks if an operation has been finished or not.
Parameters
rstateData state data of the driver
actuatorSetting This string contains the settings that have to be applied
rlimitSwitch Reached limit flag
Implemented in DriverMicos_Pollux, DriverNewFocus_8750_Cl, DriverNewFocus_8750_Ol, DriverNewPort_AGUC2, DriverNewPort_NSC200, DriverPI_C509, DriverPI_C862, DriverPI_E725, DriverStanda_uSMC2, and DriverStanda_uSMC.
operator=()
Driver & Driver::operator= (Driver & actuatorDrv) inline
Affectation Operator.
Definition at line 101 of file Driver.h.
References _lastError, _pcommChannel, _setting, and Driver().
ReportCommError()
void Driver::ReportCommError (const QString & message) const protected
Log a communication-layer error.
Parameters
message Error message.
Definition at line 224 of file Driver.cpp.
References ReportError().
Referenced by DriverMicos_Pollux::GetPos(), DriverNewPort_AGUC2::GetPos(), DriverPI_C509::GetPos(), DriverPI_C862::GetPos(), DriverPI_E725::GetPos(), DriverNewPort_AGUC2::Init(), DriverPI_C509::Init(), DriverPI_E725::Init(), DriverMicos_Pollux::InitActuator(), DriverNewPort_NSC200::InitActuator(), DriverPI_C862::InitActuator(), DriverPI_E725::InitActuator(), DriverMicos_Pollux::Move(), DriverNewPort_AGUC2::Move(), DriverPI_C509::Move(), DriverPI_C862::Move(), DriverPI_E725::Move(), DriverMicos_Pollux::MoveAbs(), DriverPI_C509::MoveAbs(), DriverPI_C862::MoveAbs(), DriverPI_E725::MoveAbs(), DriverMicos_Pollux::OperationComplete(), DriverNewPort_AGUC2::OperationComplete(), DriverPI_C509::OperationComplete(), DriverPI_C862::OperationComplete(), DriverPI_E725::OperationComplete(), DriverPI_C862::SendAddressCode(), SendGeneralCommand(), DriverNewPort_AGUC2::SendGeneralCommand(), DriverMicos_Pollux::Stop(), DriverNewPort_AGUC2::Stop(), DriverPI_C509::Stop(), DriverPI_C862::Stop(), and DriverPI_E725::Stop().
ReportError()
void Driver::ReportError (DriverDefinition::ADErrorCode code, const QString & message) const protected
Log an error with a driver error code.
Parameters
code Error code.
message Error message.
Definition at line 211 of file Driver.cpp.
References _lastError, and Utils::ReportError().
Referenced by ReportCommError().
ReportRangeError()
void Driver::ReportRangeError (const QString & message) const protected
Log a range/limits error.
Parameters
message Error message.
Definition at line 229 of file Driver.cpp.
References ReportWarning().
Referenced by DriverNewPort_NSC200::Init(), DriverNewPort_NSC200::InitActuator(), DriverNewPort_NSC200::OperationComplete(), DriverMicos_Pollux::SendAddressCode(), and DriverPI_C862::SendAddressCode().
ReportSettingError()
void Driver::ReportSettingError (const QString & message) const protected
Log a setting parsing/validation error.
Parameters
message Error message.
Definition at line 219 of file Driver.cpp.
References ReportWarning().
Referenced by DriverStanda_uSMC::Exit(), DriverNewPort_AGUC2::GetPos(), DriverPI_C509::GetPos(), DriverPI_E725::GetPos(), DriverStanda_uSMC2::GetPos(), DriverStanda_uSMC::GetPos(), DriverNewPort_NSC200::Init(), DriverPI_E725::Init(), DriverMicos_Pollux::InitActuator(), DriverNewFocus_8750_Cl::InitActuator(), DriverNewFocus_8750_Ol::InitActuator(), DriverPI_C509::InitActuator(), DriverPI_C862::InitActuator(), DriverPI_E725::InitActuator(), DriverStanda_uSMC2::InitActuator(), DriverStanda_uSMC::InitActuator(), DriverNewFocus_8750_Ol::Move(), DriverNewPort_AGUC2::Move(), DriverPI_C509::Move(), DriverPI_E725::Move(), DriverStanda_uSMC2::Move(), DriverStanda_uSMC::Move(), DriverPI_C509::MoveAbs(), DriverPI_E725::MoveAbs(), DriverStanda_uSMC2::MoveAbs(), DriverStanda_uSMC::MoveAbs(), DriverNewPort_AGUC2::OperationComplete(), DriverNewPort_NSC200::OperationComplete(), DriverPI_C509::OperationComplete(), DriverPI_E725::OperationComplete(), DriverStanda_uSMC2::OperationComplete(), DriverStanda_uSMC::OperationComplete(), DriverNewPort_NSC200::SelectedSwitchBoxChannel(), DriverMicos_Pollux::SendAddressCode(), DriverPI_C862::SendAddressCode(), DriverNewPort_AGUC2::Stop(), DriverPI_C509::Stop(), DriverPI_E725::Stop(), DriverStanda_uSMC2::Stop(), and DriverStanda_uSMC::Stop().
ReportWarning()
void Driver::ReportWarning (DriverDefinition::ADErrorCode code, const QString & message) const protected
Log a warning with a driver error code.
Parameters
code Error code.
message Warning message.
Definition at line 203 of file Driver.cpp.
References _lastError, and Utils::ReportWarning().
Referenced by DriverPI_E725::GetPos(), DriverNewPort_NSC200::InitActuator(), ReportRangeError(), and ReportSettingError().
SendGeneralCommand()
int Driver::SendGeneralCommand (char * buffer, string & rply) const virtual
Send a driver-specific command string and return the reply.
Parameters
buffer Command buffer.
rply Output reply string.
Operation : SendCommand Sends a command to the motor driver interface
command line text buffer and reply string
Reimplemented in DriverNewPort_AGUC2.
Definition at line 240 of file Driver.cpp.
References _pcommChannel, ReportCommError(), and Tokenize().
Stop()
virtual int Driver::Stop (string actuatorSetting) const pure virtual
Stops the current movement of the actuator.
Parameters
actuatorSetting This string contains the settings that have to be applied for stopping the movement
Implemented in DriverMicos_Pollux, DriverNewFocus_8750_Cl, DriverNewFocus_8750_Ol, DriverNewPort_AGUC2, DriverNewPort_NSC200, DriverPI_C509, DriverPI_C862, DriverPI_E725, DriverStanda_uSMC2, and DriverStanda_uSMC.
Tokenize()
void Driver::Tokenize (const string & str, vector< string > & tokens, const string & delimiters = " ") const protected
Split a string into tokens using the given delimiters.
Parameters
str Input string.
tokens Output token list.
delimiters Delimiter characters.
Definition at line 278 of file Driver.cpp.
Referenced by DriverPI_E725::GetPos(), SendGeneralCommand(), and DriverNewPort_AGUC2::SendGeneralCommand().
Member Data Documentation
_lastError
DriverDefinition::ADErrorCode Driver::_lastError mutable protected
Code of the last error.
Definition at line 220 of file Driver.h.
Referenced by Create(), Driver(), Driver(), Driver(), GetLastError(), DriverNewPort_AGUC2::GetPos(), DriverNewPort_AGUC2::Init(), DriverMicos_Pollux::Move(), DriverNewFocus_8750_Cl::Move(), DriverNewFocus_8750_Ol::Move(), DriverNewPort_AGUC2::Move(), DriverNewPort_NSC200::Move(), DriverPI_C509::Move(), DriverPI_C862::Move(), DriverNewPort_AGUC2::OperationComplete(), operator=(), ReportError(), ReportWarning(), DriverNewPort_NSC200::SelectedSwitchBoxChannel(), and DriverNewPort_AGUC2::Stop().
_pcommChannel
ACCom* Driver::_pcommChannel protected
Actuator communication channel.
Definition at line 224 of file Driver.h.
Referenced by Driver(), Driver(), Driver(), DriverMicos_Pollux::GetPos(), DriverNewPort_AGUC2::GetPos(), DriverNewPort_NSC200::GetPos(), DriverPI_C509::GetPos(), DriverPI_C862::GetPos(), DriverPI_E725::GetPos(), DriverNewPort_AGUC2::Init(), DriverNewPort_NSC200::Init(), DriverPI_C509::Init(), DriverPI_E725::Init(), DriverMicos_Pollux::InitActuator(), DriverNewPort_NSC200::InitActuator(), DriverPI_C509::InitActuator(), DriverPI_C862::InitActuator(), DriverPI_E725::InitActuator(), DriverMicos_Pollux::Move(), DriverNewPort_AGUC2::Move(), DriverNewPort_NSC200::Move(), DriverPI_C509::Move(), DriverPI_C862::Move(), DriverPI_E725::Move(), DriverMicos_Pollux::MoveAbs(), DriverNewPort_NSC200::MoveAbs(), DriverPI_C509::MoveAbs(), DriverPI_C862::MoveAbs(), DriverPI_E725::MoveAbs(), DriverMicos_Pollux::OperationComplete(), DriverNewPort_AGUC2::OperationComplete(), DriverNewPort_NSC200::OperationComplete(), DriverPI_C509::OperationComplete(), DriverPI_C862::OperationComplete(), DriverPI_E725::OperationComplete(), operator=(), DriverMicos_Pollux::operator=(), DriverNewFocus_8750_Cl::operator=(), DriverNewFocus_8750_Ol::operator=(), DriverNewPort_AGUC2::operator=(), DriverNewPort_NSC200::operator=(), DriverPI_C509::operator=(), DriverPI_C862::operator=(), DriverPI_E725::operator=(), DriverStanda_uSMC2::operator=(), DriverStanda_uSMC::operator=(), DriverNewPort_NSC200::SelectedSwitchBoxChannel(), DriverPI_C862::SendAddressCode(), SendGeneralCommand(), DriverNewPort_AGUC2::SendGeneralCommand(), DriverMicos_Pollux::Stop(), DriverNewPort_AGUC2::Stop(), DriverNewPort_NSC200::Stop(), DriverPI_C509::Stop(), DriverPI_C862::Stop(), and DriverPI_E725::Stop().
_setting
string Driver::_setting protected
Driver setting string.
Definition at line 222 of file Driver.h.
Referenced by Create(), Driver(), Driver(), DriverNewFocus_8750_Cl::GetPos(), DriverNewFocus_8750_Ol::GetPos(), DriverNewFocus_8750_Cl::Init(), DriverNewFocus_8750_Ol::Init(), DriverNewPort_NSC200::Init(), DriverPI_E725::Init(), DriverNewFocus_8750_Cl::InitActuator(), DriverNewFocus_8750_Ol::InitActuator(), DriverNewFocus_8750_Cl::Move(), DriverNewFocus_8750_Ol::Move(), DriverNewFocus_8750_Cl::MoveAbs(), DriverNewFocus_8750_Cl::OperationComplete(), DriverNewFocus_8750_Ol::OperationComplete(), DriverNewPort_NSC200::OperationComplete(), operator=(), DriverNewPort_NSC200::SelectedSwitchBoxChannel(), DriverMicos_Pollux::SendAddressCode(), DriverPI_C862::SendAddressCode(), DriverNewFocus_8750_Cl::Stop(), and DriverNewFocus_8750_Ol::Stop().
MICOS_POLLUX
const string Driver::MICOS_POLLUX = "Micos_Pollux" static
Identifier for the Rotor driver.
Definition at line 55 of file Driver.h.
Referenced by Create().
NEWFOCUS_8750_CL
const string Driver::NEWFOCUS_8750_CL = "NewFocus_8750_Cl" static
Identifier for the Ethernet-Closed-Loop-PIcomotor driver.
Definition at line 51 of file Driver.h.
Referenced by Create().
NEWFOCUS_8750_OL
const string Driver::NEWFOCUS_8750_OL = "NewFocus_8750_Ol" static
Identifier for the Ethernet-PIcomotor driver.
Definition at line 49 of file Driver.h.
Referenced by Create().
NEWPORT_AGUC2
const string Driver::NEWPORT_AGUC2 = "NewPort_AGUC2" static
Identifier for the NEWPORT_AGUC2.
Definition at line 67 of file Driver.h.
Referenced by Create().
NEWPORT_NSC200
const string Driver::NEWPORT_NSC200 = "NewPort_NSC200" static
Identifier for the NSA driver.
Definition at line 57 of file Driver.h.
Referenced by Create().
NULL_DRV_ID
const string Driver::NULL_DRV_ID static
Identifier for the NULL driver.
Definition at line 63 of file Driver.h.
PI_C509
const string Driver::PI_C509 = "PI_C509" static
Identifier for the Translation Stage driver.
Definition at line 53 of file Driver.h.
Referenced by Create().
PI_C862
const string Driver::PI_C862 = "PI_C862" static
Identifier for the PIezo driver.
Definition at line 47 of file Driver.h.
Referenced by Create().
PI_E725
const string Driver::PI_E725 = "PI_E725" static
Identifier for the PI_E725 driver.
Definition at line 65 of file Driver.h.
Referenced by Create().
STANDA_USMC
const string Driver::STANDA_USMC = "Standa_uSMC" static
Identifier for the STANDA (old) driver.
Definition at line 59 of file Driver.h.
Referenced by Create().
STANDA_USMC2
const string Driver::STANDA_USMC2 = "Standa_uSMC2" static
Identifier for the STANDA driver.
Definition at line 61 of file Driver.h.
Referenced by Create().
The documentation for this class was generated from the following files:
Driver.h
Driver.cpp