OpticsBenchUI: ACEthCom Class Reference
ACEthCom Class Reference
Ethernet-based communication channel.
#include <ACEthCom.h>
Public Member Functions
ACEthCom (string device, string settings)
ACEthCom (const ACEthCom &channel)
virtual int Open ()
virtual int Read (string &message,...)
virtual int Write (string &message,...)
virtual int Close ()
Public Member Functions inherited from ACCom
ACCom (string device, string settings)
ACCom (const ACCom &channel)
virtual ~ACCom ()
virtual int GetStatus () const
Additional Inherited Members
Public Types inherited from ACCom
enum { OPEN , CLOSED }
Static Public Member Functions inherited from ACCom
static ACCom * Create (string channelType, string device, string settings)
static ACCom * Create (const ACCom *prefChannel)
Static Public Attributes inherited from ACCom
static const string RS_COM = "SERIAL_PORT"
static const string ETH_COM = "ETHERNET"
static const string MB_COM = "MB_COM"
static const string USB_COM = "USB_COM"
static const string CAN_COM = "CAN_COM"
static const string NULL_COM = "NULL_COM"
Protected Member Functions inherited from ACCom
void ReportWarning (const QString &message) const
Log a warning message tagged with this communication channel.
void ReportError (const QString &message) const
Log an error message tagged with this communication channel.
Protected Attributes inherited from ACCom
int _state
string _device
string _settings
Detailed Description
Ethernet-based communication channel.
Definition at line 28 of file ACEthCom.h.
Constructor & Destructor Documentation
ACEthCom() [1/2]
ACEthCom::ACEthCom (string device, string settings) inline
Constructor
Definition at line 34 of file ACEthCom.h.
References ACCom::ACCom().
Referenced by ACEthCom().
ACEthCom() [2/2]
ACEthCom::ACEthCom (const ACEthCom & channel) inline
Constructor
Definition at line 43 of file ACEthCom.h.
References ACCom::ACCom(), and ACEthCom().
Member Function Documentation
Close()
int ACEthCom::Close () virtual
The Close method allows to close the channel
Operation : Close Closes the communcation
Implements ACCom.
Definition at line 319 of file ACEthCom.cpp.
References ACCom::_state.
Open()
int ACEthCom::Open () virtual
The Open method allows to open the channel
Operation : Open Opens the communication channel by creating a socket and connecting to it
Implements ACCom.
Definition at line 49 of file ACEthCom.cpp.
References ACCom::_device, ACCom::_settings, ACCom::_state, ACCom::ReportError(), and ACCom::ReportWarning().
Read()
int ACEthCom::Read (string & message, ...) virtual
The Read method allows to read in the channel
Parameters
message The message to be read
... The parametrization must be either of the following:
NULL : default mode
"DELAY",delay (usec) : using a specific delay before reading
Operation : Read reads data through the socket message to read
Implements ACCom.
Definition at line 241 of file ACEthCom.cpp.
Write()
int ACEthCom::Write (string & message, ...) virtual
The Write method allows to write in the channel
Parameters
message The message to be read
... The parametrization must be either of the following:
NULL : default mode (default includes NULL terminal character)
"RAW" : does not include NULL terminal character
"ECHO" : echo mode writes character by character, each write followed by a single character read. The message string must be finished with "\r" character
Operation : Write sends data through the socket message to send
Implements ACCom.
Definition at line 142 of file ACEthCom.cpp.
References ACCom::ReportWarning().
The documentation for this class was generated from the following files:
ACEthCom.h
ACEthCom.cpp