OpticsBenchUI: VideoPlayer Class Reference
VideoPlayer Class Reference
UI
#include <VideoPlayer.h>
Public Slots
void setVideoPlayerResolution (int width, int height)
Signals
void setImageSize (const int &width, const int &height)
Public Member Functions
VideoPlayer (QWidget *parent=0, Camera *_camera=0)
~VideoPlayer ()
Destructor.
Public Attributes
Camera * camera
Camera providing frames.
Protected Member Functions
void closeEvent (QCloseEvent *event)
Detailed Description
Widget for displaying live camera frames.
Definition at line 11 of file VideoPlayer.h.
Constructor & Destructor Documentation
VideoPlayer()
VideoPlayer::VideoPlayer (QWidget * parent = 0, Camera * _camera = 0)
Construct a video player for a camera.
Parameters
parent Parent widget.
_camera Camera providing frames.
Definition at line 5 of file VideoPlayer.cpp.
References camera, setImageSize(), setVideoPlayerResolution(), and VideoWidget::videoSurface().
~VideoPlayer()
VideoPlayer::~VideoPlayer ()
Destructor.
Definition at line 27 of file VideoPlayer.cpp.
References camera.
Member Function Documentation
closeEvent()
void VideoPlayer::closeEvent (QCloseEvent * event) protected
Handle window close events.
Parameters
event Close event.
Definition at line 32 of file VideoPlayer.cpp.
setImageSize
void VideoPlayer::setImageSize (const int & width, const int & height) signal
Request a new image size.
Parameters
width Width in pixels.
height Height in pixels.
Referenced by setVideoPlayerResolution(), and VideoPlayer().
setVideoPlayerResolution
void VideoPlayer::setVideoPlayerResolution (int width, int height) slot
Set the video player resolution.
Parameters
width Width in pixels.
height Height in pixels.
Definition at line 76 of file VideoPlayer.cpp.
References setImageSize().
Referenced by VideoPlayer().
Member Data Documentation
camera
Camera* VideoPlayer::camera
Camera providing frames.
Definition at line 22 of file VideoPlayer.h.
Referenced by VideoPlayer(), and ~VideoPlayer().
The documentation for this class was generated from the following files:
VideoPlayer.h
VideoPlayer.cpp