OpticsBenchUI: AnalysisWidget Class Reference
AnalysisWidget Class Reference
UI
#include <AnalysisWidget.h>
Public Slots
void update ()
Refresh displayed values.
void reload ()
Reload the analysis table.
void remove ()
Remove the selected analysis row.
void run ()
Start analysis.
void stop ()
Stop analysis.
void setDbPath (QString path)
void runFromAcquisition ()
Run analysis triggered by acquisition.
void analysisStarted (int record)
void analysisFinished (int record, bool success, const QString &output)
void analysisOutput (int record, const QString &output)
void showAnalysisWarning (QString message)
Signals
void showWarning (QString message)
Public Member Functions
AnalysisWidget (QString appDirPath=QString())
Constructor.
~AnalysisWidget () override
Destructor.
Detailed Description
UI widget for analysis tools.
Definition at line 33 of file AnalysisWidget.h.
Constructor & Destructor Documentation
AnalysisWidget()
AnalysisWidget::AnalysisWidget (QString appDirPath = QString()) explicit
Constructor.
Definition at line 32 of file AnalysisWidget.cpp.
References analysisFinished(), analysisOutput(), analysisStarted(), Utils::ConfigureSqlTableView(), QLOG_DEBUG, reload(), remove(), run(), showAnalysisWarning(), showWarning(), stop(), and update().
~AnalysisWidget()
AnalysisWidget::~AnalysisWidget () override
Destructor.
Definition at line 100 of file AnalysisWidget.cpp.
References QLOG_DEBUG, and AnalysisThread::stop().
Member Function Documentation
analysisFinished
void AnalysisWidget::analysisFinished (int record, bool success, const QString & output) slot
Update status label when a task finishes.
Parameters
record Task record index.
success True if the command succeeded.
output Process output.
Definition at line 210 of file AnalysisWidget.cpp.
References QLOG_INFO.
Referenced by AnalysisWidget().
analysisOutput
void AnalysisWidget::analysisOutput (int record, const QString & output) slot
Append streaming output from the analysis process.
Parameters
record Task record index.
output Output chunk.
Definition at line 222 of file AnalysisWidget.cpp.
Referenced by AnalysisWidget().
analysisStarted
void AnalysisWidget::analysisStarted (int record) slot
Update status label when a task starts.
Parameters
record Task record index.
Definition at line 205 of file AnalysisWidget.cpp.
Referenced by AnalysisWidget().
reload
void AnalysisWidget::reload () slot
Reload the analysis table.
Definition at line 151 of file AnalysisWidget.cpp.
Referenced by AnalysisWidget().
remove
void AnalysisWidget::remove () slot
Remove the selected analysis row.
Definition at line 155 of file AnalysisWidget.cpp.
Referenced by AnalysisWidget().
run
void AnalysisWidget::run () slot
Start analysis.
Definition at line 186 of file AnalysisWidget.cpp.
References QLOG_DEBUG, AnalysisThread::setTasks(), and stop().
Referenced by AnalysisWidget(), and runFromAcquisition().
runFromAcquisition
void AnalysisWidget::runFromAcquisition () slot
Run analysis triggered by acquisition.
Definition at line 195 of file AnalysisWidget.cpp.
References QLOG_INFO, and run().
setDbPath
void AnalysisWidget::setDbPath (QString path) slot
Set the database path used by the widget.
Parameters
path Filesystem path to DBs.
Definition at line 110 of file AnalysisWidget.cpp.
References Utils::ConfigureSqlTableView().
showAnalysisWarning
void AnalysisWidget::showAnalysisWarning (QString message) slot
Show analysis warning to the user.
Parameters
message Warning message.
Definition at line 232 of file AnalysisWidget.cpp.
References Utils::EmitWarning().
Referenced by AnalysisWidget().
showWarning
void AnalysisWidget::showWarning (QString message) signal
Emit warnings to the UI.
Parameters
message Warning message.
Referenced by AnalysisWidget().
stop
void AnalysisWidget::stop () slot
Stop analysis.
Definition at line 200 of file AnalysisWidget.cpp.
References AnalysisThread::stop().
Referenced by AnalysisWidget(), and run().
update
void AnalysisWidget::update () slot
Refresh displayed values.
Definition at line 146 of file AnalysisWidget.cpp.
Referenced by AnalysisWidget().
The documentation for this class was generated from the following files:
AnalysisWidget.h
AnalysisWidget.cpp