OpticsBenchUI: AcquisitionThread Class Reference
AcquisitionThread Class Reference
#include <AcquisitionThread.h>
Signals
void getPosition (QString positionQString)
void getSuperKData (QString dataStr)
void getPower (int power)
void getNd (int nd)
void getSwp (int swp)
void getLwp (int lwp)
void getCameraStatus (bool imagesuccess)
void getDacStatus (bool dacsuccess)
void getMotorStatus (bool motorsuccess)
void getSuperKStatus (bool superksuccess)
void getTreatmentStatus (bool treatmentsuccess)
void getAcquiring (int record)
void getFilenumber (int number)
void showWarning (QString message)
void splashScreen (QString imagepath, int screen_x, int screen_y)
void requestAnalysis ()
Request analysis execution (triggered by ANALYSE=START in settings).
Public Member Functions
AcquisitionThread (QObject *parent=nullptr)
Create a new acquisition thread.
~AcquisitionThread () override
Destructor.
void setCamera (const QVector< Camera * > &cameraList)
void setMotor (Motor *motor)
void setSuperK (SuperK *superk)
void setDac (Dac *dac)
void setComediCounter (Comedi *comedi)
void setComediDac (Comedi *comedi)
void setRaspiDac (Raspi *raspi)
void setFile (const QString &filename, int filenumber)
void setSequenceList (const QVector< AcquisitionSequence * > &sequenceList)
void setIsOpenCameraWindow (const QVector< bool > &isOpenCameraWindow)
void wakeSplashScreen ()
Wake the splash screen waiting for acquisition.
void stop ()
Request the thread to stop.
Protected Member Functions
void run () override
Thread entry point.
Detailed Description
Executes acquisition sequences in a worker thread.
This thread coordinates cameras, motors, DACs, and file I/O for each acquisition record and emits progress/status signals to the UI.
Definition at line 35 of file AcquisitionThread.h.
Constructor & Destructor Documentation
AcquisitionThread()
AcquisitionThread::AcquisitionThread (QObject * parent = nullptr) explicit
Create a new acquisition thread.
Definition at line 23 of file AcquisitionThread.cpp.
~AcquisitionThread()
AcquisitionThread::~AcquisitionThread () override
Destructor.
Definition at line 53 of file AcquisitionThread.cpp.
References stop().
Member Function Documentation
getAcquiring
void AcquisitionThread::getAcquiring (int record) signal
Emit acquisition progress record.
Parameters
record Current record index.
Referenced by run().
getCameraStatus
void AcquisitionThread::getCameraStatus (bool imagesuccess) signal
Emit camera acquisition status.
Parameters
imagesuccess True if image acquisition succeeded.
getDacStatus
void AcquisitionThread::getDacStatus (bool dacsuccess) signal
Emit DAC status.
Parameters
dacsuccess True if DAC operation succeeded.
getFilenumber
void AcquisitionThread::getFilenumber (int number) signal
Emit the current file number.
Parameters
number File index.
Referenced by run().
getLwp
void AcquisitionThread::getLwp (int lwp) signal
Emit SuperK LWP value.
Parameters
lwp LWP value.
getMotorStatus
void AcquisitionThread::getMotorStatus (bool motorsuccess) signal
Emit motor status.
Parameters
motorsuccess True if motor operation succeeded.
getNd
void AcquisitionThread::getNd (int nd) signal
Emit SuperK ND value.
Parameters
nd ND value.
getPosition
void AcquisitionThread::getPosition (QString positionQString) signal
Emit motor position text.
Parameters
positionQString Position string.
Referenced by run().
getPower
void AcquisitionThread::getPower (int power) signal
Emit SuperK power value.
Parameters
power Power value.
getSuperKData
void AcquisitionThread::getSuperKData (QString dataStr) signal
Emit SuperK data as text.
Parameters
dataStr Data string.
Referenced by run().
getSuperKStatus
void AcquisitionThread::getSuperKStatus (bool superksuccess) signal
Emit SuperK status.
Parameters
superksuccess True if SuperK operation succeeded.
getSwp
void AcquisitionThread::getSwp (int swp) signal
Emit SuperK SWP value.
Parameters
swp SWP value.
getTreatmentStatus
void AcquisitionThread::getTreatmentStatus (bool treatmentsuccess) signal
Emit treatment status.
Parameters
treatmentsuccess True if treatment succeeded.
run()
void AcquisitionThread::run () override protected
Thread entry point.
Definition at line 123 of file AcquisitionThread.cpp.
References Utils::CurrentTimestampString(), Utils::EmitWarning(), AcquisitionSequence::etime, getAcquiring(), getFilenumber(), getPosition(), getSuperKData(), Utils::GetTimeMicroseconds(), AcquisitionSequence::instrumentName, AcquisitionSequence::instrumentType, AcquisitionSequence::position, AcquisitionSequence::record, requestAnalysis(), AcquisitionSequence::seq_record, AcquisitionSequence::settings, AcquisitionSequence::sleep, Camera::stop(), AcquisitionSequence::superkLwpValue, AcquisitionSequence::superkNdValue, AcquisitionSequence::superkPowerValue, and AcquisitionSequence::superkSwpValue.
setCamera()
void AcquisitionThread::setCamera (const QVector< Camera * > & cameraList)
Set the list of active cameras.
Parameters
cameraList Cameras used during acquisition.
Definition at line 67 of file AcquisitionThread.cpp.
setComediCounter()
void AcquisitionThread::setComediCounter (Comedi * comedi)
Provide the Comedi counter controller.
Parameters
comedi Comedi counter instance.
Definition at line 83 of file AcquisitionThread.cpp.
setComediDac()
void AcquisitionThread::setComediDac (Comedi * comedi)
Provide the Comedi DAC controller.
Parameters
comedi Comedi DAC instance.
Definition at line 87 of file AcquisitionThread.cpp.
setDac()
void AcquisitionThread::setDac (Dac * dac)
Provide the DAC controller.
Parameters
dac DAC controller instance.
Definition at line 79 of file AcquisitionThread.cpp.
setFile()
void AcquisitionThread::setFile (const QString & filename, int filenumber)
Set the output filename and index.
Parameters
filename Base output filename.
filenumber Output file index.
Definition at line 95 of file AcquisitionThread.cpp.
setIsOpenCameraWindow()
void AcquisitionThread::setIsOpenCameraWindow (const QVector< bool > & isOpenCameraWindow)
Set which camera windows are open in the UI.
Parameters
isOpenCameraWindow Per-camera open flags.
Definition at line 105 of file AcquisitionThread.cpp.
setMotor()
void AcquisitionThread::setMotor (Motor * motor)
Provide the motor controller.
Parameters
motor Motor controller instance.
Definition at line 71 of file AcquisitionThread.cpp.
setRaspiDac()
void AcquisitionThread::setRaspiDac (Raspi * raspi)
Provide the Raspi DAC controller.
Parameters
raspi Raspi DAC instance.
Definition at line 91 of file AcquisitionThread.cpp.
setSequenceList()
void AcquisitionThread::setSequenceList (const QVector< AcquisitionSequence * > & sequenceList)
Set the sequence list to execute.
Parameters
sequenceList Acquisition sequences to run.
Definition at line 100 of file AcquisitionThread.cpp.
setSuperK()
void AcquisitionThread::setSuperK (SuperK * superk)
Provide the SuperK laser controller.
Parameters
superk SuperK controller instance.
Definition at line 75 of file AcquisitionThread.cpp.
showWarning
void AcquisitionThread::showWarning (QString message) signal
Emit warnings to the UI.
Parameters
message Warning message.
splashScreen
void AcquisitionThread::splashScreen (QString imagepath, int screen_x, int screen_y) signal
Show a splash screen with image and position.
Parameters
imagepath Path to the splash image.
screen_x Screen X coordinate.
screen_y Screen Y coordinate.
stop()
void AcquisitionThread::stop ()
Request the thread to stop.
Definition at line 114 of file AcquisitionThread.cpp.
Referenced by ~AcquisitionThread().
wakeSplashScreen()
void AcquisitionThread::wakeSplashScreen ()
Wake the splash screen waiting for acquisition.
Definition at line 110 of file AcquisitionThread.cpp.
The documentation for this class was generated from the following files:
AcquisitionThread.h
AcquisitionThread.cpp