OpticsBenchUI: RaspiWindow Class Reference
RaspiWindow Class Reference
UI
#include <RaspiWindow.h>
Public Slots
void update ()
Update database-backed tables.
void remove ()
Remove selected entries.
void load ()
Load configuration into runtime.
void setDbPath (QString _path)
Public Member Functions
RaspiWindow (QMainWindow *parent=0, Qt::WindowFlags fl=Qt::Window, Raspi *_raspi=0)
virtual ~RaspiWindow ()
Destructor.
Public Attributes
RaspiDacControlWidget * raspiWidget
Raspi DAC control widget instance.
Protected Member Functions
void closeEvent (QCloseEvent *event)
Detailed Description
Window for Raspi DAC configuration and control.
Definition at line 32 of file RaspiWindow.h.
Constructor & Destructor Documentation
RaspiWindow()
RaspiWindow::RaspiWindow (QMainWindow * parent = 0, Qt::WindowFlags fl = Qt::Window, Raspi * _raspi = 0)
Construct a Raspi window.
Parameters
parent Parent window.
fl Window flags.
_raspi Raspi controller instance.
Definition at line 26 of file RaspiWindow.cpp.
References Utils::ConfigureSqlTableView(), load(), Raspi::path, QLOG_INFO, Raspi::raspitype, raspiWidget, remove(), RaspiDacControlWidget::setRaspi(), and update().
~RaspiWindow()
RaspiWindow::~RaspiWindow () virtual
Destructor.
Definition at line 88 of file RaspiWindow.cpp.
References QLOG_DEBUG, and raspiWidget.
Member Function Documentation
closeEvent()
void RaspiWindow::closeEvent (QCloseEvent * event) protected
Handle window close events.
Parameters
event Close event.
Definition at line 114 of file RaspiWindow.cpp.
References QLOG_DEBUG.
load
void RaspiWindow::load () slot
Load configuration into runtime.
Definition at line 139 of file RaspiWindow.cpp.
Referenced by RaspiWindow().
remove
void RaspiWindow::remove () slot
Remove selected entries.
Definition at line 143 of file RaspiWindow.cpp.
Referenced by RaspiWindow().
setDbPath
void RaspiWindow::setDbPath (QString _path) slot
Set the database path for tables.
Parameters
_path Filesystem path to the Raspi DB.
Definition at line 94 of file RaspiWindow.cpp.
References Utils::ConfigureSqlTableView(), Raspi::path, and Raspi::setDbPath().
update
void RaspiWindow::update () slot
Update database-backed tables.
Definition at line 134 of file RaspiWindow.cpp.
Referenced by RaspiWindow().
Member Data Documentation
raspiWidget
RaspiDacControlWidget* RaspiWindow::raspiWidget
Raspi DAC control widget instance.
Definition at line 48 of file RaspiWindow.h.
Referenced by RaspiWindow(), and ~RaspiWindow().
The documentation for this class was generated from the following files:
RaspiWindow.h
RaspiWindow.cpp