OpticsBenchUI: DriverMicos_Pollux Class Reference
DriverMicos_Pollux Class Reference
Hardware » Motors
#include <DriverMicos_Pollux.h>
Public Member Functions
DriverMicos_Pollux ()
Default constructor.
DriverMicos_Pollux (ACCom *commChannel)
DriverMicos_Pollux (const DriverMicos_Pollux &actuatorDrvMicos_Pollux, ACCom *commChannel)
virtual ~DriverMicos_Pollux ()
Destructor.
DriverMicos_Pollux (const DriverMicos_Pollux &actuatorDrvMicos_Pollux)
virtual DriverMicos_Pollux & operator= (const DriverMicos_Pollux &actuatorDrvMicos_Pollux)
virtual int Init (string &rstateData) const
Initialize the driver.
virtual int InitActuator (string actuatorSetting, float position) const
Initialize the actuator with settings and an optional position.
virtual int GetPos (string actuatorSetting, float &position) const
Read the current actuator position.
virtual int Move (string actuatorSetting, float nbSteps, int unit) const
Perform a relative motion.
virtual int MoveAbs (string actuatorSetting, float absPos, int unit) const
Perform an absolute motion.
virtual int Stop (string actuatorSetting) const
Stop the actuator.
virtual int OperationComplete (string &rstateData, string actuatorSetting, DriverDefinition::ADLimitSwitch &rlimitSwitch) const
Check whether the last operation has completed.
virtual int GetActuatorFeature (DriverDefinition::DriverFeature &ractuatorFeature) const
Get actuator feature metadata.
virtual int ConvertUnit (int unit, float valueToConvert, float &rconvertedValue, float &rrange) const
Convert between default and custom units.
Public Member Functions inherited from Driver
Driver ()
Constructor.
Driver (ACCom *commChannel)
Constructor with communication channel.
Driver (const Driver &actuatorDrv, ACCom *commChannel)
Constructor with driver reference and communication channel.
Driver (const Driver &actuatorDrv)
Copy Constructor.
virtual ~Driver ()
Destructor.
Driver & operator= (Driver &actuatorDrv)
Affectation Operator.
virtual int GetLastError (DriverDefinition::ADErrorCode &lastError)
code of the last error
virtual int SendGeneralCommand (char *buffer, string &rply) const
virtual int Exit (string actuatorSetting)
Protected Member Functions
int SendAddressCode () const
Send device address code.
Protected Member Functions inherited from Driver
void Tokenize (const string &str, vector< string > &tokens, const string &delimiters=" ") const
void ReportWarning (DriverDefinition::ADErrorCode code, const QString &message) const
void ReportError (DriverDefinition::ADErrorCode code, const QString &message) const
void ReportSettingError (const QString &message) const
void ReportCommError (const QString &message) const
void ReportRangeError (const QString &message) const
Protected Attributes
float _originOffset
Origin offset value.
int _axisNumber
Axis number.
Protected Attributes inherited from Driver
DriverDefinition::ADErrorCode _lastError
Code of the last error.
string _setting
Driver setting string.
ACCom * _pcommChannel
Actuator communication channel.
Static Protected Attributes
static const int BUFFER_SIZE = 32
Serial buffer size.
static const int MAX_DEVICES = 16
Maximum device count.
static const int NB_ITEM_INIT_SETTING = 1
Number of init settings items.
static const int NB_ITEM_DRV_SETTING = 1
Number of driver settings items.
static const DriverDefinition::DriverFeature MICOS_POLLUX_FEATURE
Micos Pollux features.
Additional Inherited Members
Static Public Member Functions inherited from Driver
static Driver * Create (string driverType, string setting, ACCom *channel)
Driver type to instantiate and settings.
static Driver * Create (const Driver *prefActuatorDrv, ACCom *prefChannel)
pointer on the reference driver and channel
Static Public Attributes inherited from Driver
static const string PI_C862 = "PI_C862"
Identifier for the PIezo driver.
static const string NEWFOCUS_8750_OL = "NewFocus_8750_Ol"
Identifier for the Ethernet-PIcomotor driver.
static const string NEWFOCUS_8750_CL = "NewFocus_8750_Cl"
Identifier for the Ethernet-Closed-Loop-PIcomotor driver.
static const string PI_C509 = "PI_C509"
Identifier for the Translation Stage driver.
static const string MICOS_POLLUX = "Micos_Pollux"
Identifier for the Rotor driver.
static const string NEWPORT_NSC200 = "NewPort_NSC200"
Identifier for the NSA driver.
static const string STANDA_USMC = "Standa_uSMC"
Identifier for the STANDA (old) driver.
static const string STANDA_USMC2 = "Standa_uSMC2"
Identifier for the STANDA driver.
static const string NULL_DRV_ID
Identifier for the NULL driver.
static const string PI_E725 = "PI_E725"
Identifier for the PI_E725 driver.
static const string NEWPORT_AGUC2 = "NewPort_AGUC2"
Identifier for the NEWPORT_AGUC2.
Detailed Description
Micos Pollux actuator driver implementation.
Definition at line 31 of file DriverMicos_Pollux.h.
Constructor & Destructor Documentation
DriverMicos_Pollux() [1/4]
DriverMicos_Pollux::DriverMicos_Pollux () inline
Default constructor.
Definition at line 36 of file DriverMicos_Pollux.h.
Referenced by DriverMicos_Pollux(), DriverMicos_Pollux(), and operator=().
DriverMicos_Pollux() [2/4]
DriverMicos_Pollux::DriverMicos_Pollux (ACCom * commChannel) inline
Construct with a communication channel.
Parameters
commChannel Communication channel instance.
Definition at line 40 of file DriverMicos_Pollux.h.
References Driver::Driver().
DriverMicos_Pollux() [3/4]
DriverMicos_Pollux::DriverMicos_Pollux (const DriverMicos_Pollux & actuatorDrvMicos_Pollux, ACCom * commChannel) inline
Copy-construct with a new communication channel.
Parameters
actuatorDrvMicos_Pollux Reference driver to copy.
commChannel Communication channel instance.
Definition at line 46 of file DriverMicos_Pollux.h.
References _originOffset, Driver::Driver(), and DriverMicos_Pollux().
~DriverMicos_Pollux()
virtual DriverMicos_Pollux::~DriverMicos_Pollux () inline virtual
Destructor.
Definition at line 53 of file DriverMicos_Pollux.h.
DriverMicos_Pollux() [4/4]
DriverMicos_Pollux::DriverMicos_Pollux (const DriverMicos_Pollux & actuatorDrvMicos_Pollux) inline
Copy constructor.
Parameters
actuatorDrvMicos_Pollux Reference driver to copy.
Definition at line 57 of file DriverMicos_Pollux.h.
References _originOffset, Driver::Driver(), and DriverMicos_Pollux().
Member Function Documentation
ConvertUnit()
int DriverMicos_Pollux::ConvertUnit (int unit, float valueToConvert, float & rconvertedValue, float & rrange) const virtual
Convert between default and custom units.
Operation : ConvertUnit Performs the following conversion :
from custom unit to default unit
no conversion
from default unit to custom converts a value into default motion unit if it is expressed in custom one and gives the range associated to the unit
Parameters
unit motion unit
valueToConvert value to be converted
rconvertedValue conversion result
rrange output range for the selected unit
Implements Driver.
Definition at line 407 of file DriverMicos_Pollux.cpp.
References MICOS_POLLUX_FEATURE.
Referenced by Move(), and MoveAbs().
GetActuatorFeature()
int DriverMicos_Pollux::GetActuatorFeature (DriverDefinition::DriverFeature & ractuatorFeature) const virtual
Get actuator feature metadata.
Implements Driver.
Definition at line 345 of file DriverMicos_Pollux.cpp.
References MICOS_POLLUX_FEATURE.
GetPos()
int DriverMicos_Pollux::GetPos (string actuatorSetting, float & position) const virtual
Read the current actuator position.
Implements Driver.
Definition at line 107 of file DriverMicos_Pollux.cpp.
References _axisNumber, _originOffset, Driver::_pcommChannel, BUFFER_SIZE, Driver::ReportCommError(), and SendAddressCode().
Init()
int DriverMicos_Pollux::Init (string & rstateData) const virtual
Initialize the driver.
Implements Driver.
Definition at line 39 of file DriverMicos_Pollux.cpp.
References OperationComplete().
InitActuator()
int DriverMicos_Pollux::InitActuator (string actuatorSetting, float position) const virtual
Initialize the actuator with settings and an optional position.
Implements Driver.
Definition at line 58 of file DriverMicos_Pollux.cpp.
References _axisNumber, _originOffset, Driver::_pcommChannel, BUFFER_SIZE, NB_ITEM_INIT_SETTING, Driver::ReportCommError(), Driver::ReportSettingError(), and SendAddressCode().
Move()
int DriverMicos_Pollux::Move (string actuatorSetting, float nbSteps, int unit) const virtual
Perform a relative motion.
Implements Driver.
Definition at line 157 of file DriverMicos_Pollux.cpp.
References _axisNumber, Driver::_lastError, Driver::_pcommChannel, BUFFER_SIZE, ConvertUnit(), Driver::ReportCommError(), and SendAddressCode().
MoveAbs()
int DriverMicos_Pollux::MoveAbs (string actuatorSetting, float absPos, int unit) const virtual
Perform an absolute motion.
Implements Driver.
Definition at line 204 of file DriverMicos_Pollux.cpp.
References _axisNumber, _originOffset, Driver::_pcommChannel, BUFFER_SIZE, ConvertUnit(), Driver::ReportCommError(), and SendAddressCode().
OperationComplete()
int DriverMicos_Pollux::OperationComplete (string & rstateData, string actuatorSetting, DriverDefinition::ADLimitSwitch & rlimitSwitch) const virtual
Check whether the last operation has completed.
Implements Driver.
Definition at line 284 of file DriverMicos_Pollux.cpp.
References _axisNumber, Driver::_pcommChannel, BUFFER_SIZE, Driver::ReportCommError(), and SendAddressCode().
Referenced by Init().
operator=()
virtual DriverMicos_Pollux & DriverMicos_Pollux::operator= (const DriverMicos_Pollux & actuatorDrvMicos_Pollux) inline virtual
Assignment operator.
Parameters
actuatorDrvMicos_Pollux Reference driver to copy.
Definition at line 65 of file DriverMicos_Pollux.h.
References _originOffset, Driver::_pcommChannel, and DriverMicos_Pollux().
SendAddressCode()
int DriverMicos_Pollux::SendAddressCode () const protected
Send device address code.
Definition at line 363 of file DriverMicos_Pollux.cpp.
References _axisNumber, Driver::_setting, MAX_DEVICES, Driver::ReportRangeError(), and Driver::ReportSettingError().
Referenced by GetPos(), InitActuator(), Move(), MoveAbs(), OperationComplete(), and Stop().
Stop()
int DriverMicos_Pollux::Stop (string actuatorSetting) const virtual
Stop the actuator.
Implements Driver.
Definition at line 246 of file DriverMicos_Pollux.cpp.
References _axisNumber, Driver::_pcommChannel, BUFFER_SIZE, Driver::ReportCommError(), and SendAddressCode().
Member Data Documentation
_axisNumber
int DriverMicos_Pollux::_axisNumber mutable protected
Axis number.
Definition at line 120 of file DriverMicos_Pollux.h.
Referenced by GetPos(), InitActuator(), Move(), MoveAbs(), OperationComplete(), SendAddressCode(), and Stop().
_originOffset
float DriverMicos_Pollux::_originOffset mutable protected
Origin offset value.
Definition at line 118 of file DriverMicos_Pollux.h.
Referenced by DriverMicos_Pollux(), DriverMicos_Pollux(), GetPos(), InitActuator(), MoveAbs(), and operator=().
BUFFER_SIZE
const int DriverMicos_Pollux::BUFFER_SIZE = 32 static protected
Serial buffer size.
Definition at line 104 of file DriverMicos_Pollux.h.
Referenced by GetPos(), InitActuator(), Move(), MoveAbs(), OperationComplete(), and Stop().
MAX_DEVICES
const int DriverMicos_Pollux::MAX_DEVICES = 16 static protected
Maximum device count.
Definition at line 106 of file DriverMicos_Pollux.h.
Referenced by SendAddressCode().
MICOS_POLLUX_FEATURE
const DriverFeature DriverMicos_Pollux::MICOS_POLLUX_FEATURE static protected
Initial value:
=
  { "deg","deg",1000.,1000.,CLOSED_LOOP,NULL }
Micos Pollux features.
Definition at line 33 of file DriverMicos_Pollux.h.
Referenced by ConvertUnit(), and GetActuatorFeature().
NB_ITEM_DRV_SETTING
const int DriverMicos_Pollux::NB_ITEM_DRV_SETTING = 1 static protected
Number of driver settings items.
Definition at line 110 of file DriverMicos_Pollux.h.
NB_ITEM_INIT_SETTING
const int DriverMicos_Pollux::NB_ITEM_INIT_SETTING = 1 static protected
Number of init settings items.
Definition at line 108 of file DriverMicos_Pollux.h.
Referenced by InitActuator().
The documentation for this class was generated from the following files:
DriverMicos_Pollux.h
DriverMicos_Pollux.cpp