OpticsBenchUI: AnalysisThread Class Reference
AnalysisThread Class Reference
#include <AnalysisThread.h>
Signals
void analysisStarted (int record)
void analysisOutput (int record, const QString &output)
void analysisFinished (int record, bool success, const QString &output)
void showWarning (QString message)
Public Member Functions
AnalysisThread (QObject *parent=nullptr)
Construct the analysis thread.
~AnalysisThread () override
Destructor.
void setTasks (const QVector< AnalysisTask > &tasks)
void stop ()
Request the thread to stop.
Protected Member Functions
void run () override
Thread entry point.
Detailed Description
Executes external analysis commands in a worker thread.
Each task is run using QProcess with the specified code path and argument string.
Definition at line 44 of file AnalysisThread.h.
Constructor & Destructor Documentation
AnalysisThread()
AnalysisThread::AnalysisThread (QObject * parent = nullptr) explicit
Construct the analysis thread.
Definition at line 25 of file AnalysisThread.cpp.
~AnalysisThread()
AnalysisThread::~AnalysisThread () override
Destructor.
Definition at line 31 of file AnalysisThread.cpp.
References QLOG_DEBUG, and stop().
Member Function Documentation
analysisFinished
void AnalysisThread::analysisFinished (int record, bool success, const QString & output) signal
Emitted when a task finishes.
Parameters
record Task record index.
success True if the command exited normally with code 0.
output Combined stdout/stderr output.
Referenced by run().
analysisOutput
void AnalysisThread::analysisOutput (int record, const QString & output) signal
Emitted when a task produces output.
Parameters
record Task record index.
output Output chunk from stdout/stderr.
Referenced by run().
analysisStarted
void AnalysisThread::analysisStarted (int record) signal
Emitted when a task starts.
Parameters
record Task record index.
Referenced by run().
run()
void AnalysisThread::run () override protected
Thread entry point.
Definition at line 55 of file AnalysisThread.cpp.
References analysisFinished(), analysisOutput(), analysisStarted(), QLOG_DEBUG, QLOG_INFO, and showWarning().
setTasks()
void AnalysisThread::setTasks (const QVector< AnalysisTask > & tasks)
Set the task list to run.
Parameters
tasks Analysis tasks to execute.
Definition at line 38 of file AnalysisThread.cpp.
Referenced by AnalysisWidget::run().
showWarning
void AnalysisThread::showWarning (QString message) signal
Emit warnings to the UI.
Parameters
message Warning message.
Referenced by run().
stop()
void AnalysisThread::stop ()
Request the thread to stop.
Definition at line 42 of file AnalysisThread.cpp.
Referenced by AnalysisWidget::stop(), ~AnalysisThread(), and AnalysisWidget::~AnalysisWidget().
The documentation for this class was generated from the following files:
AnalysisThread.h
AnalysisThread.cpp