OpticsBenchUI: DriverPI_C862 Class Reference
DriverPI_C862 Class Reference
Hardware » Motors
#include <DriverPI_C862.h>
Public Member Functions
DriverPI_C862 ()
Default constructor.
DriverPI_C862 (ACCom *commChannel)
DriverPI_C862 (const DriverPI_C862 &actuatorDrvPI_C862, ACCom *commChannel)
virtual ~DriverPI_C862 ()
Destructor.
DriverPI_C862 (const DriverPI_C862 &actuatorDrvPI_C862)
virtual DriverPI_C862 & operator= (const DriverPI_C862 &actuatorDrvPI_C862)
virtual int Init (string &rstateData) const
Initialize the driver.
virtual int InitActuator (string actuatorSetting, float position) const
Initialize the actuator with settings and an optional position.
virtual int GetPos (string actuatorSetting, float &position) const
Read the current actuator position.
virtual int Move (string actuatorSetting, float nbSteps, int unit) const
Perform a relative motion.
virtual int MoveAbs (string actuatorSetting, float absPos, int unit) const
Perform an absolute motion.
virtual int Stop (string actuatorSetting) const
Stop the actuator.
virtual int OperationComplete (string &rstateData, string actuatorSetting, DriverDefinition::ADLimitSwitch &rlimitSwitch) const
Check whether the last operation has completed.
virtual int GetActuatorFeature (DriverDefinition::DriverFeature &ractuatorFeature) const
Get actuator feature metadata.
virtual int ConvertUnit (int unit, float valueToConvert, float &rconvertedValue, float &rrange) const
Convert between default and custom units.
Public Member Functions inherited from Driver
Driver ()
Constructor.
Driver (ACCom *commChannel)
Constructor with communication channel.
Driver (const Driver &actuatorDrv, ACCom *commChannel)
Constructor with driver reference and communication channel.
Driver (const Driver &actuatorDrv)
Copy Constructor.
virtual ~Driver ()
Destructor.
Driver & operator= (Driver &actuatorDrv)
Affectation Operator.
virtual int GetLastError (DriverDefinition::ADErrorCode &lastError)
code of the last error
virtual int SendGeneralCommand (char *buffer, string &rply) const
virtual int Exit (string actuatorSetting)
Protected Member Functions
int SendAddressCode () const
Send device address code.
Protected Member Functions inherited from Driver
void Tokenize (const string &str, vector< string > &tokens, const string &delimiters=" ") const
void ReportWarning (DriverDefinition::ADErrorCode code, const QString &message) const
void ReportError (DriverDefinition::ADErrorCode code, const QString &message) const
void ReportSettingError (const QString &message) const
void ReportCommError (const QString &message) const
void ReportRangeError (const QString &message) const
Protected Attributes
float _originOffset
Origin offset value.
Protected Attributes inherited from Driver
DriverDefinition::ADErrorCode _lastError
Code of the last error.
string _setting
Driver setting string.
ACCom * _pcommChannel
Actuator communication channel.
Static Protected Attributes
static const int BUFFER_SIZE = 32
Serial buffer size.
static const int MAX_DEVICES = 16
Maximum device count.
static const int NB_ITEM_INIT_SETTING = 6
Number of init settings items.
static const int NB_ITEM_DRV_SETTING = 1
Number of driver settings items.
static const DriverDefinition::DriverFeature PI_C862_FEATURE
Translation stage features.
Additional Inherited Members
Static Public Member Functions inherited from Driver
static Driver * Create (string driverType, string setting, ACCom *channel)
Driver type to instantiate and settings.
static Driver * Create (const Driver *prefActuatorDrv, ACCom *prefChannel)
pointer on the reference driver and channel
Static Public Attributes inherited from Driver
static const string PI_C862 = "PI_C862"
Identifier for the PIezo driver.
static const string NEWFOCUS_8750_OL = "NewFocus_8750_Ol"
Identifier for the Ethernet-PIcomotor driver.
static const string NEWFOCUS_8750_CL = "NewFocus_8750_Cl"
Identifier for the Ethernet-Closed-Loop-PIcomotor driver.
static const string PI_C509 = "PI_C509"
Identifier for the Translation Stage driver.
static const string MICOS_POLLUX = "Micos_Pollux"
Identifier for the Rotor driver.
static const string NEWPORT_NSC200 = "NewPort_NSC200"
Identifier for the NSA driver.
static const string STANDA_USMC = "Standa_uSMC"
Identifier for the STANDA (old) driver.
static const string STANDA_USMC2 = "Standa_uSMC2"
Identifier for the STANDA driver.
static const string NULL_DRV_ID
Identifier for the NULL driver.
static const string PI_E725 = "PI_E725"
Identifier for the PI_E725 driver.
static const string NEWPORT_AGUC2 = "NewPort_AGUC2"
Identifier for the NEWPORT_AGUC2.
Detailed Description
PI C-862 actuator driver implementation.
Definition at line 31 of file DriverPI_C862.h.
Constructor & Destructor Documentation
DriverPI_C862() [1/4]
DriverPI_C862::DriverPI_C862 () inline
Default constructor.
Definition at line 36 of file DriverPI_C862.h.
Referenced by DriverPI_C862(), DriverPI_C862(), and operator=().
DriverPI_C862() [2/4]
DriverPI_C862::DriverPI_C862 (ACCom * commChannel) inline
Construct with a communication channel.
Parameters
commChannel Communication channel instance.
Definition at line 40 of file DriverPI_C862.h.
References Driver::Driver().
DriverPI_C862() [3/4]
DriverPI_C862::DriverPI_C862 (const DriverPI_C862 & actuatorDrvPI_C862, ACCom * commChannel) inline
Copy-construct with a new communication channel.
Parameters
actuatorDrvPI_C862 Reference driver to copy.
commChannel Communication channel instance.
Definition at line 46 of file DriverPI_C862.h.
References _originOffset, Driver::Driver(), and DriverPI_C862().
~DriverPI_C862()
virtual DriverPI_C862::~DriverPI_C862 () inline virtual
Destructor.
Definition at line 53 of file DriverPI_C862.h.
DriverPI_C862() [4/4]
DriverPI_C862::DriverPI_C862 (const DriverPI_C862 & actuatorDrvPI_C862) inline
Copy constructor.
Parameters
actuatorDrvPI_C862 Reference driver to copy.
Definition at line 57 of file DriverPI_C862.h.
References _originOffset, Driver::Driver(), and DriverPI_C862().
Member Function Documentation
ConvertUnit()
int DriverPI_C862::ConvertUnit (int unit, float valueToConvert, float & rconvertedValue, float & rrange) const virtual
Convert between default and custom units.
Operation : ConvertUnit Performs the following conversion :
from custom unit to default unit
no conversion
from default unit to custom converts a value into default motion unit if it is expressed in custom one and gives the range associated to the unit
Parameters
unit motion unit
valueToConvert value to be converted
rconvertedValue conversion result
rrange output range for the selected unit
Implements Driver.
Definition at line 571 of file DriverPI_C862.cpp.
References PI_C862_FEATURE.
Referenced by Move(), and MoveAbs().
GetActuatorFeature()
int DriverPI_C862::GetActuatorFeature (DriverDefinition::DriverFeature & ractuatorFeature) const virtual
Get actuator feature metadata.
Implements Driver.
Definition at line 492 of file DriverPI_C862.cpp.
References PI_C862_FEATURE.
GetPos()
int DriverPI_C862::GetPos (string actuatorSetting, float & position) const virtual
Read the current actuator position.
Implements Driver.
Definition at line 192 of file DriverPI_C862.cpp.
References _originOffset, Driver::_pcommChannel, BUFFER_SIZE, Driver::ReportCommError(), and SendAddressCode().
Referenced by InitActuator().
Init()
int DriverPI_C862::Init (string & rstateData) const virtual
Initialize the driver.
Implements Driver.
Definition at line 35 of file DriverPI_C862.cpp.
References OperationComplete().
InitActuator()
int DriverPI_C862::InitActuator (string actuatorSetting, float position) const virtual
Initialize the actuator with settings and an optional position.
Implements Driver.
Definition at line 63 of file DriverPI_C862.cpp.
References _originOffset, Driver::_pcommChannel, BUFFER_SIZE, GetPos(), NB_ITEM_INIT_SETTING, Driver::ReportCommError(), Driver::ReportSettingError(), and SendAddressCode().
Move()
int DriverPI_C862::Move (string actuatorSetting, float nbSteps, int unit) const virtual
Perform a relative motion.
Implements Driver.
Definition at line 256 of file DriverPI_C862.cpp.
References Driver::_lastError, Driver::_pcommChannel, BUFFER_SIZE, ConvertUnit(), Driver::ReportCommError(), and SendAddressCode().
MoveAbs()
int DriverPI_C862::MoveAbs (string actuatorSetting, float absPos, int unit) const virtual
Perform an absolute motion.
Implements Driver.
Definition at line 302 of file DriverPI_C862.cpp.
References _originOffset, Driver::_pcommChannel, BUFFER_SIZE, ConvertUnit(), Driver::ReportCommError(), and SendAddressCode().
OperationComplete()
int DriverPI_C862::OperationComplete (string & rstateData, string actuatorSetting, DriverDefinition::ADLimitSwitch & rlimitSwitch) const virtual
Check whether the last operation has completed.
Implements Driver.
Definition at line 391 of file DriverPI_C862.cpp.
References Driver::_pcommChannel, BUFFER_SIZE, Driver::ReportCommError(), and SendAddressCode().
Referenced by Init().
operator=()
virtual DriverPI_C862 & DriverPI_C862::operator= (const DriverPI_C862 & actuatorDrvPI_C862) inline virtual
Assignment operator.
Parameters
actuatorDrvPI_C862 Reference driver to copy.
Definition at line 65 of file DriverPI_C862.h.
References _originOffset, Driver::_pcommChannel, and DriverPI_C862().
SendAddressCode()
int DriverPI_C862::SendAddressCode () const protected
Send device address code.
Definition at line 510 of file DriverPI_C862.cpp.
References Driver::_pcommChannel, Driver::_setting, BUFFER_SIZE, MAX_DEVICES, NB_ITEM_DRV_SETTING, Driver::ReportCommError(), Driver::ReportRangeError(), and Driver::ReportSettingError().
Referenced by GetPos(), InitActuator(), Move(), MoveAbs(), OperationComplete(), and Stop().
Stop()
int DriverPI_C862::Stop (string actuatorSetting) const virtual
Stop the actuator.
Implements Driver.
Definition at line 346 of file DriverPI_C862.cpp.
References Driver::_pcommChannel, BUFFER_SIZE, Driver::ReportCommError(), and SendAddressCode().
Member Data Documentation
_originOffset
float DriverPI_C862::_originOffset mutable protected
Origin offset value.
Definition at line 118 of file DriverPI_C862.h.
Referenced by DriverPI_C862(), DriverPI_C862(), GetPos(), InitActuator(), MoveAbs(), and operator=().
BUFFER_SIZE
const int DriverPI_C862::BUFFER_SIZE = 32 static protected
Serial buffer size.
Definition at line 104 of file DriverPI_C862.h.
Referenced by GetPos(), InitActuator(), Move(), MoveAbs(), OperationComplete(), SendAddressCode(), and Stop().
MAX_DEVICES
const int DriverPI_C862::MAX_DEVICES = 16 static protected
Maximum device count.
Definition at line 106 of file DriverPI_C862.h.
Referenced by SendAddressCode().
NB_ITEM_DRV_SETTING
const int DriverPI_C862::NB_ITEM_DRV_SETTING = 1 static protected
Number of driver settings items.
Definition at line 110 of file DriverPI_C862.h.
Referenced by SendAddressCode().
NB_ITEM_INIT_SETTING
const int DriverPI_C862::NB_ITEM_INIT_SETTING = 6 static protected
Number of init settings items.
Definition at line 108 of file DriverPI_C862.h.
Referenced by InitActuator().
PI_C862_FEATURE
const DriverFeature DriverPI_C862::PI_C862_FEATURE static protected
Initial value:
=
      { "steps","mm",3.0e6,25.,CLOSED_LOOP,NULL }
Translation stage features.
Definition at line 29 of file DriverPI_C862.h.
Referenced by ConvertUnit(), and GetActuatorFeature().
The documentation for this class was generated from the following files:
DriverPI_C862.h
DriverPI_C862.cpp