OpticsBenchUI: DriverNewPort_NSC200 Class Reference
DriverNewPort_NSC200 Class Reference
Hardware » Motors
#include <DriverNewPort_NSC200.h>
Public Member Functions
DriverNewPort_NSC200 ()
Default constructor.
DriverNewPort_NSC200 (ACCom *commChannel)
DriverNewPort_NSC200 (const DriverNewPort_NSC200 &actuatorDrvNewPort_NSC200, ACCom *commChannel)
virtual ~DriverNewPort_NSC200 ()
Destructor.
DriverNewPort_NSC200 (const DriverNewPort_NSC200 &actuatorDrvNewPort_NSC200)
virtual DriverNewPort_NSC200 & operator= (const DriverNewPort_NSC200 &actuatorDrvNewPort_NSC200)
virtual int Init (string &rstateData) const
Initialize the driver.
virtual int InitActuator (string actuatorSetting, float position) const
Initialize the actuator with settings and an optional position.
virtual int GetPos (string actuatorSetting, float &position) const
Read the current actuator position.
virtual int Move (string actuatorSetting, float nbSteps, int unit) const
Perform a relative motion.
virtual int MoveAbs (string actuatorSetting, float absPos, int unit) const
Perform an absolute motion.
virtual int Stop (string actuatorSetting) const
Stop the actuator.
virtual int OperationComplete (string &rstateData, string actuatorSetting, DriverDefinition::ADLimitSwitch &rlimitSwitch) const
Check whether the last operation has completed.
virtual int GetActuatorFeature (DriverDefinition::DriverFeature &ractuatorFeature) const
Get actuator feature metadata.
virtual int ConvertUnit (int unit, float valueToConvert, float &rconvertedValue, float &rrange) const
Convert between default and custom units.
virtual int SelectedSwitchBoxChannel (string actuatorSetting) const
Public Member Functions inherited from Driver
Driver ()
Constructor.
Driver (ACCom *commChannel)
Constructor with communication channel.
Driver (const Driver &actuatorDrv, ACCom *commChannel)
Constructor with driver reference and communication channel.
Driver (const Driver &actuatorDrv)
Copy Constructor.
virtual ~Driver ()
Destructor.
Driver & operator= (Driver &actuatorDrv)
Affectation Operator.
virtual int GetLastError (DriverDefinition::ADErrorCode &lastError)
code of the last error
virtual int SendGeneralCommand (char *buffer, string &rply) const
virtual int Exit (string actuatorSetting)
Protected Attributes
float _originOffset
Origin offset value.
int _axisNumber
Axis number.
int _delay
Communication delay.
float _vel
Velocity value.
int _channel
Switchbox channel.
Protected Attributes inherited from Driver
DriverDefinition::ADErrorCode _lastError
Code of the last error.
string _setting
Driver setting string.
ACCom * _pcommChannel
Actuator communication channel.
Static Protected Attributes
static const int BUFFER_SIZE = 32
Serial buffer size.
static const int MAX_DEVICES = 16
Maximum device count.
static const float MAX_VEL = 100000
Maximum velocity.
static const int NB_ITEM_INIT_SETTING = 2
Number of init settings items.
static const int NB_ITEM_DRV_SETTING = 2
Number of driver settings items.
static const int MAX_TRIES = 10
Maximum retry count.
static const DriverDefinition::DriverFeature NEWPORT_NSC200_FEATURE
Newport NSC200 driver features.
Additional Inherited Members
Static Public Member Functions inherited from Driver
static Driver * Create (string driverType, string setting, ACCom *channel)
Driver type to instantiate and settings.
static Driver * Create (const Driver *prefActuatorDrv, ACCom *prefChannel)
pointer on the reference driver and channel
Static Public Attributes inherited from Driver
static const string PI_C862 = "PI_C862"
Identifier for the PIezo driver.
static const string NEWFOCUS_8750_OL = "NewFocus_8750_Ol"
Identifier for the Ethernet-PIcomotor driver.
static const string NEWFOCUS_8750_CL = "NewFocus_8750_Cl"
Identifier for the Ethernet-Closed-Loop-PIcomotor driver.
static const string PI_C509 = "PI_C509"
Identifier for the Translation Stage driver.
static const string MICOS_POLLUX = "Micos_Pollux"
Identifier for the Rotor driver.
static const string NEWPORT_NSC200 = "NewPort_NSC200"
Identifier for the NSA driver.
static const string STANDA_USMC = "Standa_uSMC"
Identifier for the STANDA (old) driver.
static const string STANDA_USMC2 = "Standa_uSMC2"
Identifier for the STANDA driver.
static const string NULL_DRV_ID
Identifier for the NULL driver.
static const string PI_E725 = "PI_E725"
Identifier for the PI_E725 driver.
static const string NEWPORT_AGUC2 = "NewPort_AGUC2"
Identifier for the NEWPORT_AGUC2.
Protected Member Functions inherited from Driver
void Tokenize (const string &str, vector< string > &tokens, const string &delimiters=" ") const
void ReportWarning (DriverDefinition::ADErrorCode code, const QString &message) const
void ReportError (DriverDefinition::ADErrorCode code, const QString &message) const
void ReportSettingError (const QString &message) const
void ReportCommError (const QString &message) const
void ReportRangeError (const QString &message) const
Detailed Description
Newport NSC200 actuator driver implementation.
Definition at line 31 of file DriverNewPort_NSC200.h.
Constructor & Destructor Documentation
DriverNewPort_NSC200() [1/4]
DriverNewPort_NSC200::DriverNewPort_NSC200 () inline
Default constructor.
Definition at line 36 of file DriverNewPort_NSC200.h.
Referenced by DriverNewPort_NSC200(), DriverNewPort_NSC200(), and operator=().
DriverNewPort_NSC200() [2/4]
DriverNewPort_NSC200::DriverNewPort_NSC200 (ACCom * commChannel) inline
Construct with a communication channel.
Parameters
commChannel Communication channel instance.
Definition at line 40 of file DriverNewPort_NSC200.h.
References Driver::Driver().
DriverNewPort_NSC200() [3/4]
DriverNewPort_NSC200::DriverNewPort_NSC200 (const DriverNewPort_NSC200 & actuatorDrvNewPort_NSC200, ACCom * commChannel) inline
Copy-construct with a new communication channel.
Parameters
actuatorDrvNewPort_NSC200 Reference driver to copy.
commChannel Communication channel instance.
Definition at line 46 of file DriverNewPort_NSC200.h.
References _originOffset, Driver::Driver(), and DriverNewPort_NSC200().
~DriverNewPort_NSC200()
virtual DriverNewPort_NSC200::~DriverNewPort_NSC200 () inline virtual
Destructor.
Definition at line 53 of file DriverNewPort_NSC200.h.
DriverNewPort_NSC200() [4/4]
DriverNewPort_NSC200::DriverNewPort_NSC200 (const DriverNewPort_NSC200 & actuatorDrvNewPort_NSC200) inline
Copy constructor.
Parameters
actuatorDrvNewPort_NSC200 Reference driver to copy.
Definition at line 57 of file DriverNewPort_NSC200.h.
References _originOffset, Driver::Driver(), and DriverNewPort_NSC200().
Member Function Documentation
ConvertUnit()
int DriverNewPort_NSC200::ConvertUnit (int unit, float valueToConvert, float & rconvertedValue, float & rrange) const virtual
Convert between default and custom units.
Operation : ConvertUnit Performs the following conversion :
from custom unit to default unit
no conversion
from default unit to custom converts a value into default motion unit if it is expressed in custom one and gives the range associated to the unit
Parameters
unit motion unit
valueToConvert value to be converted
rconvertedValue conversion result
rrange output range for the selected unit
Implements Driver.
Definition at line 562 of file DriverNewPort_NSC200.cpp.
References NEWPORT_NSC200_FEATURE.
Referenced by Move(), and MoveAbs().
GetActuatorFeature()
int DriverNewPort_NSC200::GetActuatorFeature (DriverDefinition::DriverFeature & ractuatorFeature) const virtual
Get actuator feature metadata.
Implements Driver.
Definition at line 532 of file DriverNewPort_NSC200.cpp.
References NEWPORT_NSC200_FEATURE.
GetPos()
int DriverNewPort_NSC200::GetPos (string actuatorSetting, float & position) const virtual
Read the current actuator position.
Implements Driver.
Definition at line 166 of file DriverNewPort_NSC200.cpp.
References _axisNumber, _channel, _delay, Driver::_pcommChannel, and BUFFER_SIZE.
Init()
int DriverNewPort_NSC200::Init (string & rstateData) const virtual
Initialize the driver.
Implements Driver.
Definition at line 39 of file DriverNewPort_NSC200.cpp.
References _axisNumber, _delay, Driver::_pcommChannel, Driver::_setting, BUFFER_SIZE, MAX_DEVICES, MAX_TRIES, NB_ITEM_DRV_SETTING, Driver::ReportRangeError(), and Driver::ReportSettingError().
InitActuator()
int DriverNewPort_NSC200::InitActuator (string actuatorSetting, float position) const virtual
Initialize the actuator with settings and an optional position.
Implements Driver.
Definition at line 108 of file DriverNewPort_NSC200.cpp.
References _axisNumber, _delay, Driver::_pcommChannel, _vel, BUFFER_SIZE, MAX_VEL, Driver::ReportCommError(), Driver::ReportRangeError(), Driver::ReportWarning(), and SelectedSwitchBoxChannel().
Move()
int DriverNewPort_NSC200::Move (string actuatorSetting, float nbSteps, int unit) const virtual
Perform a relative motion.
Implements Driver.
Definition at line 218 of file DriverNewPort_NSC200.cpp.
References _axisNumber, _delay, Driver::_lastError, Driver::_pcommChannel, BUFFER_SIZE, ConvertUnit(), and SelectedSwitchBoxChannel().
MoveAbs()
int DriverNewPort_NSC200::MoveAbs (string actuatorSetting, float absPos, int unit) const virtual
Perform an absolute motion.
Implements Driver.
Definition at line 266 of file DriverNewPort_NSC200.cpp.
References _axisNumber, _delay, Driver::_pcommChannel, BUFFER_SIZE, ConvertUnit(), and SelectedSwitchBoxChannel().
OperationComplete()
int DriverNewPort_NSC200::OperationComplete (string & rstateData, string actuatorSetting, DriverDefinition::ADLimitSwitch & rlimitSwitch) const virtual
Check whether the last operation has completed.
Implements Driver.
Definition at line 350 of file DriverNewPort_NSC200.cpp.
References _axisNumber, _channel, _delay, Driver::_pcommChannel, Driver::_setting, _vel, BUFFER_SIZE, NB_ITEM_DRV_SETTING, NB_ITEM_INIT_SETTING, Driver::ReportRangeError(), and Driver::ReportSettingError().
operator=()
virtual DriverNewPort_NSC200 & DriverNewPort_NSC200::operator= (const DriverNewPort_NSC200 & actuatorDrvNewPort_NSC200) inline virtual
Assignment operator.
Parameters
actuatorDrvNewPort_NSC200 Reference driver to copy.
Definition at line 65 of file DriverNewPort_NSC200.h.
References _originOffset, Driver::_pcommChannel, and DriverNewPort_NSC200().
SelectedSwitchBoxChannel()
int DriverNewPort_NSC200::SelectedSwitchBoxChannel (string actuatorSetting) const virtual
Select a switchbox channel from the actuator settings.
Parameters
actuatorSetting Settings string.
Definition at line 595 of file DriverNewPort_NSC200.cpp.
References _axisNumber, _channel, _delay, Driver::_lastError, Driver::_pcommChannel, Driver::_setting, _vel, BUFFER_SIZE, NB_ITEM_DRV_SETTING, NB_ITEM_INIT_SETTING, and Driver::ReportSettingError().
Referenced by InitActuator(), Move(), MoveAbs(), and Stop().
Stop()
int DriverNewPort_NSC200::Stop (string actuatorSetting) const virtual
Stop the actuator.
Implements Driver.
Definition at line 312 of file DriverNewPort_NSC200.cpp.
References _axisNumber, _delay, Driver::_pcommChannel, BUFFER_SIZE, and SelectedSwitchBoxChannel().
Member Data Documentation
_axisNumber
int DriverNewPort_NSC200::_axisNumber mutable protected
Axis number.
Definition at line 127 of file DriverNewPort_NSC200.h.
Referenced by GetPos(), Init(), InitActuator(), Move(), MoveAbs(), OperationComplete(), SelectedSwitchBoxChannel(), and Stop().
_channel
int DriverNewPort_NSC200::_channel mutable protected
Switchbox channel.
Definition at line 133 of file DriverNewPort_NSC200.h.
Referenced by GetPos(), OperationComplete(), and SelectedSwitchBoxChannel().
_delay
int DriverNewPort_NSC200::_delay mutable protected
Communication delay.
Definition at line 129 of file DriverNewPort_NSC200.h.
Referenced by GetPos(), Init(), InitActuator(), Move(), MoveAbs(), OperationComplete(), SelectedSwitchBoxChannel(), and Stop().
_originOffset
float DriverNewPort_NSC200::_originOffset mutable protected
Origin offset value.
Definition at line 125 of file DriverNewPort_NSC200.h.
Referenced by DriverNewPort_NSC200(), DriverNewPort_NSC200(), and operator=().
_vel
float DriverNewPort_NSC200::_vel mutable protected
Velocity value.
Definition at line 131 of file DriverNewPort_NSC200.h.
Referenced by InitActuator(), OperationComplete(), and SelectedSwitchBoxChannel().
BUFFER_SIZE
const int DriverNewPort_NSC200::BUFFER_SIZE = 32 static protected
Serial buffer size.
Definition at line 108 of file DriverNewPort_NSC200.h.
Referenced by GetPos(), Init(), InitActuator(), Move(), MoveAbs(), OperationComplete(), SelectedSwitchBoxChannel(), and Stop().
MAX_DEVICES
const int DriverNewPort_NSC200::MAX_DEVICES = 16 static protected
Maximum device count.
Definition at line 110 of file DriverNewPort_NSC200.h.
Referenced by Init().
MAX_TRIES
const int DriverNewPort_NSC200::MAX_TRIES = 10 static protected
Maximum retry count.
Definition at line 118 of file DriverNewPort_NSC200.h.
Referenced by Init().
MAX_VEL
const float DriverNewPort_NSC200::MAX_VEL = 100000 static protected
Maximum velocity.
Definition at line 112 of file DriverNewPort_NSC200.h.
Referenced by InitActuator().
NB_ITEM_DRV_SETTING
const int DriverNewPort_NSC200::NB_ITEM_DRV_SETTING = 2 static protected
Number of driver settings items.
Definition at line 116 of file DriverNewPort_NSC200.h.
Referenced by Init(), OperationComplete(), and SelectedSwitchBoxChannel().
NB_ITEM_INIT_SETTING
const int DriverNewPort_NSC200::NB_ITEM_INIT_SETTING = 2 static protected
Number of init settings items.
Definition at line 114 of file DriverNewPort_NSC200.h.
Referenced by OperationComplete(), and SelectedSwitchBoxChannel().
NEWPORT_NSC200_FEATURE
const DriverFeature DriverNewPort_NSC200::NEWPORT_NSC200_FEATURE static protected
Initial value:
=
  { "steps","mm",110866,11.,CLOSED_LOOP,NULL }
Newport NSC200 driver features.
Definition at line 33 of file DriverNewPort_NSC200.h.
Referenced by ConvertUnit(), and GetActuatorFeature().
The documentation for this class was generated from the following files:
DriverNewPort_NSC200.h
DriverNewPort_NSC200.cpp