OpticsBenchUI: QsLogging::Logger Class Reference
QsLogging::Logger Class Reference
Logger singleton and configuration.
#include <QsLog.h>
Classes
class Helper
Public Member Functions
void addDestination (Destination *destination)
Adds a log message destination. Don't add null destinations.
void setLoggingLevel (Level newLevel)
Logging at a level < 'newLevel' will be ignored.
Level loggingLevel () const
The default level is INFO.
Static Public Member Functions
static Logger & instance ()
Return the logger singleton instance.
Detailed Description
Logger singleton and configuration.
Definition at line 54 of file QsLog.h.
Member Function Documentation
addDestination()
void QsLogging::Logger::addDestination (Destination * destination)
Adds a log message destination. Don't add null destinations.
Definition at line 107 of file QsLog.cpp.
References QsLogging::LoggerImpl::destList.
Referenced by main().
instance()
static Logger& QsLogging::Logger::instance () inline static
Return the logger singleton instance.
Definition at line 58 of file QsLog.h.
Referenced by main().
loggingLevel()
Level QsLogging::Logger::loggingLevel () const
The default level is INFO.
Definition at line 118 of file QsLog.cpp.
References QsLogging::LoggerImpl::level.
setLoggingLevel()
void QsLogging::Logger::setLoggingLevel (Level newLevel)
Logging at a level < 'newLevel' will be ignored.
Definition at line 113 of file QsLog.cpp.
References QsLogging::LoggerImpl::level.
Referenced by main().
The documentation for this class was generated from the following files:
QsLog.h
QsLog.cpp