OpticsBenchUI: CameraRAPTORNINOX640 Class Reference
CameraRAPTORNINOX640 Class Reference
Hardware » Cameras
#include <CameraRAPTORNINOX640.h>
Public Slots
void setImageSize (const int &_imageWidth, const int &_imageHeight) override
void setFeature (int feature, double value) override
void setMode (int feature, bool value) override
void getProps () override
Query the camera for its properties.
Public Slots inherited from Camera
virtual void setImageSize (const int &_imageWidth, const int &_imageHeight)=0
virtual void setFeature (int feature, double value)=0
virtual void setMode (int feature, bool value)=0
virtual void vflipImage (int state)
virtual void hflipImage (int state)
virtual uchar * reversebytes (uchar *buffer, int buffersize)
virtual ushort * reversebytes (ushort *buffer, int buffersize)
virtual int * reversebytes (int *buffer, int buffersize)
virtual uchar * fliphorizontal (uchar *buffer, int buffersize, int width)
virtual ushort * fliphorizontal (ushort *buffer, int buffersize, int width)
virtual int * fliphorizontal (int *buffer, int buffersize, int width)
virtual void setColorTable (int id)
Signals
void getImage (const QImage &image)
void showWarning (QString message)
void updateFeatures ()
Notify UI to refresh feature values.
void updateMin (int min)
void updateMax (int max)
Signals inherited from Camera
void getImage (const QImage &image)
void showWarning (QString message)
void updateFeatures ()
Notify UI to refresh feature values.
void updateProps ()
Notify UI to refresh property values.
void updateMin (int min)
void updateMax (int max)
void updateAvg (int avg)
Public Member Functions
CameraRAPTORNINOX640 ()
Constructor.
~CameraRAPTORNINOX640 () override
Destructor.
void stop () override
Stop acquisition and release resources.
int findCamera () override
Discover available cameras.
void setCamera (void *_camera, int _id) override
void getFeatures () override
Query and cache camera features.
uchar * getSnapshot () override
Acquire a single 8-bit image.
ushort * getSnapshot16 () override
Acquire a single 16-bit image.
int * getSnapshot32 () override
Acquire a single 32-bit image.
Public Member Functions inherited from Camera
Camera ()
~Camera () override=default
virtual void getProps ()=0
Query and cache camera properties.
Additional Inherited Members
Public Attributes inherited from Camera
QMutex * mutex = nullptr
General mutex for camera operations.
QMutex * snapshotMutex = nullptr
Mutex for snapshot operations.
QMutex * acquireMutex = nullptr
Mutex for acquisition operations.
QWaitCondition * acqstart = nullptr
Wait condition for acquisition start.
QWaitCondition * acqend = nullptr
Wait condition for acquisition end.
bool has_started = false
True if acquisition has started.
bool suspend = false
True if acquisition is suspended.
bool optimizeAcquisition = false
True if acquisition optimization is enabled.
unsigned int width = 0
Current image width.
unsigned int height = 0
Current image height.
unsigned int video_mode = 0
Video mode identifier.
unsigned int pixel_encoding = 0
Pixel encoding identifier.
uchar * buffer = nullptr
8-bit acquisition buffer.
uchar * snapshot = nullptr
8-bit snapshot buffer.
ushort * buffer16 = nullptr
16-bit acquisition buffer.
ushort * snapshot16 = nullptr
16-bit snapshot buffer.
int * buffer32 = nullptr
32-bit acquisition buffer.
int * snapshot32 = nullptr
32-bit snapshot buffer.
int BufSize = 0
Buffer size (bytes or elements, backend-specific).
int snapShotMin = 0
Snapshot minimum.
int snapShotMax = 0
Snapshot maximum.
int snapShotAvg = 0
Snapshot average.
int min = 0
Current minimum.
int max = 0
Current maximum.
int avg = 0
Current average.
int camera_err = 0
Error flag.
int num = 0
Camera total number for camera manager.
int id = 0
Camera position id in list for camera manager.
QVector< void * > cameralist
Available camera list for camera manager.
QVector< QString > vendorlist
Available vendor list for camera manager.
QVector< QString > modelist
Available model list for camera manager.
QString vendor
Current vendor.
QString model
Current model.
bool modeCheckEnabled = false
AUTO/MANUAL mode check enabled.
QVector< QString > featureNameList
Available feature list.
QVector< int > featureIdList
Available feature id list.
QVector< double > featureValueList
Available feature value list.
QVector< double > featureMinList
Available feature min list.
QVector< double > featureMaxList
Available feature max list.
QVector< bool > featureModeAutoList
Available feature mode list.
QVector< bool > featureAutoCapableList
Available feature mode auto capable list.
QVector< double > featureAbsValueList
Available feature abs value list.
QVector< int > featureAbsCapableList
Available feature abs capable list.
QVector< QString > propList
Available properties list.
Protected Attributes inherited from Camera
int vflip = 0
Vertical flip flag.
int hflip = 0
Horizontal flip flag.
double eTimeTotal = 0.0
Total exposure time.
double frequency = 0.0
Acquisition frequency.
QVector< QRgb > hot
Hot color table.
QVector< QRgb > gray
Gray color table.
QVector< QRgb > * table = nullptr
Active color table pointer.
QImage * image = nullptr
Image object for display.
Detailed Description
Raptor Ninox 640 camera implementation.
Definition at line 30 of file CameraRAPTORNINOX640.h.
Constructor & Destructor Documentation
CameraRAPTORNINOX640()
CameraRAPTORNINOX640::CameraRAPTORNINOX640 ()
Constructor.
Definition at line 63 of file CameraRAPTORNINOX640.cpp.
References Camera::acqend, Camera::acqstart, Camera::acquireMutex, Camera::buffer, Camera::buffer16, Camera::buffer32, Camera::has_started, Camera::hflip, Camera::image, Camera::modeCheckEnabled, Camera::mutex, Camera::snapshot, Camera::snapshot16, Camera::snapshot32, Camera::snapshotMutex, Camera::suspend, and Camera::vflip.
~CameraRAPTORNINOX640()
CameraRAPTORNINOX640::~CameraRAPTORNINOX640 () override
Destructor.
Definition at line 91 of file CameraRAPTORNINOX640.cpp.
References Camera::acqend, Camera::acqstart, Camera::acquireMutex, Camera::mutex, QLOG_DEBUG, Camera::snapshotMutex, and stop().
Member Function Documentation
findCamera()
int CameraRAPTORNINOX640::findCamera () override virtual
Discover available cameras.
Implements Camera.
Definition at line 438 of file CameraRAPTORNINOX640.cpp.
References Camera::cameralist, Camera::modelist, Camera::num, QLOG_INFO, and Camera::vendorlist.
getFeatures()
void CameraRAPTORNINOX640::getFeatures () override virtual
Query and cache camera features.
Implements Camera.
Definition at line 356 of file CameraRAPTORNINOX640.cpp.
References Camera::featureAbsValueList, and updateFeatures().
getImage
void CameraRAPTORNINOX640::getImage (const QImage & image) signal
Emit a new image frame.
Parameters
image The latest frame.
getProps
void CameraRAPTORNINOX640::getProps () override slot
Query the camera for its properties.
Definition at line 376 of file CameraRAPTORNINOX640.cpp.
References Camera::frequency, Camera::propList, QLOG_DEBUG, raptorninox640_gains, raptorninox640_nuc, raptorninox640_props, and Camera::updateProps().
Referenced by setFeature().
getSnapshot()
uchar * CameraRAPTORNINOX640::getSnapshot () override virtual
Acquire a single 8-bit image.
Implements Camera.
Definition at line 239 of file CameraRAPTORNINOX640.cpp.
References Camera::avg, Camera::buffer, Camera::height, Camera::max, Camera::min, Camera::snapshot, Camera::snapShotAvg, Camera::snapShotMax, Camera::snapShotMin, Camera::snapshotMutex, and Camera::width.
getSnapshot16()
ushort * CameraRAPTORNINOX640::getSnapshot16 () override virtual
Acquire a single 16-bit image.
Implements Camera.
Definition at line 250 of file CameraRAPTORNINOX640.cpp.
References Camera::avg, Camera::buffer16, Camera::height, Camera::max, Camera::min, QLOG_DEBUG, Camera::snapshot16, Camera::snapShotAvg, Camera::snapShotMax, Camera::snapShotMin, Camera::snapshotMutex, and Camera::width.
getSnapshot32()
int * CameraRAPTORNINOX640::getSnapshot32 () override virtual
Acquire a single 32-bit image.
Implements Camera.
Definition at line 262 of file CameraRAPTORNINOX640.cpp.
References Camera::avg, Camera::buffer32, Camera::height, Camera::max, Camera::min, QLOG_INFO, Camera::snapshot32, Camera::snapShotAvg, Camera::snapShotMax, Camera::snapShotMin, Camera::snapshotMutex, and Camera::width.
setCamera()
void CameraRAPTORNINOX640::setCamera (void * _camera, int _id) override virtual
Attach a camera handle and id.
Parameters
_camera Backend camera pointer.
_id Camera index.
Implements Camera.
Definition at line 103 of file CameraRAPTORNINOX640.cpp.
References B14, Camera::camera_err, Camera::featureAbsCapableList, Camera::featureAbsValueList, Camera::featureIdList, Camera::featureMaxList, Camera::featureMinList, Camera::featureModeAutoList, Camera::featureNameList, Camera::featureValueList, Camera::frequency, Camera::model, Camera::pixel_encoding, Camera::propList, QLOG_INFO, raptorninox640_features, raptorninox640_gains, raptorninox640_nuc, raptorninox640_props, and Camera::vendor.
setFeature
void CameraRAPTORNINOX640::setFeature (int feature, double value) override slot
Set a numeric feature value.
Parameters
feature Feature identifier.
value Feature value.
Definition at line 324 of file CameraRAPTORNINOX640.cpp.
References getProps(), QLOG_INFO, and raptorninox640_features.
setImageSize
void CameraRAPTORNINOX640::setImageSize (const int & _imageWidth, const int & _imageHeight) override slot
Set the image size for acquisition.
Parameters
_imageWidth Width in pixels.
_imageHeight Height in pixels.
Definition at line 601 of file CameraRAPTORNINOX640.cpp.
References QLOG_DEBUG.
setMode
void CameraRAPTORNINOX640::setMode (int feature, bool value) override slot
Enable or disable a feature mode.
Parameters
feature Feature identifier.
value True for auto/enable, false for manual/disable.
Definition at line 353 of file CameraRAPTORNINOX640.cpp.
showWarning
void CameraRAPTORNINOX640::showWarning (QString message) signal
Emit warnings to the UI.
Parameters
message Warning message.
stop()
void CameraRAPTORNINOX640::stop () override virtual
Stop acquisition and release resources.
Implements Camera.
Definition at line 273 of file CameraRAPTORNINOX640.cpp.
References Camera::has_started, and Camera::suspend.
Referenced by ~CameraRAPTORNINOX640().
updateFeatures
void CameraRAPTORNINOX640::updateFeatures () signal
Notify UI to refresh feature values.
Referenced by getFeatures().
updateMax
void CameraRAPTORNINOX640::updateMax (int max) signal
Update the max display value.
Parameters
max Maximum pixel value.
updateMin
void CameraRAPTORNINOX640::updateMin (int min) signal
Update the min display value.
Parameters
min Minimum pixel value.
The documentation for this class was generated from the following files:
CameraRAPTORNINOX640.h
CameraRAPTORNINOX640.cpp