OpticsBenchUI: DriverNewFocus_8750_Cl Class Reference
DriverNewFocus_8750_Cl Class Reference
Hardware » Motors
#include <DriverNewFocus_8750_Cl.h>
Public Member Functions
DriverNewFocus_8750_Cl ()
Default constructor.
DriverNewFocus_8750_Cl (ACCom *commChannel)
DriverNewFocus_8750_Cl (const DriverNewFocus_8750_Cl &actuatorDrvNewFocus_8750_Cl, ACCom *commChannel)
virtual ~DriverNewFocus_8750_Cl ()
Destructor.
DriverNewFocus_8750_Cl (const DriverNewFocus_8750_Cl &actuatorDrvNewFocus_8750_Cl)
virtual DriverNewFocus_8750_Cl & operator= (const DriverNewFocus_8750_Cl &actuatorDrvNewFocus_8750_Cl)
virtual int Init (string &rstateData) const
Initialize the driver.
virtual int InitActuator (string actuatorSetting, float position) const
Initialize the actuator with settings and an optional position.
virtual int GetPos (string actuatorSetting, float &position) const
Read the current actuator position.
virtual int Move (string actuatorSetting, float nbSteps, int unit) const
Perform a relative motion.
virtual int MoveAbs (string actuatorSetting, float absPos, int unit) const
Perform an absolute motion.
virtual int Stop (string actuatorSetting) const
Stop the actuator.
virtual int OperationComplete (string &rstateData, string actuatorSetting, DriverDefinition::ADLimitSwitch &rlimitSwitch) const
Check whether the last operation has completed.
virtual int GetActuatorFeature (DriverDefinition::DriverFeature &ractuatorFeature) const
Get actuator feature metadata.
virtual int ConvertUnit (int unit, float valueToConvert, float &rconvertedValue, float &rrange) const
Convert between default and custom units.
Public Member Functions inherited from Driver
Driver ()
Constructor.
Driver (ACCom *commChannel)
Constructor with communication channel.
Driver (const Driver &actuatorDrv, ACCom *commChannel)
Constructor with driver reference and communication channel.
Driver (const Driver &actuatorDrv)
Copy Constructor.
virtual ~Driver ()
Destructor.
Driver & operator= (Driver &actuatorDrv)
Affectation Operator.
virtual int GetLastError (DriverDefinition::ADErrorCode &lastError)
code of the last error
virtual int SendGeneralCommand (char *buffer, string &rply) const
virtual int Exit (string actuatorSetting)
Additional Inherited Members
Static Public Member Functions inherited from Driver
static Driver * Create (string driverType, string setting, ACCom *channel)
Driver type to instantiate and settings.
static Driver * Create (const Driver *prefActuatorDrv, ACCom *prefChannel)
pointer on the reference driver and channel
Static Public Attributes inherited from Driver
static const string PI_C862 = "PI_C862"
Identifier for the PIezo driver.
static const string NEWFOCUS_8750_OL = "NewFocus_8750_Ol"
Identifier for the Ethernet-PIcomotor driver.
static const string NEWFOCUS_8750_CL = "NewFocus_8750_Cl"
Identifier for the Ethernet-Closed-Loop-PIcomotor driver.
static const string PI_C509 = "PI_C509"
Identifier for the Translation Stage driver.
static const string MICOS_POLLUX = "Micos_Pollux"
Identifier for the Rotor driver.
static const string NEWPORT_NSC200 = "NewPort_NSC200"
Identifier for the NSA driver.
static const string STANDA_USMC = "Standa_uSMC"
Identifier for the STANDA (old) driver.
static const string STANDA_USMC2 = "Standa_uSMC2"
Identifier for the STANDA driver.
static const string NULL_DRV_ID
Identifier for the NULL driver.
static const string PI_E725 = "PI_E725"
Identifier for the PI_E725 driver.
static const string NEWPORT_AGUC2 = "NewPort_AGUC2"
Identifier for the NEWPORT_AGUC2.
Protected Member Functions inherited from Driver
void Tokenize (const string &str, vector< string > &tokens, const string &delimiters=" ") const
void ReportWarning (DriverDefinition::ADErrorCode code, const QString &message) const
void ReportError (DriverDefinition::ADErrorCode code, const QString &message) const
void ReportSettingError (const QString &message) const
void ReportCommError (const QString &message) const
void ReportRangeError (const QString &message) const
Protected Attributes inherited from Driver
DriverDefinition::ADErrorCode _lastError
Code of the last error.
string _setting
Driver setting string.
ACCom * _pcommChannel
Actuator communication channel.
Detailed Description
NewFocus 8750 closed-loop Picomotor driver implementation.
Definition at line 30 of file DriverNewFocus_8750_Cl.h.
Constructor & Destructor Documentation
DriverNewFocus_8750_Cl() [1/4]
DriverNewFocus_8750_Cl::DriverNewFocus_8750_Cl () inline
Default constructor.
Definition at line 35 of file DriverNewFocus_8750_Cl.h.
Referenced by DriverNewFocus_8750_Cl(), DriverNewFocus_8750_Cl(), and operator=().
DriverNewFocus_8750_Cl() [2/4]
DriverNewFocus_8750_Cl::DriverNewFocus_8750_Cl (ACCom * commChannel) inline
Construct with a communication channel.
Parameters
commChannel Communication channel instance.
Definition at line 38 of file DriverNewFocus_8750_Cl.h.
References Driver::Driver().
DriverNewFocus_8750_Cl() [3/4]
DriverNewFocus_8750_Cl::DriverNewFocus_8750_Cl (const DriverNewFocus_8750_Cl & actuatorDrvNewFocus_8750_Cl, ACCom * commChannel) inline
Copy-construct with a new communication channel.
Parameters
actuatorDrvNewFocus_8750_Cl Reference driver to copy.
commChannel Communication channel instance.
Definition at line 44 of file DriverNewFocus_8750_Cl.h.
References Driver::Driver(), and DriverNewFocus_8750_Cl().
~DriverNewFocus_8750_Cl()
virtual DriverNewFocus_8750_Cl::~DriverNewFocus_8750_Cl () inline virtual
Destructor.
Definition at line 50 of file DriverNewFocus_8750_Cl.h.
DriverNewFocus_8750_Cl() [4/4]
DriverNewFocus_8750_Cl::DriverNewFocus_8750_Cl (const DriverNewFocus_8750_Cl & actuatorDrvNewFocus_8750_Cl) inline
Copy constructor.
Parameters
actuatorDrvNewFocus_8750_Cl Reference driver to copy.
Definition at line 54 of file DriverNewFocus_8750_Cl.h.
References Driver::Driver(), and DriverNewFocus_8750_Cl().
Member Function Documentation
ConvertUnit()
int DriverNewFocus_8750_Cl::ConvertUnit (int unit, float valueToConvert, float & rconvertedValue, float & rrange) const virtual
Convert between default and custom units.
Operation : ConvertUnit Performs the following conversion :
from custom unit to default unit
no conversion
from default unit to custom converts a value into default motion unit if it is expressed in custom one and gives the range associated to the unit
Parameters
unit motion unit
valueToConvert value to be converted
rconvertedValue conversion result
rrange output range for the selected unit
Implements Driver.
Definition at line 427 of file DriverNewFocus_8750_Cl.cpp.
Referenced by Move(), and MoveAbs().
GetActuatorFeature()
int DriverNewFocus_8750_Cl::GetActuatorFeature (DriverDefinition::DriverFeature & ractuatorFeature) const virtual
Get actuator feature metadata.
Operation : GetActuatorFeature.
Parameters
ractuatorFeature actuator setting
Implements Driver.
Definition at line 365 of file DriverNewFocus_8750_Cl.cpp.
GetPos()
int DriverNewFocus_8750_Cl::GetPos (string actuatorSetting, float & position) const virtual
Read the current actuator position.
Operation : GetPos Returns the position of the actuator whose setting is given in parameter
Parameters
actuatorSetting actuator setting
position Position of the actuator
Implements Driver.
Definition at line 128 of file DriverNewFocus_8750_Cl.cpp.
References Driver::_setting.
Init()
int DriverNewFocus_8750_Cl::Init (string & rstateData) const virtual
Initialize the driver.
Operation : Init Initializes the driver by putting it in online and servocontrol mode to perform remote control
Parameters
rstateData state data of the driver
Implements Driver.
Definition at line 42 of file DriverNewFocus_8750_Cl.cpp.
References Driver::_setting.
InitActuator()
int DriverNewFocus_8750_Cl::InitActuator (string actuatorSetting, float position) const virtual
Initialize the actuator with settings and an optional position.
Operation : InitActuator Initializes the actuator whose setting is given in parameter by setting its velocity
Parameters
actuatorSetting actuator setting
position required position at initialization
Implements Driver.
Definition at line 86 of file DriverNewFocus_8750_Cl.cpp.
References Driver::_setting, and Driver::ReportSettingError().
Move()
int DriverNewFocus_8750_Cl::Move (string actuatorSetting, float nbSteps, int unit) const virtual
Perform a relative motion.
Operation : Move Moves the actuator whose setting is given in parameter on nbSteps
Parameters
actuatorSetting actuator setting
nbSteps number of steps to perform
unit unit used for the motion. 0 = default unit, 1 = custom one
Implements Driver.
Definition at line 168 of file DriverNewFocus_8750_Cl.cpp.
References Driver::_lastError, Driver::_setting, and ConvertUnit().
MoveAbs()
int DriverNewFocus_8750_Cl::MoveAbs (string actuatorSetting, float absPos, int unit) const virtual
Perform an absolute motion.
Operation : MoveAbs Moves the actuator whose setting is given in parameter to the selected position. On the open loop picomotors, this feature is not available.
Parameters
actuatorSetting actuator setting
absPos position to reach
unit unit used for the motion. 0 = default unit, 1 = custom one
Implements Driver.
Definition at line 215 of file DriverNewFocus_8750_Cl.cpp.
References Driver::_setting, and ConvertUnit().
OperationComplete()
int DriverNewFocus_8750_Cl::OperationComplete (string & rstateData, string actuatorSetting, DriverDefinition::ADLimitSwitch & rlimitSwitch) const virtual
Check whether the last operation has completed.
Operation : OperationComplete Checks the completion of a motion : 0 : motion is being performed 1 : motion is performed
Parameters
rstateData state data of the driver
actuatorSetting actuator setting
rlimitSwitch reached limit flag
Implements Driver.
Definition at line 285 of file DriverNewFocus_8750_Cl.cpp.
References Driver::_setting.
operator=()
virtual DriverNewFocus_8750_Cl & DriverNewFocus_8750_Cl::operator= (const DriverNewFocus_8750_Cl & actuatorDrvNewFocus_8750_Cl) inline virtual
Assignment operator.
Parameters
actuatorDrvNewFocus_8750_Cl Reference driver to copy.
Definition at line 61 of file DriverNewFocus_8750_Cl.h.
References Driver::_pcommChannel, and DriverNewFocus_8750_Cl().
Stop()
int DriverNewFocus_8750_Cl::Stop (string actuatorSetting) const virtual
Stop the actuator.
Operation : Stop Stops the motion of the current active picomotor on the driver
Parameters
actuatorSetting actuator setting
Implements Driver.
Definition at line 252 of file DriverNewFocus_8750_Cl.cpp.
References Driver::_setting.
The documentation for this class was generated from the following files:
DriverNewFocus_8750_Cl.h
DriverNewFocus_8750_Cl.cpp