OpticsBenchUI: FileParser Class Reference
FileParser Class Reference
Utilities
#include <FileParser.h>
Public Member Functions
FileParser (QObject *parent=0)
~FileParser ()
Destructor.
void setDir (QString _dir)
void setPrefix (QString _prefix)
void setSuffix (QString _suffix)
void setDel (QString _del)
void setOrder (QString _order)
void setType (QString _type)
void setFormat (QString _format)
void setSep (QString _sep)
void setDelay (QString _delay)
void setNameList (QString _nameList)
QString getDir ()
Return the directory.
QString getPrefix ()
Return the filename prefix.
QString getSuffix ()
Return the filename suffix.
QString getDel ()
Return the delimiter value.
QString getOrder ()
Return the order.
QString getType ()
Return the type.
QString getFormat ()
Return the format string.
QString getSep ()
Return the separator.
QString getDelay ()
Return the delay value.
QString getParsedFileName ()
Return the computed filename.
QVector< QString > getNameList ()
Return the list of filenames.
bool getFileData ()
Load and parse file data into internal structures.
double * getArray ()
Return the parsed data array.
int getArrayHeight ()
Return the parsed array height.
int getArrayWidth ()
Return the parsed array width.
QVector< double > getDataList ()
Return the parsed data as a list.
Detailed Description
Parses data files and extracts arrays and metadata.
Definition at line 31 of file FileParser.h.
Constructor & Destructor Documentation
FileParser()
FileParser::FileParser (QObject * parent = 0)
Constructor.
Parameters
parent Parent object.
Definition at line 20 of file FileParser.cpp.
Member Function Documentation
setDel()
void FileParser::setDel (QString _del)
Set the delimiter value.
Parameters
_del Delimiter string.
Definition at line 54 of file FileParser.cpp.
Referenced by AcquisitionSequence::prepare().
setDelay()
void FileParser::setDelay (QString _delay)
Set the delay value used for sequencing.
Parameters
_delay Delay string.
Definition at line 97 of file FileParser.cpp.
Referenced by AcquisitionSequence::prepare().
setDir()
void FileParser::setDir (QString _dir)
Set the directory containing input files.
Parameters
_dir Directory path.
Definition at line 39 of file FileParser.cpp.
Referenced by AcquisitionSequence::prepare().
setFormat()
void FileParser::setFormat (QString _format)
Set the format string.
Parameters
_format Format string.
Definition at line 81 of file FileParser.cpp.
Referenced by AcquisitionSequence::prepare().
setNameList()
void FileParser::setNameList (QString _nameList)
Set a list of filenames.
Parameters
_nameList Name list string.
Definition at line 103 of file FileParser.cpp.
Referenced by setType().
setOrder()
void FileParser::setOrder (QString _order)
Set the filename ordering scheme.
Parameters
_order Ordering string.
Definition at line 59 of file FileParser.cpp.
Referenced by AcquisitionSequence::prepare().
setPrefix()
void FileParser::setPrefix (QString _prefix)
Set the filename prefix.
Parameters
_prefix Prefix string.
Definition at line 44 of file FileParser.cpp.
Referenced by AcquisitionSequence::prepare().
setSep()
void FileParser::setSep (QString _sep)
Set the separator used in the file.
Parameters
_sep Separator string.
Definition at line 86 of file FileParser.cpp.
Referenced by AcquisitionSequence::prepare().
setSuffix()
void FileParser::setSuffix (QString _suffix)
Set the filename suffix.
Parameters
_suffix Suffix string.
Definition at line 49 of file FileParser.cpp.
Referenced by AcquisitionSequence::prepare().
setType()
void FileParser::setType (QString _type)
Set the file type identifier.
Parameters
_type Type string.
Definition at line 64 of file FileParser.cpp.
References setNameList().
Referenced by AcquisitionSequence::prepare().
The documentation for this class was generated from the following files:
FileParser.h
FileParser.cpp