OpticsBenchUI: DriverStanda_uSMC Class Reference
DriverStanda_uSMC Class Reference
Hardware » Motors
#include <DriverStanda_uSMC.h>
Public Member Functions
DriverStanda_uSMC ()
Default constructor.
DriverStanda_uSMC (ACCom *commChannel)
DriverStanda_uSMC (const DriverStanda_uSMC &driverStanda_uSMC, ACCom *commChannel)
virtual ~DriverStanda_uSMC ()
Destructor.
DriverStanda_uSMC (const DriverStanda_uSMC &driverStanda_uSMC)
virtual DriverStanda_uSMC & operator= (const DriverStanda_uSMC &driverStanda_uSMC)
virtual int Init (string &rstateData) const
Initialize the driver.
virtual int InitActuator (string actuatorSetting, float position) const
Initialize the actuator with settings and an optional position.
virtual int GetPos (string actuatorSetting, float &position) const
Read the current actuator position.
virtual int Move (string actuatorSetting, float nbSteps, int unit) const
Perform a relative motion.
virtual int MoveAbs (string actuatorSetting, float absPos, int unit) const
Perform an absolute motion.
virtual int Stop (string actuatorSetting) const
Stop the actuator.
virtual int OperationComplete (string &rstateData, string actuatorSetting, DriverDefinition::ADLimitSwitch &rlimitSwitch) const
Check whether the last operation has completed.
virtual int GetActuatorFeature (DriverDefinition::DriverFeature &ractuatorFeature) const
Get actuator feature metadata.
virtual int ConvertUnit (int unit, float valueToConvert, float &rconvertedValue, float &rrange) const
Convert between default and custom units.
virtual int Exit (string actuatorSetting)
Public Member Functions inherited from Driver
Driver ()
Constructor.
Driver (ACCom *commChannel)
Constructor with communication channel.
Driver (const Driver &actuatorDrv, ACCom *commChannel)
Constructor with driver reference and communication channel.
Driver (const Driver &actuatorDrv)
Copy Constructor.
virtual ~Driver ()
Destructor.
Driver & operator= (Driver &actuatorDrv)
Affectation Operator.
virtual int GetLastError (DriverDefinition::ADErrorCode &lastError)
code of the last error
virtual int SendGeneralCommand (char *buffer, string &rply) const
Protected Attributes
USMC_Devices _devices
Devices handle.
DWORD _cur_dev
Current device index.
USMC_State _state
Current device state.
USMC_StartParameters _start_params
Start parameters.
USMC_Parameters _params
Device parameters.
USMC_Mode _mode
Device mode.
USMC_EncoderState _enc_state
Encoder state.
float _speed
Current speed value.
int _rotator
Rotator flag/value.
int _divisor
Divisor value.
Protected Attributes inherited from Driver
DriverDefinition::ADErrorCode _lastError
Code of the last error.
string _setting
Driver setting string.
ACCom * _pcommChannel
Actuator communication channel.
Static Protected Attributes
static const int BUFFER_SIZE = 0
Serial buffer size.
static const int MAX_DEVICES = 0
Maximum device count.
static const float MAX_VEL = 0
Maximum velocity.
static const int NB_ITEM_INIT_SETTING = 4
Number of init settings items.
static const int NB_ITEM_DRV_SETTING = 0
Number of driver settings items.
static const int MAX_TRIES = 10
Maximum retry count.
static const int MIN_BYTES_TRANS = 7
Minimum bytes per transfer.
static const DriverDefinition::DriverFeature STANDA_USMC_FEATURE
Standa USMC driver features.
Additional Inherited Members
Static Public Member Functions inherited from Driver
static Driver * Create (string driverType, string setting, ACCom *channel)
Driver type to instantiate and settings.
static Driver * Create (const Driver *prefActuatorDrv, ACCom *prefChannel)
pointer on the reference driver and channel
Static Public Attributes inherited from Driver
static const string PI_C862 = "PI_C862"
Identifier for the PIezo driver.
static const string NEWFOCUS_8750_OL = "NewFocus_8750_Ol"
Identifier for the Ethernet-PIcomotor driver.
static const string NEWFOCUS_8750_CL = "NewFocus_8750_Cl"
Identifier for the Ethernet-Closed-Loop-PIcomotor driver.
static const string PI_C509 = "PI_C509"
Identifier for the Translation Stage driver.
static const string MICOS_POLLUX = "Micos_Pollux"
Identifier for the Rotor driver.
static const string NEWPORT_NSC200 = "NewPort_NSC200"
Identifier for the NSA driver.
static const string STANDA_USMC = "Standa_uSMC"
Identifier for the STANDA (old) driver.
static const string STANDA_USMC2 = "Standa_uSMC2"
Identifier for the STANDA driver.
static const string NULL_DRV_ID
Identifier for the NULL driver.
static const string PI_E725 = "PI_E725"
Identifier for the PI_E725 driver.
static const string NEWPORT_AGUC2 = "NewPort_AGUC2"
Identifier for the NEWPORT_AGUC2.
Protected Member Functions inherited from Driver
void Tokenize (const string &str, vector< string > &tokens, const string &delimiters=" ") const
void ReportWarning (DriverDefinition::ADErrorCode code, const QString &message) const
void ReportError (DriverDefinition::ADErrorCode code, const QString &message) const
void ReportSettingError (const QString &message) const
void ReportCommError (const QString &message) const
void ReportRangeError (const QString &message) const
Detailed Description
Standa uSMC actuator driver implementation.
Definition at line 23 of file DriverStanda_uSMC.h.
Constructor & Destructor Documentation
DriverStanda_uSMC() [1/4]
DriverStanda_uSMC::DriverStanda_uSMC () inline
Default constructor.
Definition at line 28 of file DriverStanda_uSMC.h.
Referenced by DriverStanda_uSMC(), DriverStanda_uSMC(), and operator=().
DriverStanda_uSMC() [2/4]
DriverStanda_uSMC::DriverStanda_uSMC (ACCom * commChannel) inline
Construct with a communication channel.
Parameters
commChannel Communication channel instance.
Definition at line 32 of file DriverStanda_uSMC.h.
References Driver::Driver().
DriverStanda_uSMC() [3/4]
DriverStanda_uSMC::DriverStanda_uSMC (const DriverStanda_uSMC & driverStanda_uSMC, ACCom * commChannel) inline
Copy-construct with a new communication channel.
Parameters
driverStanda_uSMC Reference driver to copy.
commChannel Communication channel instance.
Definition at line 38 of file DriverStanda_uSMC.h.
References Driver::Driver(), and DriverStanda_uSMC().
~DriverStanda_uSMC()
virtual DriverStanda_uSMC::~DriverStanda_uSMC () inline virtual
Destructor.
Definition at line 44 of file DriverStanda_uSMC.h.
DriverStanda_uSMC() [4/4]
DriverStanda_uSMC::DriverStanda_uSMC (const DriverStanda_uSMC & driverStanda_uSMC) inline
Copy constructor.
Parameters
driverStanda_uSMC Reference driver to copy.
Definition at line 48 of file DriverStanda_uSMC.h.
References Driver::Driver(), and DriverStanda_uSMC().
Member Function Documentation
ConvertUnit()
int DriverStanda_uSMC::ConvertUnit (int unit, float valueToConvert, float & rconvertedValue, float & rrange) const virtual
Convert between default and custom units.
Operation : ConvertUnit Performs the following conversion :
from custom unit to default unit
no conversion
from default unit to custom converts a value into default motion unit if it is expressed in custom one and gives the range associated to the unit
Parameters
unit motion unit
valueToConvert value to be converted
rconvertedValue conversion result
rrange output range for the selected unit
Implements Driver.
Definition at line 327 of file DriverStanda_uSMC.cpp.
Exit()
int DriverStanda_uSMC::Exit (string actuatorSetting) virtual
Shutdown hook for the driver.
Parameters
actuatorSetting Settings string.
Reimplemented from Driver.
Definition at line 338 of file DriverStanda_uSMC.cpp.
References _cur_dev, _divisor, _params, _rotator, _speed, _state, GetPos(), NB_ITEM_INIT_SETTING, and Driver::ReportSettingError().
GetActuatorFeature()
int DriverStanda_uSMC::GetActuatorFeature (DriverDefinition::DriverFeature & ractuatorFeature) const virtual
Get actuator feature metadata.
Implements Driver.
Definition at line 297 of file DriverStanda_uSMC.cpp.
References STANDA_USMC_FEATURE.
GetPos()
int DriverStanda_uSMC::GetPos (string actuatorSetting, float & position) const virtual
Read the current actuator position.
Implements Driver.
Definition at line 112 of file DriverStanda_uSMC.cpp.
References _cur_dev, _divisor, _rotator, _speed, _state, NB_ITEM_INIT_SETTING, and Driver::ReportSettingError().
Referenced by Exit(), InitActuator(), Move(), MoveAbs(), and OperationComplete().
Init()
int DriverStanda_uSMC::Init (string & rstateData) const virtual
Initialize the driver.
Implements Driver.
Definition at line 34 of file DriverStanda_uSMC.cpp.
References _devices.
InitActuator()
int DriverStanda_uSMC::InitActuator (string actuatorSetting, float position) const virtual
Initialize the actuator with settings and an optional position.
Implements Driver.
Definition at line 51 of file DriverStanda_uSMC.cpp.
References _cur_dev, _divisor, _mode, _params, _rotator, _speed, GetPos(), NB_ITEM_INIT_SETTING, and Driver::ReportSettingError().
Move()
int DriverStanda_uSMC::Move (string actuatorSetting, float nbSteps, int unit) const virtual
Perform a relative motion.
Implements Driver.
Definition at line 141 of file DriverStanda_uSMC.cpp.
References _cur_dev, _divisor, _rotator, _speed, _start_params, GetPos(), NB_ITEM_INIT_SETTING, and Driver::ReportSettingError().
MoveAbs()
int DriverStanda_uSMC::MoveAbs (string actuatorSetting, float absPos, int unit) const virtual
Perform an absolute motion.
Implements Driver.
Definition at line 182 of file DriverStanda_uSMC.cpp.
References _cur_dev, _divisor, _rotator, _speed, _start_params, GetPos(), NB_ITEM_INIT_SETTING, and Driver::ReportSettingError().
OperationComplete()
int DriverStanda_uSMC::OperationComplete (string & rstateData, string actuatorSetting, DriverDefinition::ADLimitSwitch & rlimitSwitch) const virtual
Check whether the last operation has completed.
Implements Driver.
Definition at line 256 of file DriverStanda_uSMC.cpp.
References _cur_dev, _divisor, _rotator, _speed, _state, GetPos(), NB_ITEM_INIT_SETTING, and Driver::ReportSettingError().
operator=()
virtual DriverStanda_uSMC & DriverStanda_uSMC::operator= (const DriverStanda_uSMC & driverStanda_uSMC) inline virtual
Assignment operator.
Parameters
driverStanda_uSMC Reference driver to copy.
Definition at line 54 of file DriverStanda_uSMC.h.
References Driver::_pcommChannel, and DriverStanda_uSMC().
Stop()
int DriverStanda_uSMC::Stop (string actuatorSetting) const virtual
Stop the actuator.
Implements Driver.
Definition at line 224 of file DriverStanda_uSMC.cpp.
References _cur_dev, _divisor, _rotator, _speed, NB_ITEM_INIT_SETTING, and Driver::ReportSettingError().
Member Data Documentation
_cur_dev
DWORD DriverStanda_uSMC::_cur_dev mutable protected
Current device index.
Definition at line 113 of file DriverStanda_uSMC.h.
Referenced by Exit(), GetPos(), InitActuator(), Move(), MoveAbs(), OperationComplete(), and Stop().
_devices
USMC_Devices DriverStanda_uSMC::_devices mutable protected
Devices handle.
Definition at line 111 of file DriverStanda_uSMC.h.
Referenced by Init().
_divisor
int DriverStanda_uSMC::_divisor mutable protected
Divisor value.
Definition at line 129 of file DriverStanda_uSMC.h.
Referenced by Exit(), GetPos(), InitActuator(), Move(), MoveAbs(), OperationComplete(), and Stop().
_enc_state
USMC_EncoderState DriverStanda_uSMC::_enc_state mutable protected
Encoder state.
Definition at line 123 of file DriverStanda_uSMC.h.
_mode
USMC_Mode DriverStanda_uSMC::_mode mutable protected
Device mode.
Definition at line 121 of file DriverStanda_uSMC.h.
Referenced by InitActuator().
_params
USMC_Parameters DriverStanda_uSMC::_params mutable protected
Device parameters.
Definition at line 119 of file DriverStanda_uSMC.h.
Referenced by Exit(), and InitActuator().
_rotator
int DriverStanda_uSMC::_rotator mutable protected
Rotator flag/value.
Definition at line 127 of file DriverStanda_uSMC.h.
Referenced by Exit(), GetPos(), InitActuator(), Move(), MoveAbs(), OperationComplete(), and Stop().
_speed
float DriverStanda_uSMC::_speed mutable protected
Current speed value.
Definition at line 125 of file DriverStanda_uSMC.h.
Referenced by Exit(), GetPos(), InitActuator(), Move(), MoveAbs(), OperationComplete(), and Stop().
_start_params
USMC_StartParameters DriverStanda_uSMC::_start_params mutable protected
Start parameters.
Definition at line 117 of file DriverStanda_uSMC.h.
Referenced by Move(), and MoveAbs().
_state
USMC_State DriverStanda_uSMC::_state mutable protected
Current device state.
Definition at line 115 of file DriverStanda_uSMC.h.
Referenced by Exit(), GetPos(), and OperationComplete().
BUFFER_SIZE
const int DriverStanda_uSMC::BUFFER_SIZE = 0 static protected
Serial buffer size.
Definition at line 95 of file DriverStanda_uSMC.h.
MAX_DEVICES
const int DriverStanda_uSMC::MAX_DEVICES = 0 static protected
Maximum device count.
Definition at line 97 of file DriverStanda_uSMC.h.
MAX_TRIES
const int DriverStanda_uSMC::MAX_TRIES = 10 static protected
Maximum retry count.
Definition at line 105 of file DriverStanda_uSMC.h.
MAX_VEL
const float DriverStanda_uSMC::MAX_VEL = 0 static protected
Maximum velocity.
Definition at line 99 of file DriverStanda_uSMC.h.
MIN_BYTES_TRANS
const int DriverStanda_uSMC::MIN_BYTES_TRANS = 7 static protected
Minimum bytes per transfer.
Definition at line 107 of file DriverStanda_uSMC.h.
NB_ITEM_DRV_SETTING
const int DriverStanda_uSMC::NB_ITEM_DRV_SETTING = 0 static protected
Number of driver settings items.
Definition at line 103 of file DriverStanda_uSMC.h.
NB_ITEM_INIT_SETTING
const int DriverStanda_uSMC::NB_ITEM_INIT_SETTING = 4 static protected
Number of init settings items.
Definition at line 101 of file DriverStanda_uSMC.h.
Referenced by Exit(), GetPos(), InitActuator(), Move(), MoveAbs(), OperationComplete(), and Stop().
STANDA_USMC_FEATURE
const DriverFeature DriverStanda_uSMC::STANDA_USMC_FEATURE static protected
Initial value:
=
  { "step","step",1,1,CLOSED_LOOP,NULL }
Standa USMC driver features.
Definition at line 28 of file DriverStanda_uSMC.h.
Referenced by GetActuatorFeature().
The documentation for this class was generated from the following files:
DriverStanda_uSMC.h
DriverStanda_uSMC.cpp