OpticsBenchUI: VideoWidgetSurface Class Reference
VideoWidgetSurface Class Reference
UI
#include <VideoWidgetSurface.h>
Public Member Functions
VideoWidgetSurface (QWidget *widget, QObject *parent=0)
QList< QVideoFrame::PixelFormat > supportedPixelFormats (QAbstractVideoBuffer::HandleType handleType=QAbstractVideoBuffer::NoHandle) const override
[0]
bool isFormatSupported (const QVideoSurfaceFormat &format) const override
bool start (const QVideoSurfaceFormat &format) override
void stop () override
Stop rendering.
bool present (const QVideoFrame &frame) override
QRect videoRect () const
Return the target rectangle for video.
void updateVideoRect ()
Recompute the video rectangle.
void paint (QPainter *painter)
Detailed Description
[0]
Video surface that renders frames into a widget.
Definition at line 10 of file VideoWidgetSurface.h.
Constructor & Destructor Documentation
VideoWidgetSurface()
VideoWidgetSurface::VideoWidgetSurface (QWidget * widget, QObject * parent = 0)
Construct a video surface for a widget.
Parameters
widget Target widget.
parent Parent object.
Definition at line 5 of file VideoWidgetSurface.cpp.
Member Function Documentation
isFormatSupported()
bool VideoWidgetSurface::isFormatSupported (const QVideoSurfaceFormat & format) const override
Check whether a format is supported.
Parameters
format Video surface format.
[0] [1]
Definition at line 28 of file VideoWidgetSurface.cpp.
paint()
void VideoWidgetSurface::paint (QPainter * painter)
Paint the current frame.
Parameters
painter Painter to draw with.
[5] [6]
Definition at line 89 of file VideoWidgetSurface.cpp.
present()
bool VideoWidgetSurface::present (const QVideoFrame & frame) override
Present a new frame.
Parameters
frame Video frame.
[3] [4]
Definition at line 65 of file VideoWidgetSurface.cpp.
References stop().
start()
bool VideoWidgetSurface::start (const QVideoSurfaceFormat & format) override
Start rendering with a format.
Parameters
format Video surface format.
[1] [2]
Definition at line 38 of file VideoWidgetSurface.cpp.
References updateVideoRect().
stop()
void VideoWidgetSurface::stop () override
Stop rendering.
[2] [3]
Definition at line 56 of file VideoWidgetSurface.cpp.
Referenced by present().
supportedPixelFormats()
QList< QVideoFrame::PixelFormat > VideoWidgetSurface::supportedPixelFormats (QAbstractVideoBuffer::HandleType handleType = QAbstractVideoBuffer::NoHandle) const override
[0]
Return the supported pixel formats.
Parameters
handleType Buffer handle type.
Definition at line 12 of file VideoWidgetSurface.cpp.
updateVideoRect()
void VideoWidgetSurface::updateVideoRect ()
Recompute the video rectangle.
[4] [5]
Definition at line 80 of file VideoWidgetSurface.cpp.
Referenced by start().
videoRect()
QRect VideoWidgetSurface::videoRect () const inline
Return the target rectangle for video.
Definition at line 34 of file VideoWidgetSurface.h.
The documentation for this class was generated from the following files:
VideoWidgetSurface.h
VideoWidgetSurface.cpp