OpticsBenchUI: DacWindow Class Reference
DacWindow Class Reference
UI
#include <DacWindow.h>
Public Slots
void update ()
Update database-backed tables.
void remove ()
Remove selected entries.
void load ()
Load configuration into runtime.
void setDbPath (QString path)
Public Member Functions
DacWindow (QMainWindow *parent=nullptr, Qt::WindowFlags fl=Qt::Window, Dac *dac=nullptr)
~DacWindow () override
Destructor.
Public Attributes
DacControlWidget * dacWidget
DAC control widget instance.
Protected Member Functions
void closeEvent (QCloseEvent *event) override
Detailed Description
Window for DAC configuration and control.
Definition at line 33 of file DacWindow.h.
Constructor & Destructor Documentation
DacWindow()
DacWindow::DacWindow (QMainWindow * parent = nullptr, Qt::WindowFlags fl = Qt::Window, Dac * dac = nullptr)
Construct a DAC window.
Parameters
parent Parent window.
fl Window flags.
dac DAC controller instance.
Definition at line 32 of file DacWindow.cpp.
References Utils::ConfigureSqlTableView(), dacWidget, load(), Dac::path, QLOG_INFO, remove(), DacControlWidget::setDac(), and update().
~DacWindow()
DacWindow::~DacWindow () override
Destructor.
Definition at line 88 of file DacWindow.cpp.
References QLOG_DEBUG.
Member Function Documentation
closeEvent()
void DacWindow::closeEvent (QCloseEvent * event) override protected
Handle window close events.
Parameters
event Close event.
Definition at line 108 of file DacWindow.cpp.
References QLOG_DEBUG.
load
void DacWindow::load () slot
Load configuration into runtime.
Definition at line 130 of file DacWindow.cpp.
Referenced by DacWindow().
remove
void DacWindow::remove () slot
Remove selected entries.
Definition at line 134 of file DacWindow.cpp.
Referenced by DacWindow().
setDbPath
void DacWindow::setDbPath (QString path) slot
Set the database path for tables.
Parameters
path Filesystem path to the DAC DB.
Definition at line 94 of file DacWindow.cpp.
References Utils::ConfigureSqlTableView(), Dac::path, and Dac::setDbPath().
update
void DacWindow::update () slot
Update database-backed tables.
Definition at line 126 of file DacWindow.cpp.
Referenced by DacWindow().
Member Data Documentation
dacWidget
DacControlWidget* DacWindow::dacWidget
DAC control widget instance.
Definition at line 49 of file DacWindow.h.
Referenced by DacWindow().
The documentation for this class was generated from the following files:
DacWindow.h
DacWindow.cpp