OpticsBenchUI: DriverSuperK Class Reference
DriverSuperK Class Reference
Hardware » Lasers
#include <DriverSuperK.h>
Public Member Functions
DriverSuperK (ACCom *commChannel)
virtual ~DriverSuperK ()
Destructor.
virtual int Init ()
Initialize the SuperK device.
virtual int setPower (int power)
virtual int getPower (int &power)
virtual int setNd (int nd)
virtual int getNd (int &nd)
virtual int setSwp (int swp)
virtual int getSwp (int &swp)
virtual int setLwp (int lwp)
virtual int getLwp (int &lwp)
virtual int operationComplete ()
Check whether the last command has completed.
Detailed Description
Low-level driver for the SuperK laser over Interbus.
Definition at line 44 of file DriverSuperK.h.
Constructor & Destructor Documentation
DriverSuperK()
DriverSuperK::DriverSuperK (ACCom * commChannel)
Constructor.
Parameters
commChannel Communication channel instance.
Definition at line 31 of file DriverSuperK.cpp.
References QLOG_DEBUG.
~DriverSuperK()
DriverSuperK::~DriverSuperK () virtual
Destructor.
Definition at line 37 of file DriverSuperK.cpp.
References QLOG_DEBUG.
Member Function Documentation
getLwp()
int DriverSuperK::getLwp (int & lwp) virtual
Read the current long-wavelength pass (LWP) value.
Parameters
lwp Output LWP value.
Definition at line 125 of file DriverSuperK.cpp.
References QLOG_DEBUG, and QLOG_INFO.
Referenced by SuperK::connectSuperK().
getNd()
int DriverSuperK::getNd (int & nd) virtual
Read the current neutral density (ND) value.
Parameters
nd Output ND value.
Definition at line 83 of file DriverSuperK.cpp.
References QLOG_DEBUG, and QLOG_INFO.
Referenced by SuperK::connectSuperK().
getPower()
int DriverSuperK::getPower (int & power) virtual
Read the current power setting.
Parameters
power Output power value.
Definition at line 62 of file DriverSuperK.cpp.
References QLOG_DEBUG, and QLOG_INFO.
Referenced by SuperK::connectSuperK().
getSwp()
int DriverSuperK::getSwp (int & swp) virtual
Read the current short-wavelength pass (SWP) value.
Parameters
swp Output SWP value.
Definition at line 104 of file DriverSuperK.cpp.
References QLOG_DEBUG, and QLOG_INFO.
Referenced by SuperK::connectSuperK().
Init()
int DriverSuperK::Init () virtual
Initialize the SuperK device.
Definition at line 43 of file DriverSuperK.cpp.
References QLOG_DEBUG, and QLOG_INFO.
Referenced by SuperK::connectSuperK().
operationComplete()
int DriverSuperK::operationComplete () virtual
Check whether the last command has completed.
Definition at line 146 of file DriverSuperK.cpp.
References QLOG_DEBUG.
setLwp()
int DriverSuperK::setLwp (int lwp) virtual
Set the long-wavelength pass (LWP) value.
Parameters
lwp LWP value.
Definition at line 136 of file DriverSuperK.cpp.
References QLOG_DEBUG.
setNd()
int DriverSuperK::setNd (int nd) virtual
Set the neutral density (ND) value.
Parameters
nd ND value.
Definition at line 94 of file DriverSuperK.cpp.
References QLOG_DEBUG.
setPower()
int DriverSuperK::setPower (int power) virtual
Set the power setting.
Parameters
power Power value.
Definition at line 73 of file DriverSuperK.cpp.
References QLOG_DEBUG.
setSwp()
int DriverSuperK::setSwp (int swp) virtual
Set the short-wavelength pass (SWP) value.
Parameters
swp SWP value.
Definition at line 115 of file DriverSuperK.cpp.
References QLOG_DEBUG.
The documentation for this class was generated from the following files:
DriverSuperK.h
DriverSuperK.cpp