OpticsBenchUI: SuperK Class Reference
SuperK Class Reference
Hardware » Lasers
#include <SuperK.h>
Public Slots
void operationComplete ()
Slot called when a driver operation completes.
Signals
void getPower (int power)
void getNd (int nd)
void getSwp (int swp)
void getLwp (int lwp)
void getDescription (QString description)
void showWarning (QString message)
void stopTimer ()
Request timers to stop (UI coordination).
Public Member Functions
SuperK (QObject *parent=0, QString _appDirPath=0)
~SuperK ()
Destructor.
void connectSuperK (QString newdriver)
void setPower (QString newdriver, int power)
void setNd (QString newdriver, int nd)
void setSwp (QString newdriver, int swp)
void setLwp (QString newdriver, int lwp)
void setDbPath (QString _path)
int getOperationComplete (QString newdriver)
int getPower (QString newdriver)
int getNd (QString newdriver)
int getSwp (QString newdriver)
int getLwp (QString newdriver)
Public Attributes
QVector< int > operationcomplete
Per-driver completion flags.
QString path
Path to the SuperK database.
Detailed Description
Controls a SuperK laser source via its driver.
Definition at line 35 of file SuperK.h.
Constructor & Destructor Documentation
SuperK()
SuperK::SuperK (QObject * parent = 0, QString _appDirPath = 0)
Create a SuperK controller.
Parameters
parent QObject parent.
_appDirPath Application directory for locating databases.
Definition at line 26 of file SuperK.cpp.
References path.
~SuperK()
SuperK::~SuperK ()
Destructor.
Definition at line 34 of file SuperK.cpp.
References operationcomplete, path, and QLOG_DEBUG.
Member Function Documentation
connectSuperK()
void SuperK::connectSuperK (QString newdriver)
Connect to a SuperK driver by name.
Parameters
newdriver Driver identifier from the database.
Definition at line 87 of file SuperK.cpp.
References ACCom::Create(), Utils::EmitWarning(), getDescription(), DriverSuperK::getLwp(), getLwp(), DriverSuperK::getNd(), getNd(), DriverSuperK::getPower(), getPower(), DriverSuperK::getSwp(), getSwp(), DriverSuperK::Init(), ACCom::Open(), operationcomplete, path, QLOG_DEBUG, and QLOG_INFO.
getDescription
void SuperK::getDescription (QString description) signal
Emit a human-readable description of the device.
Parameters
description Device description string.
Referenced by connectSuperK().
getLwp [1/2]
void SuperK::getLwp (int lwp) signal
Emit current LWP value.
Parameters
lwp LWP value.
getLwp() [2/2]
int SuperK::getLwp (QString newdriver)
Read current LWP setting.
Parameters
newdriver Driver identifier from the database.
Definition at line 309 of file SuperK.cpp.
Referenced by connectSuperK(), and operationComplete().
getNd [1/2]
void SuperK::getNd (int nd) signal
Emit current ND value.
Parameters
nd ND value.
getNd() [2/2]
int SuperK::getNd (QString newdriver)
Read current ND setting.
Parameters
newdriver Driver identifier from the database.
Definition at line 257 of file SuperK.cpp.
Referenced by connectSuperK(), and operationComplete().
getOperationComplete()
int SuperK::getOperationComplete (QString newdriver)
Return nonzero when the driver operation is complete.
Parameters
newdriver Driver identifier from the database.
Definition at line 322 of file SuperK.cpp.
References operationcomplete.
getPower [1/2]
void SuperK::getPower (int power) signal
Emit current power value.
Parameters
power Power value.
getPower() [2/2]
int SuperK::getPower (QString newdriver)
Read current power setting.
Parameters
newdriver Driver identifier from the database.
Definition at line 231 of file SuperK.cpp.
Referenced by connectSuperK(), and operationComplete().
getSwp [1/2]
void SuperK::getSwp (int swp) signal
Emit current SWP value.
Parameters
swp SWP value.
getSwp() [2/2]
int SuperK::getSwp (QString newdriver)
Read current SWP setting.
Parameters
newdriver Driver identifier from the database.
Definition at line 283 of file SuperK.cpp.
Referenced by connectSuperK(), and operationComplete().
operationComplete
void SuperK::operationComplete () slot
Slot called when a driver operation completes.
Definition at line 334 of file SuperK.cpp.
References getLwp(), getNd(), getPower(), getSwp(), operationcomplete, path, QLOG_DEBUG, and stopTimer().
setDbPath()
void SuperK::setDbPath (QString _path)
Set the path to the SuperK database.
Parameters
_path Filesystem path to the SuperK SQLite DB.
Definition at line 60 of file SuperK.cpp.
References operationcomplete, and path.
Referenced by SuperKWindow::setDbPath().
setLwp()
void SuperK::setLwp (QString newdriver, int lwp)
Set the long-wavelength pass (LWP) value.
Parameters
newdriver Driver identifier from the database.
lwp LWP value.
Definition at line 296 of file SuperK.cpp.
References operationcomplete.
setNd()
void SuperK::setNd (QString newdriver, int nd)
Set the neutral density (ND) value.
Parameters
newdriver Driver identifier from the database.
nd ND value.
Definition at line 245 of file SuperK.cpp.
References operationcomplete.
setPower()
void SuperK::setPower (QString newdriver, int power)
Set the output power.
Parameters
newdriver Driver identifier from the database.
power Power value (device units).
Definition at line 219 of file SuperK.cpp.
References operationcomplete.
setSwp()
void SuperK::setSwp (QString newdriver, int swp)
Set the short-wavelength pass (SWP) value.
Parameters
newdriver Driver identifier from the database.
swp SWP value.
Definition at line 270 of file SuperK.cpp.
References operationcomplete.
showWarning
void SuperK::showWarning (QString message) signal
Emit warnings to the UI.
Parameters
message Warning message.
stopTimer
void SuperK::stopTimer () signal
Request timers to stop (UI coordination).
Referenced by operationComplete().
Member Data Documentation
operationcomplete
QVector<int> SuperK::operationcomplete
Per-driver completion flags.
Definition at line 87 of file SuperK.h.
Referenced by connectSuperK(), getOperationComplete(), operationComplete(), setDbPath(), setLwp(), setNd(), setPower(), setSwp(), and ~SuperK().
path
QString SuperK::path
Path to the SuperK database.
Definition at line 89 of file SuperK.h.
Referenced by connectSuperK(), operationComplete(), setDbPath(), SuperKWindow::setDbPath(), SuperK(), SuperKWindow::SuperKWindow(), and ~SuperK().
The documentation for this class was generated from the following files:
SuperK.h
SuperK.cpp