OpticsBenchUI: CameraControlWidget Class Reference
CameraControlWidget Class Reference
UI
#include <CameraControlWidget.h>
Signals
void setFeature (int position, double value)
void setMode (int position, bool value)
void showWarning (QString message)
Public Member Functions
CameraControlWidget (Camera *_camera=nullptr)
~CameraControlWidget ()
Destructor.
Detailed Description
UI widget for camera feature control.
Definition at line 35 of file CameraControlWidget.h.
Constructor & Destructor Documentation
CameraControlWidget()
CameraControlWidget::CameraControlWidget (Camera * _camera = nullptr)
Construct a control widget for a camera.
Parameters
_camera Camera to control.
Definition at line 95 of file CameraControlWidget.cpp.
References setFeature(), and setMode().
~CameraControlWidget()
CameraControlWidget::~CameraControlWidget ()
Destructor.
Definition at line 246 of file CameraControlWidget.cpp.
Member Function Documentation
setFeature
void CameraControlWidget::setFeature (int position, double value) signal
Set a camera feature value.
Parameters
position Feature index.
value Feature value.
Referenced by CameraControlWidget().
setMode
void CameraControlWidget::setMode (int position, bool value) signal
Set a camera feature mode.
Parameters
position Feature index.
value True for auto/enable, false for manual/disable.
Referenced by CameraControlWidget().
showWarning
void CameraControlWidget::showWarning (QString message) signal
Emit warnings to the UI.
Parameters
message Warning message.
The documentation for this class was generated from the following files:
CameraControlWidget.h
CameraControlWidget.cpp