OpticsBenchUI: ACCom Class Reference
ACCom Class Reference abstract
#include <ACCom.h>
Public Types
enum { OPEN , CLOSED }
Public Member Functions
ACCom (string device, string settings)
ACCom (const ACCom &channel)
virtual ~ACCom ()
virtual int Open ()=0
virtual int Read (string &message,...)=0
virtual int Write (string &message,...)=0
virtual int Close ()=0
virtual int GetStatus () const
Static Public Member Functions
static ACCom * Create (string channelType, string device, string settings)
static ACCom * Create (const ACCom *prefChannel)
Static Public Attributes
static const string RS_COM = "SERIAL_PORT"
static const string ETH_COM = "ETHERNET"
static const string MB_COM = "MB_COM"
static const string USB_COM = "USB_COM"
static const string CAN_COM = "CAN_COM"
static const string NULL_COM = "NULL_COM"
Protected Member Functions
void ReportWarning (const QString &message) const
Log a warning message tagged with this communication channel.
void ReportError (const QString &message) const
Log an error message tagged with this communication channel.
Protected Attributes
int _state
string _device
string _settings
Detailed Description
Abstract communication channel for device drivers.
Concrete implementations provide protocol-specific open/read/write operations (serial, ethernet, USB, CAN, etc.).
Definition at line 41 of file ACCom.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
The state values of the channel communication
Definition at line 48 of file ACCom.h.
Constructor & Destructor Documentation
ACCom() [1/2]
ACCom::ACCom (string device, string settings)
Constructor
Parameters
device The device name or address
settings The setting string as set in the configuration file
Definition at line 32 of file ACCom.cpp.
References _device, _settings, and _state.
Referenced by ACCom(), ACEthCom::ACEthCom(), ACEthCom::ACEthCom(), ACRSCom::ACRSCom(), ACRSCom::ACRSCom(), ACUsbCom::ACUsbCom(), ACUsbCom::ACUsbCom(), Create(), and Create().
ACCom() [2/2]
ACCom::ACCom (const ACCom & channel) inline
Copy Constructor
Parameters
channel The object to be copyied
Definition at line 75 of file ACCom.h.
References _device, _settings, _state, and ACCom().
~ACCom()
virtual ACCom::~ACCom () inline virtual
Destructor
Definition at line 84 of file ACCom.h.
Member Function Documentation
Close()
virtual int ACCom::Close () pure virtual
The Close method allows to close the channel communication port
Implemented in ACEthCom, ACRSCom, and ACUsbCom.
Create() [1/2]
ACCom * ACCom::Create (const ACCom * prefChannel) static
Copy factory instantiator
Parameters
prefChannel The communication object to be instantiated
Definition at line 94 of file ACCom.cpp.
References ACCom().
Create() [2/2]
ACCom * ACCom::Create (string channelType, string device, string settings) static
The Create method is the factory instantiator of the communication object
Parameters
channelType The type of channel to be instantiated (SERIAL,ETHERNET MB_COM,CAN_COM)
device The device name or address as set in the configuration file
settings The settings string as set in the configuration file
Definition at line 56 of file ACCom.cpp.
References ACCom(), ETH_COM, NULL_COM, Utils::ReportWarning(), RS_COM, and USB_COM.
Referenced by Motor::connectMotor(), and SuperK::connectSuperK().
GetStatus()
virtual int ACCom::GetStatus () const inline virtual
The GetStatus returns the channel status (OPEN or CLOSE)
Definition at line 138 of file ACCom.h.
References _state.
Open()
virtual int ACCom::Open () pure virtual
The Open method allows to open the channel communication port
Implemented in ACEthCom, ACRSCom, and ACUsbCom.
Referenced by Motor::connectMotor(), and SuperK::connectSuperK().
Read()
virtual int ACCom::Read (string & message, ...) pure virtual
The Read method allows to read in the channel communication port
Parameters
message The message to be read
... Various parameters depending on the type of protocol used
Implemented in ACEthCom, ACRSCom, and ACUsbCom.
ReportError()
void ACCom::ReportError (const QString & message) const protected
Log an error message tagged with this communication channel.
Definition at line 42 of file ACCom.cpp.
References Utils::ReportError().
Referenced by ACUsbCom::Close(), ACEthCom::Open(), ACRSCom::Open(), and ACUsbCom::Open().
ReportWarning()
void ACCom::ReportWarning (const QString & message) const protected
Log a warning message tagged with this communication channel.
Definition at line 37 of file ACCom.cpp.
References Utils::ReportWarning().
Referenced by ACRSCom::Close(), ACEthCom::Open(), and ACEthCom::Write().
Write()
virtual int ACCom::Write (string & message, ...) pure virtual
The Write method allows to write in the channel communication port
Parameters
message The message to be written
... Various parameters depending on the type of protocol used
Implemented in ACEthCom, ACRSCom, and ACUsbCom.
Member Data Documentation
_device
string ACCom::_device protected
The internal device name of the channel communication
Definition at line 153 of file ACCom.h.
Referenced by ACCom(), ACCom(), ACEthCom::Open(), and ACRSCom::Open().
_settings
string ACCom::_settings protected
The internal settings of the channel communication
Definition at line 158 of file ACCom.h.
Referenced by ACCom(), ACCom(), ACEthCom::Open(), ACRSCom::Open(), and ACUsbCom::Open().
_state
int ACCom::_state protected
The internal state of the channel communication
Definition at line 148 of file ACCom.h.
Referenced by ACCom(), ACCom(), ACEthCom::Close(), ACRSCom::Close(), ACUsbCom::Close(), GetStatus(), ACEthCom::Open(), ACRSCom::Open(), and ACUsbCom::Open().
CAN_COM
const string ACCom::CAN_COM = "CAN_COM" static
The canbus protocol code name
Definition at line 58 of file ACCom.h.
ETH_COM
const string ACCom::ETH_COM = "ETHERNET" static
The ethernet protocol code name
Definition at line 52 of file ACCom.h.
Referenced by Create().
MB_COM
const string ACCom::MB_COM = "MB_COM" static
The modbus protocol code name
Definition at line 54 of file ACCom.h.
NULL_COM
const string ACCom::NULL_COM = "NULL_COM" static
The blank protocol code name
Definition at line 60 of file ACCom.h.
Referenced by Create().
RS_COM
const string ACCom::RS_COM = "SERIAL_PORT" static
The serial port protocol code name
Definition at line 50 of file ACCom.h.
Referenced by Create().
USB_COM
const string ACCom::USB_COM = "USB_COM" static
The usb protocol code name
Definition at line 56 of file ACCom.h.
Referenced by Create().
The documentation for this class was generated from the following files:
ACCom.h
ACCom.cpp