OpticsBenchUI: Utils Namespace Reference
Utils Namespace Reference
Functions
double GetTimeMicroseconds ()
Return the current time in microseconds.
QString BuildDbPath (const QString &baseDir, const QString &filename)
QString CurrentTimestampString ()
Return the current timestamp as a formatted string.
QString EnsureHdf5Extension (const QString &filename)
QString DefaultHdf5Path (const QString &baseName)
QString Hdf5FileDialogFilter ()
Return the file dialog filter for HDF5 files.
QSqlDatabase ConnectSqliteDb (const QString &path, const char *logContext)
bool ExecSql (QSqlQuery &query, const QString &sql, const char *logContext)
void ReportError (const char *logContext, const QString &message)
void ReportWarning (const char *logContext, const QString &message)
void ConfigureSqlTableView (QTableView *view)
void UpdateSqlTableViewColumnSizing (QTableView *view)
void UpdateSqlTableViewRowSizing (QTableView *view)
template<typename T >
void EmitWarning (T *sender, const char *logContext, const QString &message)
Detailed Description
Utility helpers for logging, database paths, and timestamps.
Function Documentation
BuildDbPath()
QString Utils::BuildDbPath (const QString & baseDir, const QString & filename)
Build a database path from a base directory and filename.
Parameters
baseDir Base directory.
filename Database filename.
Definition at line 38 of file Utils.cpp.
Referenced by AcquisitionWidget::setDelegates().
ConfigureSqlTableView()
void Utils::ConfigureSqlTableView (QTableView * view)
Apply default sizing and wrapping behavior to SQL table views.
Parameters
view Table view to configure.
Definition at line 301 of file Utils.cpp.
References UpdateSqlTableViewColumnSizing(), and UpdateSqlTableViewRowSizing().
Referenced by AcquisitionWidget::AcquisitionWidget(), AnalysisWidget::AnalysisWidget(), ComediWindow::ComediWindow(), DacWindow::DacWindow(), MotorWindow::MotorWindow(), RaspiWindow::RaspiWindow(), MotorWindow::setDbPath(), RaspiWindow::setDbPath(), SuperKWindow::setDbPath(), AcquisitionWidget::setDbPath(), AnalysisWidget::setDbPath(), ComediWindow::setDbPath(), DacWindow::setDbPath(), and SuperKWindow::SuperKWindow().
ConnectSqliteDb()
QSqlDatabase Utils::ConnectSqliteDb (const QString & path, const char * logContext)
Open a SQLite database and log context for errors.
Parameters
path Database path.
logContext Context string for logging.
Definition at line 68 of file Utils.cpp.
References QLOG_INFO, and QLOG_WARN.
CurrentTimestampString()
QString Utils::CurrentTimestampString ()
Return the current timestamp as a formatted string.
Definition at line 44 of file Utils.cpp.
Referenced by main(), and AcquisitionThread::run().
DefaultHdf5Path()
QString Utils::DefaultHdf5Path (const QString & baseName)
Build a default HDF5 path using a base name.
Parameters
baseName Base filename.
Definition at line 55 of file Utils.cpp.
References EnsureHdf5Extension().
Referenced by OpticsBenchUIMain::saveAcqFile().
EmitWarning()
template<typename T > void Utils::EmitWarning (T * sender, const char * logContext, const QString & message)
Report a warning and emit showWarning when available.
Parameters
sender Object that may expose showWarning.
logContext Context string for logging.
message Warning message.
Definition at line 84 of file Utils.h.
References ReportWarning().
Referenced by Motor::connectMotor(), SuperK::connectSuperK(), CameraUSB::findCamera(), AcquisitionThread::run(), CameraUSB::setCamera(), AcquisitionWidget::showAcquisitionWarning(), and AnalysisWidget::showAnalysisWarning().
EnsureHdf5Extension()
QString Utils::EnsureHdf5Extension (const QString & filename)
Ensure a filename ends with the HDF5 extension.
Parameters
filename Input filename.
Definition at line 48 of file Utils.cpp.
Referenced by DefaultHdf5Path(), and OpticsBenchUIMain::saveAcqFile().
ExecSql()
bool Utils::ExecSql (QSqlQuery & query, const QString & sql, const char * logContext)
Execute a SQL statement and log on error.
Parameters
query Query object.
sql SQL statement.
logContext Context string for logging.
Definition at line 82 of file Utils.cpp.
References ReportWarning().
GetTimeMicroseconds()
double Utils::GetTimeMicroseconds ()
Return the current time in microseconds.
Definition at line 32 of file Utils.cpp.
Referenced by AcquisitionThread::run().
Hdf5FileDialogFilter()
QString Utils::Hdf5FileDialogFilter ()
Return the file dialog filter for HDF5 files.
Definition at line 64 of file Utils.cpp.
Referenced by OpticsBenchUIMain::saveAcqFile().
ReportError()
void Utils::ReportError (const char * logContext, const QString & message)
Log an error with context.
Parameters
logContext Context string for logging.
message Error message.
Definition at line 90 of file Utils.cpp.
References QLOG_ERROR.
Referenced by Driver::ReportCommError(), ACCom::ReportError(), and Driver::ReportError().
ReportWarning()
void Utils::ReportWarning (const char * logContext, const QString & message)
Log a warning with context.
Parameters
logContext Context string for logging.
message Warning message.
Definition at line 98 of file Utils.cpp.
References QLOG_WARN.
Referenced by ACCom::Create(), EmitWarning(), ExecSql(), DriverPI_E725::GetPos(), DriverNewPort_NSC200::InitActuator(), Driver::ReportRangeError(), Driver::ReportSettingError(), ACCom::ReportWarning(), and Driver::ReportWarning().
UpdateSqlTableViewColumnSizing()
void Utils::UpdateSqlTableViewColumnSizing (QTableView * view)
Update column sizing based on content and viewport width.
Parameters
view Table view to update.
Definition at line 348 of file Utils.cpp.
Referenced by ConfigureSqlTableView().
UpdateSqlTableViewRowSizing()
void Utils::UpdateSqlTableViewRowSizing (QTableView * view)
Update row sizing based on current model content.
Parameters
view Table view to update.
Definition at line 384 of file Utils.cpp.
Referenced by ConfigureSqlTableView().