OpticsBenchUI: RaspiDac Class Reference
RaspiDac Class Reference
Hardware » Dac
#include <RaspiDac.h>
Signals
void getDescription (QString description)
void showWarning (QString message)
void getOutputs (int outputs)
void getOutputValues (void *raspivalues)
Signals inherited from Raspi
void getDescription (QString description)
void showWarning (QString message)
void getOutputs (int outputs)
void getOutputValues (void *raspivalues)
Public Member Functions
RaspiDac (QString dbpath)
~RaspiDac ()
Destructor.
bool connectRaspi (QString newraspi)
bool resetRaspi (QString newraspi)
bool setRaspiValue (QString newraspi, int output, void *value)
bool getRaspiValue (QString newraspi, int output, double &value)
bool updateDBValues (QString newraspi)
void setDbPath (QString _path)
Public Attributes
QString path
QString raspitype
Public Attributes inherited from Raspi
QString path
Path to the Raspi database.
QString raspitype
Raspi device type identifier.
Additional Inherited Members
Detailed Description
Raspberry Pi DAC implementation.
Definition at line 35 of file RaspiDac.h.
Constructor & Destructor Documentation
RaspiDac()
RaspiDac::RaspiDac (QString dbpath) explicit
Create a Raspi DAC using the given DB path.
Parameters
dbpath Filesystem path to the Raspi DB.
Definition at line 30 of file RaspiDac.cpp.
References path, QLOG_ERROR, and raspitype.
~RaspiDac()
RaspiDac::~RaspiDac ()
Destructor.
Definition at line 44 of file RaspiDac.cpp.
References path, and QLOG_DEBUG.
Member Function Documentation
connectRaspi()
bool RaspiDac::connectRaspi (QString newraspi) virtual
Connect to the Raspi DAC device.
Parameters
newraspi Device identifier from the database.
Implements Raspi.
Definition at line 94 of file RaspiDac.cpp.
References Utils::EmitWarning(), getDescription(), getOutputs(), getOutputValues(), path, QLOG_DEBUG, QLOG_INFO, and resetRaspi().
getDescription
void RaspiDac::getDescription (QString description) signal
Emit a human-readable description of the device.
Parameters
description Device description string.
Referenced by connectRaspi().
getOutputs
void RaspiDac::getOutputs (int outputs) signal
Emit output count.
Parameters
outputs Number of outputs.
Referenced by connectRaspi().
getOutputValues
void RaspiDac::getOutputValues (void * raspivalues) signal
Emit output values (device-specific type).
Parameters
raspivalues Pointer to device-specific values.
Referenced by connectRaspi(), and updateDBValues().
getRaspiValue()
bool RaspiDac::getRaspiValue (QString newraspi, int output, double & value) virtual
Read a DAC output value.
Parameters
newraspi Device identifier from the database.
output Output channel index.
value Output value in engineering units.
Implements Raspi.
Definition at line 486 of file RaspiDac.cpp.
References QLOG_INFO.
Referenced by setRaspiValue().
resetRaspi()
bool RaspiDac::resetRaspi (QString newraspi) virtual
Reset the DAC device.
Parameters
newraspi Device identifier from the database.
Implements Raspi.
Definition at line 355 of file RaspiDac.cpp.
References QLOG_INFO.
Referenced by connectRaspi().
setDbPath()
void RaspiDac::setDbPath (QString _path) virtual
Set the database path used by this device.
Parameters
_path Filesystem path to the Raspi DB.
Implements Raspi.
Definition at line 68 of file RaspiDac.cpp.
References path.
setRaspiValue()
bool RaspiDac::setRaspiValue (QString newraspi, int output, void * value) virtual
Set a DAC output value (device-specific).
Parameters
newraspi Device identifier from the database.
output Output channel index.
value Pointer to a device-specific value.
Implements Raspi.
Definition at line 406 of file RaspiDac.cpp.
References Utils::EmitWarning(), getRaspiValue(), LSB, MSB, and QLOG_INFO.
showWarning
void RaspiDac::showWarning (QString message) signal
Emit warnings to the UI.
Parameters
message Warning message.
updateDBValues()
bool RaspiDac::updateDBValues (QString newraspi) virtual
Sync or update database-backed settings.
Parameters
newraspi Device identifier from the database.
Implements Raspi.
Definition at line 563 of file RaspiDac.cpp.
References Utils::EmitWarning(), getOutputValues(), path, and QLOG_DEBUG.
Member Data Documentation
path
QString RaspiDac::path
Definition at line 69 of file RaspiDac.h.
Referenced by connectRaspi(), RaspiDac(), setDbPath(), updateDBValues(), and ~RaspiDac().
raspitype
QString RaspiDac::raspitype
Definition at line 70 of file RaspiDac.h.
Referenced by RaspiDac().
The documentation for this class was generated from the following files:
RaspiDac.h
RaspiDac.cpp