OpticsBenchUI: MotorWindow Class Reference
MotorWindow Class Reference
UI » Motor UI
#include <MotorWindow.h>
Public Slots
void update ()
Update database-backed tables.
void remove ()
Remove selected entries.
void load ()
Load configuration into runtime.
void setDbPath (QString _path)
void refreshActuatorTable ()
Refresh actuator table to show latest positions.
Public Member Functions
MotorWindow (QMainWindow *parent=0, Qt::WindowFlags fl=Qt::Window, Motor *_motor=0)
virtual ~MotorWindow ()
Destructor.
Public Attributes
MotorControlWidget * motorWidget
Motor control widget instance.
Protected Member Functions
void closeEvent (QCloseEvent *event)
Detailed Description
Window for motor configuration and control.
Definition at line 34 of file MotorWindow.h.
Constructor & Destructor Documentation
MotorWindow()
MotorWindow::MotorWindow (QMainWindow * parent = 0, Qt::WindowFlags fl = Qt::Window, Motor * _motor = 0)
Construct a motor window.
Parameters
parent Parent window.
fl Window flags.
_motor Motor controller instance.
Definition at line 26 of file MotorWindow.cpp.
References Utils::ConfigureSqlTableView(), load(), motorWidget, Motor::path, refreshActuatorTable(), remove(), MotorControlWidget::setMotor(), and update().
~MotorWindow()
MotorWindow::~MotorWindow () virtual
Destructor.
Definition at line 129 of file MotorWindow.cpp.
References QLOG_DEBUG.
Member Function Documentation
closeEvent()
void MotorWindow::closeEvent (QCloseEvent * event) protected
Handle window close events.
Parameters
event Close event.
Definition at line 182 of file MotorWindow.cpp.
References QLOG_DEBUG.
load
void MotorWindow::load () slot
Load configuration into runtime.
Definition at line 237 of file MotorWindow.cpp.
Referenced by MotorWindow().
refreshActuatorTable
void MotorWindow::refreshActuatorTable () slot
Refresh actuator table to show latest positions.
Definition at line 228 of file MotorWindow.cpp.
References Utils::UpdateSqlTableViewColumnSizing(), and Utils::UpdateSqlTableViewRowSizing().
Referenced by MotorWindow().
remove
void MotorWindow::remove () slot
Remove selected entries.
Definition at line 241 of file MotorWindow.cpp.
Referenced by MotorWindow().
setDbPath
void MotorWindow::setDbPath (QString _path) slot
Set the database path for tables.
Parameters
_path Filesystem path to the motor DB.
Definition at line 137 of file MotorWindow.cpp.
References Utils::ConfigureSqlTableView(), Motor::path, and Motor::setDbPath().
Referenced by OpticsBenchUIMain::applyConfigurationDirectory().
update
void MotorWindow::update () slot
Update database-backed tables.
Definition at line 218 of file MotorWindow.cpp.
References motorWidget, and MotorControlWidget::refreshCurrentPosition().
Referenced by MotorWindow().
Member Data Documentation
motorWidget
MotorControlWidget* MotorWindow::motorWidget
Motor control widget instance.
Definition at line 50 of file MotorWindow.h.
Referenced by MotorWindow(), and update().
The documentation for this class was generated from the following files:
MotorWindow.h
MotorWindow.cpp