OpticsBenchUI: AcquisitionWidget Class Reference
AcquisitionWidget Class Reference
UI » Acquisition
#include <AcquisitionWidget.h>
Public Slots
void update ()
Refresh displayed values.
void reload ()
Reload the acquisition table.
void remove ()
Remove the selected acquisition row.
void run ()
Start acquisition.
void stop ()
Stop acquisition.
void splashScreen (QString imagepath, int screen_x, int screen_y)
void getPosition (QString positionQString)
void getSuperKData (QString dataStr)
void getCameraStatus (bool imagesuccess)
void getDacStatus (bool dacsuccess)
void getMotorStatus (bool motorsuccess)
void getSuperKStatus (bool superksuccess)
void getTreatmentStatus (bool treatmentstatus)
void getAcquiring (int record)
void getFilenumber (int number)
void isopenCameraWindow (QVector< bool > isopencamerawindow)
void showAcquisitionWarning (QString message)
void requestAnalysisFromThread ()
Relay analysis request from acquisition thread.
void acquisitionFinished ()
Update elapsed time when acquisition thread finishes.
void updateElapsed ()
Update elapsed time while acquisition runs.
int currentAcquiringRecord () const
Current record being processed (for UI highlight).
Signals
void showWarning (QString message)
void requestAnalysis ()
Request analysis execution.
void runningChanged (bool running)
Public Member Functions
AcquisitionWidget (QString appDirPath=QString())
~AcquisitionWidget () override
Destructor.
void setCamera (QVector< Camera * > cameraList)
void setMotor (Motor *motor)
void setSuperK (SuperK *superk)
void setDac (Dac *dac)
void setComediCounter (Comedi *comedi)
void setComediDac (Comedi *comedi)
void setRaspiDac (Raspi *raspi)
void setDelegates ()
Create and apply table delegates.
void setDbPath (QString path)
void setAcqFile (QString acqfile)
Detailed Description
UI widget for configuring and running acquisition sequences.
Definition at line 37 of file AcquisitionWidget.h.
Constructor & Destructor Documentation
AcquisitionWidget()
AcquisitionWidget::AcquisitionWidget (QString appDirPath = QString()) explicit
Construct the acquisition widget.
Parameters
appDirPath Application directory for resources and DBs.
Definition at line 76 of file AcquisitionWidget.cpp.
References acquisitionFinished(), Utils::ConfigureSqlTableView(), getAcquiring(), getCameraStatus(), getDacStatus(), getFilenumber(), getMotorStatus(), getPosition(), getSuperKData(), getSuperKStatus(), getTreatmentStatus(), QLOG_DEBUG, reload(), remove(), requestAnalysis(), requestAnalysisFromThread(), run(), showAcquisitionWarning(), showWarning(), splashScreen(), stop(), update(), and updateElapsed().
~AcquisitionWidget()
AcquisitionWidget::~AcquisitionWidget () override
Destructor.
Definition at line 192 of file AcquisitionWidget.cpp.
References QLOG_DEBUG.
Member Function Documentation
acquisitionFinished
void AcquisitionWidget::acquisitionFinished () slot
Update elapsed time when acquisition thread finishes.
Definition at line 718 of file AcquisitionWidget.cpp.
References runningChanged().
Referenced by AcquisitionWidget().
currentAcquiringRecord
int AcquisitionWidget::currentAcquiringRecord () const inline slot
Current record being processed (for UI highlight).
Definition at line 144 of file AcquisitionWidget.h.
getAcquiring
void AcquisitionWidget::getAcquiring (int record) slot
Update acquisition progress.
Parameters
record Current record index.
Definition at line 564 of file AcquisitionWidget.cpp.
References AcquisitionSequence::seq_record.
Referenced by AcquisitionWidget().
getCameraStatus
void AcquisitionWidget::getCameraStatus (bool imagesuccess) slot
Update camera status indicator.
Parameters
imagesuccess True if image acquisition succeeded.
Definition at line 544 of file AcquisitionWidget.cpp.
Referenced by AcquisitionWidget().
getDacStatus
void AcquisitionWidget::getDacStatus (bool dacsuccess) slot
Update DAC status indicator.
Parameters
dacsuccess True if DAC operation succeeded.
Definition at line 548 of file AcquisitionWidget.cpp.
Referenced by AcquisitionWidget().
getFilenumber
void AcquisitionWidget::getFilenumber (int number) slot
Update file number.
Parameters
number File index.
Definition at line 674 of file AcquisitionWidget.cpp.
Referenced by AcquisitionWidget().
getMotorStatus
void AcquisitionWidget::getMotorStatus (bool motorsuccess) slot
Update motor status indicator.
Parameters
motorsuccess True if motor operation succeeded.
Definition at line 552 of file AcquisitionWidget.cpp.
Referenced by AcquisitionWidget().
getPosition
void AcquisitionWidget::getPosition (QString positionQString) slot
Update the motor position display.
Parameters
positionQString Position string.
Definition at line 520 of file AcquisitionWidget.cpp.
Referenced by AcquisitionWidget().
getSuperKData
void AcquisitionWidget::getSuperKData (QString dataStr) slot
Update SuperK data display.
Parameters
dataStr Data string.
Definition at line 524 of file AcquisitionWidget.cpp.
Referenced by AcquisitionWidget().
getSuperKStatus
void AcquisitionWidget::getSuperKStatus (bool superksuccess) slot
Update SuperK status indicator.
Parameters
superksuccess True if SuperK operation succeeded.
Definition at line 556 of file AcquisitionWidget.cpp.
Referenced by AcquisitionWidget().
getTreatmentStatus
void AcquisitionWidget::getTreatmentStatus (bool treatmentstatus) slot
Update treatment status indicator.
Parameters
treatmentstatus True if treatment succeeded.
Definition at line 560 of file AcquisitionWidget.cpp.
Referenced by AcquisitionWidget().
isopenCameraWindow
void AcquisitionWidget::isopenCameraWindow (QVector< bool > isopencamerawindow) slot
Track which camera windows are open.
Parameters
isopencamerawindow Per-camera open flags.
Definition at line 678 of file AcquisitionWidget.cpp.
References AcquisitionThread::setIsOpenCameraWindow().
Referenced by OpticsBenchUIMain::OpticsBenchUIMain().
reload
void AcquisitionWidget::reload () slot
Reload the acquisition table.
Definition at line 362 of file AcquisitionWidget.cpp.
Referenced by AcquisitionWidget().
remove
void AcquisitionWidget::remove () slot
Remove the selected acquisition row.
Definition at line 366 of file AcquisitionWidget.cpp.
Referenced by AcquisitionWidget().
requestAnalysis
void AcquisitionWidget::requestAnalysis () signal
Request analysis execution.
Referenced by AcquisitionWidget(), and requestAnalysisFromThread().
requestAnalysisFromThread
void AcquisitionWidget::requestAnalysisFromThread () slot
Relay analysis request from acquisition thread.
Definition at line 714 of file AcquisitionWidget.cpp.
References requestAnalysis().
Referenced by AcquisitionWidget().
run
void AcquisitionWidget::run () slot
Start acquisition.
Definition at line 378 of file AcquisitionWidget.cpp.
References Motor::connectMotor(), AcquisitionSequence::instrumentName, AcquisitionSequence::instrumentType, AcquisitionSequence::IS_LOOP, AcquisitionSequence::loop, AcquisitionSequence::LOOP_END, AcquisitionSequence::LOOP_START, AcquisitionSequence::loopends, AcquisitionSequence::loopNumber, AcquisitionSequence::prepare(), QLOG_DEBUG, AcquisitionSequence::record, runningChanged(), AcquisitionSequence::scanplan, AcquisitionSequence::seq_record, AcquisitionThread::setCamera(), AcquisitionThread::setComediCounter(), AcquisitionThread::setComediDac(), AcquisitionThread::setDac(), AcquisitionThread::setFile(), AcquisitionThread::setMotor(), AcquisitionThread::setRaspiDac(), AcquisitionThread::setSequenceList(), AcquisitionThread::setSuperK(), and AcquisitionSequence::settings.
Referenced by AcquisitionWidget().
runningChanged
void AcquisitionWidget::runningChanged (bool running) signal
Notify when acquisition is running or stopped.
Parameters
running True while acquisition is active.
Referenced by acquisitionFinished(), and run().
setAcqFile()
void AcquisitionWidget::setAcqFile (QString acqfile)
Set the acquisition file path/prefix.
Parameters
acqfile Acquisition file base.
Definition at line 202 of file AcquisitionWidget.cpp.
Referenced by OpticsBenchUIMain::OpticsBenchUIMain().
setCamera()
void AcquisitionWidget::setCamera (QVector< Camera * > cameraList)
Set the camera list used for acquisition.
Parameters
cameraList Cameras to use during acquisition.
Definition at line 226 of file AcquisitionWidget.cpp.
Referenced by OpticsBenchUIMain::OpticsBenchUIMain().
setComediCounter()
void AcquisitionWidget::setComediCounter (Comedi * comedi)
Set the Comedi counter controller.
Parameters
comedi Comedi counter instance.
Definition at line 242 of file AcquisitionWidget.cpp.
Referenced by OpticsBenchUIMain::OpticsBenchUIMain().
setComediDac()
void AcquisitionWidget::setComediDac (Comedi * comedi)
Set the Comedi DAC controller.
Parameters
comedi Comedi DAC instance.
Definition at line 246 of file AcquisitionWidget.cpp.
Referenced by OpticsBenchUIMain::OpticsBenchUIMain().
setDac()
void AcquisitionWidget::setDac (Dac * dac)
Set the DAC controller.
Parameters
dac DAC controller instance.
Definition at line 238 of file AcquisitionWidget.cpp.
Referenced by OpticsBenchUIMain::OpticsBenchUIMain().
setDbPath()
void AcquisitionWidget::setDbPath (QString path)
Set the database path used by the widget.
Parameters
path Filesystem path to DBs.
Definition at line 207 of file AcquisitionWidget.cpp.
References Utils::ConfigureSqlTableView().
Referenced by OpticsBenchUIMain::applyConfigurationDirectory(), and OpticsBenchUIMain::OpticsBenchUIMain().
setDelegates()
void AcquisitionWidget::setDelegates ()
Create and apply table delegates.
Definition at line 254 of file AcquisitionWidget.cpp.
References Utils::BuildDbPath(), and Camera::model.
Referenced by OpticsBenchUIMain::OpticsBenchUIMain().
setMotor()
void AcquisitionWidget::setMotor (Motor * motor)
Set the motor controller.
Parameters
motor Motor controller instance.
Definition at line 230 of file AcquisitionWidget.cpp.
Referenced by OpticsBenchUIMain::OpticsBenchUIMain().
setRaspiDac()
void AcquisitionWidget::setRaspiDac (Raspi * raspi)
Set the Raspi DAC controller.
Parameters
raspi Raspi DAC instance.
Definition at line 250 of file AcquisitionWidget.cpp.
Referenced by OpticsBenchUIMain::OpticsBenchUIMain().
setSuperK()
void AcquisitionWidget::setSuperK (SuperK * superk)
Set the SuperK controller.
Parameters
superk SuperK controller instance.
Definition at line 234 of file AcquisitionWidget.cpp.
Referenced by OpticsBenchUIMain::OpticsBenchUIMain().
showAcquisitionWarning
void AcquisitionWidget::showAcquisitionWarning (QString message) slot
Show acquisition warning to the user.
Parameters
message Warning message.
Definition at line 710 of file AcquisitionWidget.cpp.
References Utils::EmitWarning().
Referenced by AcquisitionWidget().
showWarning
void AcquisitionWidget::showWarning (QString message) signal
Emit warnings to the UI.
Parameters
message Warning message.
Referenced by AcquisitionWidget().
splashScreen
void AcquisitionWidget::splashScreen (QString imagepath, int screen_x, int screen_y) slot
Show a splash screen during acquisition.
Parameters
imagepath Path to splash image.
screen_x Screen X coordinate.
screen_y Screen Y coordinate.
Definition at line 508 of file AcquisitionWidget.cpp.
References QLOG_INFO, and AcquisitionThread::wakeSplashScreen().
Referenced by AcquisitionWidget().
stop
void AcquisitionWidget::stop () slot
Stop acquisition.
Definition at line 491 of file AcquisitionWidget.cpp.
Referenced by AcquisitionWidget().
update
void AcquisitionWidget::update () slot
Refresh displayed values.
Definition at line 357 of file AcquisitionWidget.cpp.
Referenced by AcquisitionWidget().
updateElapsed
void AcquisitionWidget::updateElapsed () slot
Update elapsed time while acquisition runs.
Definition at line 730 of file AcquisitionWidget.cpp.
Referenced by AcquisitionWidget().
The documentation for this class was generated from the following files:
AcquisitionWidget.h
AcquisitionWidget.cpp