OpticsBenchUI: ComediDac Class Reference
ComediDac Class Reference
Hardware » Dac
#include <ComediDac.h>
Signals
void getDescription (QString description)
void showWarning (QString message)
void getOutputs (int outputs, QString deviceName)
void getOutputValues (void *comedivalues)
Signals inherited from Comedi
void getDescription (QString description)
void showWarning (QString message)
void getOutputs (int outputs, QString mode)
void getOutputValues (void *comedivalues)
Public Member Functions
ComediDac (QString dbpath)
~ComediDac () override
Destructor.
bool connectComedi (QString newcomedi) override
bool resetComedi (QString newcomedi) override
bool setComediValue (QString newcomedi, int output, void *value) override
bool getComediValue (QString newcomedi, int output, double &value) override
bool updateDBValues (QString newcomedi) override
void setDbPath (QString path) override
Public Member Functions inherited from Comedi
~Comedi () override=default
Virtual destructor.
Additional Inherited Members
Public Attributes inherited from Comedi
QString path
Path to the Comedi database.
QString comeditype
Comedi device type identifier.
Detailed Description
Comedi DAC implementation.
Definition at line 36 of file ComediDac.h.
Constructor & Destructor Documentation
ComediDac()
ComediDac::ComediDac (QString dbpath) explicit
Create a Comedi DAC using the given DB path.
Parameters
dbpath Filesystem path to the Comedi DB.
Definition at line 27 of file ComediDac.cpp.
References Comedi::comeditype, and Comedi::path.
~ComediDac()
ComediDac::~ComediDac () override
Destructor.
Definition at line 35 of file ComediDac.cpp.
References Comedi::path, and QLOG_DEBUG.
Member Function Documentation
connectComedi()
bool ComediDac::connectComedi (QString newcomedi) override virtual
Connect to the Comedi DAC device.
Parameters
newcomedi Device identifier from the database.
Implements Comedi.
Definition at line 99 of file ComediDac.cpp.
References Utils::EmitWarning(), getDescription(), getOutputs(), getOutputValues(), Comedi::path, QLOG_INFO, and resetComedi().
getComediValue()
bool ComediDac::getComediValue (QString newcomedi, int output, double & value) override virtual
Read a DAC output value.
Parameters
newcomedi Device identifier from the database.
output Output channel index.
value Output value in engineering units.
Implements Comedi.
Definition at line 287 of file ComediDac.cpp.
References QLOG_INFO.
Referenced by resetComedi(), and setComediValue().
getDescription
void ComediDac::getDescription (QString description) signal
Emit a human-readable description of the device.
Parameters
description Device description string.
Referenced by connectComedi().
getOutputs
void ComediDac::getOutputs (int outputs, QString deviceName) signal
Emit output count and device name.
Parameters
outputs Number of outputs.
deviceName Device name or mode string.
Referenced by connectComedi().
getOutputValues
void ComediDac::getOutputValues (void * comedivalues) signal
Emit output values (device-specific type).
Parameters
comedivalues Pointer to device-specific values.
Referenced by connectComedi(), and updateDBValues().
resetComedi()
bool ComediDac::resetComedi (QString newcomedi) override virtual
Reset the DAC device.
Parameters
newcomedi Device identifier from the database.
Implements Comedi.
Definition at line 221 of file ComediDac.cpp.
References Utils::EmitWarning(), getComediValue(), QLOG_INFO, setComediValue(), and updateDBValues().
Referenced by connectComedi().
setComediValue()
bool ComediDac::setComediValue (QString newcomedi, int output, void * value) override virtual
Set a DAC output value (device-specific).
Parameters
newcomedi Device identifier from the database.
output Output channel index.
value Pointer to a device-specific value.
Implements Comedi.
Definition at line 248 of file ComediDac.cpp.
References Utils::EmitWarning(), getComediValue(), and QLOG_INFO.
Referenced by resetComedi().
setDbPath()
void ComediDac::setDbPath (QString path) override virtual
Set the database path used by this device.
Parameters
path Filesystem path to the Comedi DB.
Implements Comedi.
Definition at line 65 of file ComediDac.cpp.
References Comedi::path.
showWarning
void ComediDac::showWarning (QString message) signal
Emit warnings to the UI.
Parameters
message Warning message.
updateDBValues()
bool ComediDac::updateDBValues (QString newcomedi) override virtual
Sync or update database-backed settings.
Parameters
newcomedi Device identifier from the database.
Implements Comedi.
Definition at line 313 of file ComediDac.cpp.
References Utils::EmitWarning(), getOutputValues(), Comedi::path, and QLOG_DEBUG.
Referenced by resetComedi().
The documentation for this class was generated from the following files:
ComediDac.h
ComediDac.cpp