OpticsBenchUI: OpticsBenchUIMain Class Reference
OpticsBenchUIMain Class Reference
UI
#include <OpticsBenchUIMain.h>
Public Slots
void openacquisition ()
Open acquisition UI.
void openanalysis ()
Open analysis UI.
void openCameraWindow (int cameraNumber)
void openMotorWindow ()
Open the motor control window.
void openSuperKWindow ()
Open the SuperK control window.
void openDacWindow ()
Open the DAC control window.
void openComediCounterWindow ()
Open the Comedi counter window.
void openComediDacWindow ()
Open the Comedi DAC window.
void openRaspiDacWindow ()
Open the Raspi DAC window.
void showDacWarning (QString message)
void showComediWarning (QString message)
void showRaspiWarning (QString message)
void showMotorWarning (QString message)
void showSuperKWarning (QString message)
void showCameraWarning (QString message)
void showCameraControlWidgetWarning (QString message)
void showAcquisitionWarning (QString message)
void setAcquisitionRunning (bool running)
void setAnalysisRunning (bool running)
void flashRunningTabs ()
Timer slot to flash running tabs.
void showDocumentation ()
Show help documentation.
void showApiDocumentation ()
Show API documentation in the default browser.
void openConfiguration ()
Open the configuration dialog.
void applyConfigurationDirectory (const QString &path)
void saveConfiguration ()
Save all configuration databases (*.db3) to a selected directory.
void closeTab (int index)
Signals
void isopenCameraWindow (QVector< bool > isopencamerawindow)
void setDbPath (QString path)
void setAcqFile (QString acqfile)
Public Member Functions
OpticsBenchUIMain (QString appDirPath=0, QMainWindow *parent=0, Qt::WindowFlags fl=Qt::Window)
virtual ~OpticsBenchUIMain ()
Destructor.
void setOpenCameraWindow (bool isopen, int cameranumber)
Public Attributes
QVector< bool > isopencamerawindow
Per-camera open flags.
bool isopenanalysiswidget
True if analysis widget is open.
bool isopenacquisitionwidget
True if acquisition widget is open.
Protected Member Functions
void closeEvent (QCloseEvent *event)
void keyPressEvent (QKeyEvent *e)
Detailed Description
Main application window coordinating device windows and widgets.
Definition at line 95 of file OpticsBenchUIMain.h.
Constructor & Destructor Documentation
OpticsBenchUIMain()
OpticsBenchUIMain::OpticsBenchUIMain (QString appDirPath = 0, QMainWindow * parent = 0, Qt::WindowFlags fl = Qt::Window)
Construct the main window.
Parameters
appDirPath Application directory for resources and DBs.
parent Parent window.
fl Window flags.
Definition at line 74 of file OpticsBenchUIMain.cpp.
References applyConfigurationDirectory(), closeTab(), flashRunningTabs(), isopenacquisitionwidget, isopenanalysiswidget, AcquisitionWidget::isopenCameraWindow(), isopencamerawindow, isopenCameraWindow(), openacquisition(), openanalysis(), openCameraWindow(), openComediCounterWindow(), openComediDacWindow(), openConfiguration(), openDacWindow(), openMotorWindow(), openRaspiDacWindow(), openSuperKWindow(), saveConfiguration(), AcquisitionWidget::setAcqFile(), setAcqFile(), setAcquisitionRunning(), setAnalysisRunning(), AcquisitionWidget::setCamera(), AcquisitionWidget::setComediCounter(), AcquisitionWidget::setComediDac(), AcquisitionWidget::setDac(), AcquisitionWidget::setDbPath(), AnalysisWidget::setDbPath(), setDbPath(), AcquisitionWidget::setDelegates(), AcquisitionWidget::setMotor(), AcquisitionWidget::setRaspiDac(), AcquisitionWidget::setSuperK(), showAcquisitionWarning(), showApiDocumentation(), showComediWarning(), showDacWarning(), showDocumentation(), showMotorWarning(), showRaspiWarning(), and showSuperKWarning().
~OpticsBenchUIMain()
OpticsBenchUIMain::~OpticsBenchUIMain () virtual
Destructor.
Definition at line 637 of file OpticsBenchUIMain.cpp.
References QLOG_INFO.
Member Function Documentation
applyConfigurationDirectory
void OpticsBenchUIMain::applyConfigurationDirectory (const QString & path) slot
Apply and propagate a configuration directory.
Parameters
path Directory containing *.db3 files.
Definition at line 422 of file OpticsBenchUIMain.cpp.
References MotorWindow::setDbPath(), RaspiWindow::setDbPath(), SuperKWindow::setDbPath(), AcquisitionWidget::setDbPath(), AnalysisWidget::setDbPath(), ComediWindow::setDbPath(), and DacWindow::setDbPath().
Referenced by openConfiguration(), and OpticsBenchUIMain().
closeEvent()
void OpticsBenchUIMain::closeEvent (QCloseEvent * event) protected
Handle application close events.
Parameters
event Close event.
Definition at line 669 of file OpticsBenchUIMain.cpp.
closeTab
void OpticsBenchUIMain::closeTab (int index) slot
Close the tab at a given index.
Parameters
index Tab index.
Definition at line 404 of file OpticsBenchUIMain.cpp.
References isopenacquisitionwidget, and isopenanalysiswidget.
Referenced by OpticsBenchUIMain().
flashRunningTabs
void OpticsBenchUIMain::flashRunningTabs () slot
Timer slot to flash running tabs.
Definition at line 751 of file OpticsBenchUIMain.cpp.
Referenced by OpticsBenchUIMain().
isopenCameraWindow
void OpticsBenchUIMain::isopenCameraWindow (QVector< bool > isopencamerawindow) signal
Emit open/close state for camera windows.
Parameters
isopencamerawindow Per-camera open flags.
Referenced by OpticsBenchUIMain(), and setOpenCameraWindow().
keyPressEvent()
void OpticsBenchUIMain::keyPressEvent (QKeyEvent * e) protected
Handle global key press events.
Parameters
e Key press event.
Definition at line 661 of file OpticsBenchUIMain.cpp.
openacquisition
void OpticsBenchUIMain::openacquisition () slot
Open acquisition UI.
Definition at line 579 of file OpticsBenchUIMain.cpp.
References isopenacquisitionwidget.
Referenced by OpticsBenchUIMain().
openanalysis
void OpticsBenchUIMain::openanalysis () slot
Open analysis UI.
Definition at line 587 of file OpticsBenchUIMain.cpp.
References isopenanalysiswidget.
Referenced by OpticsBenchUIMain().
openCameraWindow
void OpticsBenchUIMain::openCameraWindow (int cameraNumber) slot
Open a camera window by index.
Parameters
cameraNumber Camera index.
Definition at line 595 of file OpticsBenchUIMain.cpp.
References isopencamerawindow, and CameraWindow::update().
Referenced by OpticsBenchUIMain().
openComediCounterWindow
void OpticsBenchUIMain::openComediCounterWindow () slot
Open the Comedi counter window.
Definition at line 623 of file OpticsBenchUIMain.cpp.
Referenced by OpticsBenchUIMain().
openComediDacWindow
void OpticsBenchUIMain::openComediDacWindow () slot
Open the Comedi DAC window.
Definition at line 627 of file OpticsBenchUIMain.cpp.
Referenced by OpticsBenchUIMain().
openConfiguration
void OpticsBenchUIMain::openConfiguration () slot
Open the configuration dialog.
Definition at line 414 of file OpticsBenchUIMain.cpp.
References applyConfigurationDirectory().
Referenced by OpticsBenchUIMain().
openDacWindow
void OpticsBenchUIMain::openDacWindow () slot
Open the DAC control window.
Definition at line 618 of file OpticsBenchUIMain.cpp.
Referenced by OpticsBenchUIMain().
openMotorWindow
void OpticsBenchUIMain::openMotorWindow () slot
Open the motor control window.
Definition at line 610 of file OpticsBenchUIMain.cpp.
Referenced by OpticsBenchUIMain().
openRaspiDacWindow
void OpticsBenchUIMain::openRaspiDacWindow () slot
Open the Raspi DAC window.
Definition at line 632 of file OpticsBenchUIMain.cpp.
Referenced by OpticsBenchUIMain().
openSuperKWindow
void OpticsBenchUIMain::openSuperKWindow () slot
Open the SuperK control window.
Definition at line 614 of file OpticsBenchUIMain.cpp.
Referenced by OpticsBenchUIMain().
saveConfiguration
void OpticsBenchUIMain::saveConfiguration () slot
Save all configuration databases (*.db3) to a selected directory.
Definition at line 474 of file OpticsBenchUIMain.cpp.
Referenced by OpticsBenchUIMain().
setAcqFile
void OpticsBenchUIMain::setAcqFile (QString acqfile) signal
Emit new acquisition file path/prefix.
Parameters
acqfile Acquisition file base.
Referenced by OpticsBenchUIMain().
setAcquisitionRunning
void OpticsBenchUIMain::setAcquisitionRunning (bool running) slot
Update flashing state for acquisition tab.
Parameters
running True while acquisition is active.
Definition at line 709 of file OpticsBenchUIMain.cpp.
Referenced by OpticsBenchUIMain().
setAnalysisRunning
void OpticsBenchUIMain::setAnalysisRunning (bool running) slot
Update flashing state for analysis tab.
Parameters
running True while analysis is active.
Definition at line 730 of file OpticsBenchUIMain.cpp.
Referenced by OpticsBenchUIMain().
setDbPath
void OpticsBenchUIMain::setDbPath (QString path) signal
Emit new database path.
Parameters
path Filesystem path to DBs.
Referenced by OpticsBenchUIMain().
setOpenCameraWindow()
void OpticsBenchUIMain::setOpenCameraWindow (bool isopen, int cameranumber)
Track camera window open/close state.
Parameters
isopen True if the window is open.
cameranumber Camera index.
Definition at line 657 of file OpticsBenchUIMain.cpp.
References isopencamerawindow, and isopenCameraWindow().
Referenced by CameraWindow::CameraWindow(), and CameraWindow::closeEvent().
showAcquisitionWarning
void OpticsBenchUIMain::showAcquisitionWarning (QString message) slot
Display acquisition warning message.
Parameters
message Warning text.
Definition at line 705 of file OpticsBenchUIMain.cpp.
Referenced by OpticsBenchUIMain().
showApiDocumentation
void OpticsBenchUIMain::showApiDocumentation () slot
Show API documentation in the default browser.
Definition at line 569 of file OpticsBenchUIMain.cpp.
Referenced by OpticsBenchUIMain().
showCameraControlWidgetWarning
void OpticsBenchUIMain::showCameraControlWidgetWarning (QString message) slot
Display camera control warning message.
Parameters
message Warning text.
Definition at line 772 of file OpticsBenchUIMain.cpp.
showCameraWarning
void OpticsBenchUIMain::showCameraWarning (QString message) slot
Display camera warning message.
Parameters
message Warning text.
Definition at line 701 of file OpticsBenchUIMain.cpp.
showComediWarning
void OpticsBenchUIMain::showComediWarning (QString message) slot
Display Comedi warning message.
Parameters
message Warning text.
Definition at line 683 of file OpticsBenchUIMain.cpp.
Referenced by OpticsBenchUIMain().
showDacWarning
void OpticsBenchUIMain::showDacWarning (QString message) slot
Display DAC warning message.
Parameters
message Warning text.
Definition at line 678 of file OpticsBenchUIMain.cpp.
Referenced by OpticsBenchUIMain().
showDocumentation
void OpticsBenchUIMain::showDocumentation () slot
Show help documentation.
Definition at line 565 of file OpticsBenchUIMain.cpp.
References Assistant::showDocumentation().
Referenced by OpticsBenchUIMain().
showMotorWarning
void OpticsBenchUIMain::showMotorWarning (QString message) slot
Display motor warning message.
Parameters
message Warning text.
Definition at line 693 of file OpticsBenchUIMain.cpp.
Referenced by OpticsBenchUIMain().
showRaspiWarning
void OpticsBenchUIMain::showRaspiWarning (QString message) slot
Display Raspi warning message.
Parameters
message Warning text.
Definition at line 688 of file OpticsBenchUIMain.cpp.
Referenced by OpticsBenchUIMain().
showSuperKWarning
void OpticsBenchUIMain::showSuperKWarning (QString message) slot
Display SuperK warning message.
Parameters
message Warning text.
Definition at line 697 of file OpticsBenchUIMain.cpp.
Referenced by OpticsBenchUIMain().
Member Data Documentation
isopenacquisitionwidget
bool OpticsBenchUIMain::isopenacquisitionwidget
True if acquisition widget is open.
Definition at line 116 of file OpticsBenchUIMain.h.
Referenced by closeTab(), openacquisition(), and OpticsBenchUIMain().
isopenanalysiswidget
bool OpticsBenchUIMain::isopenanalysiswidget
True if analysis widget is open.
Definition at line 114 of file OpticsBenchUIMain.h.
Referenced by closeTab(), openanalysis(), and OpticsBenchUIMain().
isopencamerawindow
QVector<bool> OpticsBenchUIMain::isopencamerawindow
Per-camera open flags.
Definition at line 112 of file OpticsBenchUIMain.h.
Referenced by openCameraWindow(), OpticsBenchUIMain(), and setOpenCameraWindow().
The documentation for this class was generated from the following files:
OpticsBenchUIMain.h
OpticsBenchUIMain.cpp