OpticsBenchUI: SuperKWindow Class Reference
SuperKWindow Class Reference
UI » Laser UI
#include <SuperKWindow.h>
Public Slots
void update ()
Update database-backed tables.
void remove ()
Remove selected entries.
void load ()
Load configuration into runtime.
void setDbPath (QString _path)
Public Member Functions
SuperKWindow (QMainWindow *parent=0, Qt::WindowFlags fl=Qt::Window, SuperK *_superk=0)
virtual ~SuperKWindow ()
Destructor.
Public Attributes
SuperKControlWidget * superkWidget
SuperK control widget instance.
Protected Member Functions
void closeEvent (QCloseEvent *event)
Detailed Description
Window for SuperK configuration and control.
Definition at line 34 of file SuperKWindow.h.
Constructor & Destructor Documentation
SuperKWindow()
SuperKWindow::SuperKWindow (QMainWindow * parent = 0, Qt::WindowFlags fl = Qt::Window, SuperK * _superk = 0)
Construct a SuperK window.
Parameters
parent Parent window.
fl Window flags.
_superk SuperK controller instance.
Definition at line 26 of file SuperKWindow.cpp.
References Utils::ConfigureSqlTableView(), load(), SuperK::path, remove(), SuperKControlWidget::setSuperK(), superkWidget, and update().
~SuperKWindow()
SuperKWindow::~SuperKWindow () virtual
Destructor.
Definition at line 88 of file SuperKWindow.cpp.
References QLOG_DEBUG.
Member Function Documentation
closeEvent()
void SuperKWindow::closeEvent (QCloseEvent * event) protected
Handle window close events.
Parameters
event Close event.
Definition at line 120 of file SuperKWindow.cpp.
References QLOG_DEBUG.
load
void SuperKWindow::load () slot
Load configuration into runtime.
Definition at line 143 of file SuperKWindow.cpp.
Referenced by SuperKWindow().
remove
void SuperKWindow::remove () slot
Remove selected entries.
Definition at line 147 of file SuperKWindow.cpp.
Referenced by SuperKWindow().
setDbPath
void SuperKWindow::setDbPath (QString _path) slot
Set the database path for tables.
Parameters
_path Filesystem path to the SuperK DB.
Definition at line 94 of file SuperKWindow.cpp.
References Utils::ConfigureSqlTableView(), SuperK::path, and SuperK::setDbPath().
Referenced by OpticsBenchUIMain::applyConfigurationDirectory().
update
void SuperKWindow::update () slot
Update database-backed tables.
Definition at line 138 of file SuperKWindow.cpp.
Referenced by SuperKWindow().
Member Data Documentation
superkWidget
SuperKControlWidget* SuperKWindow::superkWidget
SuperK control widget instance.
Definition at line 50 of file SuperKWindow.h.
Referenced by SuperKWindow().
The documentation for this class was generated from the following files:
SuperKWindow.h
SuperKWindow.cpp