OpticsBenchUI: Motor Class Reference
Motor Class Reference
Hardware » Motors
#include <Motor.h>
Public Slots
void operationComplete ()
Slot called when a motor operation completes.
Signals
void getPosition (float position)
void operationCompleted ()
Emit when a motor operation completes successfully.
void dbPositionUpdated ()
Emit when a DB position update succeeds (e.g., acquisition refresh).
void getDescription (QString description)
void showWarning (QString message)
void stopTimer ()
Request timers to stop (UI coordination).
Public Member Functions
Motor (QObject *parent=0, QString _appDirPath=0)
~Motor ()
Destructor.
void connectMotor (QString newactuator)
void moveForward (QString newactuator, float motion)
void moveBackward (QString newactuator, float motion)
void moveAbsolute (QString newactuator, float motion)
void stopMotor (QString newactuator)
void setDbPath (QString _path)
int getOperationComplete (QString newactuator)
float getPosition (QString newactuator)
void updateDbPosition (QString newactuator)
void refreshPositionFromDb (QString newactuator)
Public Attributes
QVector< int > operationcomplete
Per-actuator completion flags.
QString path
Path to the motor database.
Detailed Description
Controls and queries motorized actuators defined in the database.
This class provides a thin UI-facing API for connecting to motors, issuing motion commands, and reading positions. It also emits Qt signals for UI updates and warnings.
Definition at line 40 of file Motor.h.
Constructor & Destructor Documentation
Motor()
Motor::Motor (QObject * parent = 0, QString _appDirPath = 0)
Create a motor controller.
Parameters
parent QObject parent.
_appDirPath Application directory for locating databases.
Definition at line 26 of file Motor.cpp.
References path.
~Motor()
Motor::~Motor ()
Destructor.
Definition at line 34 of file Motor.cpp.
References operationcomplete, path, QLOG_DEBUG, and QLOG_INFO.
Member Function Documentation
connectMotor()
void Motor::connectMotor (QString newactuator)
Connect to a motorized actuator by name.
Parameters
newactuator Actuator identifier from the database.
Definition at line 115 of file Motor.cpp.
References DriverDefinition::CLOSED_LOOP, DriverDefinition::DriverFeature::closedLoop, ACCom::Create(), Driver::Create(), Utils::EmitWarning(), getDescription(), getPosition(), Driver::Init(), ACCom::Open(), operationcomplete, path, QLOG_DEBUG, QLOG_INFO, QLOG_WARN, and updateDbPosition().
Referenced by MotorControlWidget::connectMotor(), and AcquisitionWidget::run().
dbPositionUpdated
void Motor::dbPositionUpdated () signal
Emit when a DB position update succeeds (e.g., acquisition refresh).
Referenced by updateDbPosition().
getDescription
void Motor::getDescription (QString description) signal
Emit a human-readable description of the actuator.
Parameters
description Actuator description string.
Referenced by connectMotor().
getOperationComplete()
int Motor::getOperationComplete (QString newactuator)
Return nonzero when the actuator operation is complete.
Parameters
newactuator Actuator identifier from the database.
Definition at line 445 of file Motor.cpp.
References operationcomplete.
getPosition [1/2]
void Motor::getPosition (float position) signal
Emit the current position for display.
Parameters
position Position value (device units).
getPosition() [2/2]
float Motor::getPosition (QString newactuator)
Read current actuator position.
Parameters
newactuator Actuator identifier from the database.
Definition at line 379 of file Motor.cpp.
Referenced by connectMotor(), operationComplete(), refreshPositionFromDb(), and updateDbPosition().
moveAbsolute()
void Motor::moveAbsolute (QString newactuator, float motion)
Move an actuator to an absolute position.
Parameters
newactuator Actuator identifier from the database.
motion Absolute position (device units).
Definition at line 357 of file Motor.cpp.
References operationcomplete.
Referenced by MotorControlWidget::moveAbsolute().
moveBackward()
void Motor::moveBackward (QString newactuator, float motion)
Move an actuator backward by a relative distance.
Parameters
newactuator Actuator identifier from the database.
motion Relative motion amount (device units).
Definition at line 345 of file Motor.cpp.
References operationcomplete.
Referenced by MotorControlWidget::moveBackward().
moveForward()
void Motor::moveForward (QString newactuator, float motion)
Move an actuator forward by a relative distance.
Parameters
newactuator Actuator identifier from the database.
motion Relative motion amount (device units).
Definition at line 334 of file Motor.cpp.
References operationcomplete.
Referenced by MotorControlWidget::moveForward().
operationComplete
void Motor::operationComplete () slot
Slot called when a motor operation completes.
Definition at line 456 of file Motor.cpp.
References getPosition(), operationcomplete, operationCompleted(), path, QLOG_DEBUG, QLOG_WARN, and stopTimer().
operationCompleted
void Motor::operationCompleted () signal
Emit when a motor operation completes successfully.
Referenced by operationComplete().
refreshPositionFromDb()
void Motor::refreshPositionFromDb (QString newactuator)
Refresh cached position from the DB.
Parameters
newactuator Actuator identifier from the database.
Definition at line 422 of file Motor.cpp.
References getPosition(), path, and QLOG_WARN.
Referenced by MotorControlWidget::refreshCurrentPosition().
setDbPath()
void Motor::setDbPath (QString _path)
Set the path to the motor database.
Parameters
_path Filesystem path to the motor SQLite DB.
Definition at line 65 of file Motor.cpp.
References operationcomplete, and path.
Referenced by MotorWindow::setDbPath().
showWarning
void Motor::showWarning (QString message) signal
Emit warnings to the UI.
Parameters
message Warning message.
stopMotor()
void Motor::stopMotor (QString newactuator)
Stop the current actuator motion.
Parameters
newactuator Actuator identifier from the database.
Definition at line 368 of file Motor.cpp.
References operationcomplete.
Referenced by MotorControlWidget::stopMotor().
stopTimer
void Motor::stopTimer () signal
Request timers to stop (UI coordination).
Referenced by operationComplete().
updateDbPosition()
void Motor::updateDbPosition (QString newactuator)
Refresh position from the driver and persist it to the DB.
Parameters
newactuator Actuator identifier from the database.
Definition at line 390 of file Motor.cpp.
References dbPositionUpdated(), getPosition(), path, and QLOG_WARN.
Referenced by connectMotor().
Member Data Documentation
operationcomplete
QVector<int> Motor::operationcomplete
Per-actuator completion flags.
Definition at line 88 of file Motor.h.
Referenced by connectMotor(), getOperationComplete(), moveAbsolute(), moveBackward(), moveForward(), operationComplete(), setDbPath(), stopMotor(), and ~Motor().
path
QString Motor::path
Path to the motor database.
Definition at line 90 of file Motor.h.
Referenced by connectMotor(), Motor(), MotorWindow::MotorWindow(), operationComplete(), refreshPositionFromDb(), setDbPath(), MotorWindow::setDbPath(), updateDbPosition(), and ~Motor().
The documentation for this class was generated from the following files:
Motor.h
Motor.cpp