OpticsBenchUI: CameraWindow Class Reference
CameraWindow Class Reference
UI » Camera UI
#include <CameraWindow.h>
Public Slots
void set480x320 ()
Set video resolution to 480x320.
void set640x480 ()
Set video resolution to 640x480.
void set1280x960 ()
Set video resolution to 1280x960.
Signals
void setVideoPlayerResolution (int width, int height)
Public Member Functions
CameraWindow (QMainWindow *parent=0, Qt::WindowFlags fl=Qt::Window, Camera *_camera=0, int cameraNumber=0)
virtual ~CameraWindow ()
Destructor.
void update ()
Refresh the UI.
Protected Member Functions
void closeEvent (QCloseEvent *event)
Detailed Description
Window hosting camera controls and live video.
Definition at line 39 of file CameraWindow.h.
Constructor & Destructor Documentation
CameraWindow()
CameraWindow::CameraWindow (QMainWindow * parent = 0, Qt::WindowFlags fl = Qt::Window, Camera * _camera = 0, int cameraNumber = 0)
Construct a camera window.
Parameters
parent Parent window.
fl Window flags.
_camera Camera to display/control.
cameraNumber Camera index.
Definition at line 29 of file CameraWindow.cpp.
References Camera::camera_err, Camera::model, OFFSET_X, OFFSET_Y, Camera::propList, set1280x960(), set480x320(), set640x480(), OpticsBenchUIMain::setOpenCameraWindow(), setVideoPlayerResolution(), and Camera::vendor.
~CameraWindow()
CameraWindow::~CameraWindow () virtual
Destructor.
Definition at line 102 of file CameraWindow.cpp.
References QLOG_INFO.
Member Function Documentation
closeEvent()
void CameraWindow::closeEvent (QCloseEvent * event) protected
Handle window close events.
Parameters
event Close event.
Definition at line 112 of file CameraWindow.cpp.
References QLOG_DEBUG, and OpticsBenchUIMain::setOpenCameraWindow().
set1280x960
void CameraWindow::set1280x960 () slot
Set video resolution to 1280x960.
Definition at line 138 of file CameraWindow.cpp.
References OFFSET_X, OFFSET_Y, and setVideoPlayerResolution().
Referenced by CameraWindow().
set480x320
void CameraWindow::set480x320 () slot
Set video resolution to 480x320.
Definition at line 120 of file CameraWindow.cpp.
References OFFSET_X, OFFSET_Y, and setVideoPlayerResolution().
Referenced by CameraWindow().
set640x480
void CameraWindow::set640x480 () slot
Set video resolution to 640x480.
Definition at line 129 of file CameraWindow.cpp.
References OFFSET_X, OFFSET_Y, and setVideoPlayerResolution().
Referenced by CameraWindow().
setVideoPlayerResolution
void CameraWindow::setVideoPlayerResolution (int width, int height) signal
Set video player resolution.
Parameters
width Width in pixels.
height Height in pixels.
Referenced by CameraWindow(), set1280x960(), set480x320(), and set640x480().
update()
void CameraWindow::update ()
Refresh the UI.
Definition at line 147 of file CameraWindow.cpp.
References Camera::getFeatures().
Referenced by OpticsBenchUIMain::openCameraWindow().
The documentation for this class was generated from the following files:
CameraWindow.h
CameraWindow.cpp