OpticsBenchUI: ComediCounter Class Reference
ComediCounter Class Reference
Hardware » Dac
#include <ComediCounter.h>
Signals
void getDescription (QString description)
void showWarning (QString message)
void getOutputs (int outputs, QString deviceName)
void getOutputValues (void *comedivalues)
Signals inherited from Comedi
void getDescription (QString description)
void showWarning (QString message)
void getOutputs (int outputs, QString mode)
void getOutputValues (void *comedivalues)
Public Member Functions
ComediCounter (QString dbpath)
~ComediCounter () override
Destructor.
bool connectComedi (QString newcomedi) override
bool resetComedi (QString newcomedi) override
bool setComediValue (QString newcomedi, int output, void *value) override
bool getComediValue (QString newcomedi, int output, double &value) override
bool updateDBValues (QString newcomedi) override
void setDbPath (QString path) override
Public Member Functions inherited from Comedi
~Comedi () override=default
Virtual destructor.
Additional Inherited Members
Public Attributes inherited from Comedi
QString path
Path to the Comedi database.
QString comeditype
Comedi device type identifier.
Detailed Description
Comedi counter implementation.
Definition at line 32 of file ComediCounter.h.
Constructor & Destructor Documentation
ComediCounter()
ComediCounter::ComediCounter (QString dbpath) explicit
Create a Comedi counter using the given DB path.
Parameters
dbpath Filesystem path to the Comedi DB.
Definition at line 26 of file ComediCounter.cpp.
References Comedi::comeditype, and Comedi::path.
~ComediCounter()
ComediCounter::~ComediCounter () override
Destructor.
Definition at line 35 of file ComediCounter.cpp.
References Comedi::path, and QLOG_DEBUG.
Member Function Documentation
connectComedi()
bool ComediCounter::connectComedi (QString newcomedi) override virtual
Connect to the Comedi counter device.
Parameters
newcomedi Device identifier from the database.
Implements Comedi.
Definition at line 99 of file ComediCounter.cpp.
References Utils::EmitWarning(), getDescription(), getOutputs(), getOutputValues(), Comedi::path, QLOG_DEBUG, QLOG_INFO, and resetComedi().
getComediValue()
bool ComediCounter::getComediValue (QString newcomedi, int output, double & value) override virtual
Read a counter value.
Parameters
newcomedi Device identifier from the database.
output Output channel index.
value Output value in engineering units.
Implements Comedi.
Definition at line 336 of file ComediCounter.cpp.
getDescription
void ComediCounter::getDescription (QString description) signal
Emit a human-readable description of the device.
Parameters
description Device description string.
Referenced by connectComedi().
getOutputs
void ComediCounter::getOutputs (int outputs, QString deviceName) signal
Emit output count and device name.
Parameters
outputs Number of outputs.
deviceName Device name or mode string.
Referenced by connectComedi().
getOutputValues
void ComediCounter::getOutputValues (void * comedivalues) signal
Emit output values (device-specific type).
Parameters
comedivalues Pointer to device-specific values.
Referenced by connectComedi(), resetComedi(), and updateDBValues().
resetComedi()
bool ComediCounter::resetComedi (QString newcomedi) override virtual
Reset the counter device.
Parameters
newcomedi Device identifier from the database.
Implements Comedi.
Definition at line 212 of file ComediCounter.cpp.
References Utils::EmitWarning(), getOutputValues(), Comedi::path, and QLOG_INFO.
Referenced by connectComedi().
setComediValue()
bool ComediCounter::setComediValue (QString newcomedi, int output, void * value) override virtual
Set a counter value or mode (device-specific).
Parameters
newcomedi Device identifier from the database.
output Output channel index.
value Pointer to a device-specific value.
Implements Comedi.
Definition at line 295 of file ComediCounter.cpp.
References QLOG_INFO.
setDbPath()
void ComediCounter::setDbPath (QString path) override virtual
Set the database path used by this device.
Parameters
path Filesystem path to the Comedi DB.
Implements Comedi.
Definition at line 66 of file ComediCounter.cpp.
References Comedi::path.
showWarning
void ComediCounter::showWarning (QString message) signal
Emit warnings to the UI.
Parameters
message Warning message.
updateDBValues()
bool ComediCounter::updateDBValues (QString newcomedi) override virtual
Sync or update database-backed settings.
Parameters
newcomedi Device identifier from the database.
Implements Comedi.
Definition at line 347 of file ComediCounter.cpp.
References Utils::EmitWarning(), getOutputValues(), Comedi::path, and QLOG_INFO.
The documentation for this class was generated from the following files:
ComediCounter.h
ComediCounter.cpp