OpticsBenchUI: ACRSCom Class Reference
ACRSCom Class Reference
RS-232 serial communication channel.
#include <ACRSCom.h>
Public Member Functions
ACRSCom (string device, string settings)
ACRSCom (const ACRSCom &channel)
virtual int Open ()
virtual int Read (string &message,...)
virtual int Write (string &message,...)
virtual int Close ()
Public Member Functions inherited from ACCom
ACCom (string device, string settings)
ACCom (const ACCom &channel)
virtual ~ ACCom ()
virtual int GetStatus () const
Additional Inherited Members
Public Types inherited from ACCom
enum { OPEN , CLOSED }
Static Public Member Functions inherited from ACCom
static ACCom * Create (string channelType, string device, string settings)
static ACCom * Create (const ACCom *prefChannel)
Static Public Attributes inherited from ACCom
static const string RS_COM = "SERIAL_PORT"
static const string ETH_COM = "ETHERNET"
static const string MB_COM = "MB_COM"
static const string USB_COM = "USB_COM"
static const string CAN_COM = "CAN_COM"
static const string NULL_COM = "NULL_COM"
Protected Member Functions inherited from ACCom
void ReportWarning (const QString &message) const
Log a warning message tagged with this communication channel.
void ReportError (const QString &message) const
Log an error message tagged with this communication channel.
Protected Attributes inherited from ACCom
int _state
string _device
string _settings
Detailed Description
RS-232 serial communication channel.
Definition at line 32 of file ACRSCom.h.
Constructor & Destructor Documentation
ACRSCom() [1/2]
ACRSCom::ACRSCom (string device, string settings) inline
Constructor
Definition at line 38 of file ACRSCom.h.
ACRSCom() [2/2]
ACRSCom::ACRSCom (const ACRSCom & channel) inline
Constructor
Definition at line 53 of file ACRSCom.h.
Member Function Documentation
Close()
int ACRSCom::Close () virtual
The Close method allows to close the channel
Operation : Close Closes the communication by closing the file associated to the serial port.
Implements ACCom.
Definition at line 255 of file ACRSCom.cpp.
References ACCom::_state, ACCom::CLOSED, ACCom::OPEN, and ACCom::ReportWarning().
Referenced by Open().
Open()
int ACRSCom::Open () virtual
The Open method allows to open the channel
Operation : Open Opens the communication channel by opening the file associated to the serial port and performs a setup of the communication according to the selected settings.
Implements ACCom.
Definition at line 61 of file ACRSCom.cpp.
References ACCom::_device, ACCom::_settings, ACCom::_state, Close(), ACCom::CLOSED, ACCom::OPEN, and ACCom::ReportError().
Read()
int ACRSCom::Read (string & message, ...) virtual
The Read method allows to read in the channel
Parameters
message The message to be read
... The parametrization must be either of the following:
NULL : default mode
Operation : Read Reads datas on the serial port. Returns the number of read characters. data read on the serial port
Implements ACCom.
Definition at line 213 of file ACRSCom.cpp.
Write()
int ACRSCom::Write (string & message, ...) virtual
The Write method allows to write in the channel
Parameters
message The message to be read
... The parametrization must be either of the following:
NULL : default mode
"ECHO" : echo mode writes character by character, each write followed by a single character read.
The message string must be finished with "\r" character
Operation : Write Writes datas on the serial port. Returns the number of bytes written data to send on the serial port
Implements ACCom.
Definition at line 177 of file ACRSCom.cpp.
References QLOG_DEBUG, and ACCom::ReportWarning().
The documentation for this class was generated from the following files:
ACRSCom.h
ACRSCom.cpp