OpticsBenchUI: DacAdvantech Class Reference
DacAdvantech Class Reference
Hardware » Dac
#include <DacAdvantech.h>
Signals
void getDescription (QString description)
void showWarning (QString message)
void getOutputs (int outputs, QString mode)
void getOutputValues (QVector< float > *dacvalues)
Signals inherited from Dac
void getDescription (QString description)
void showWarning (QString message)
void getOutputs (int outputs, QString mode)
void getOutputValues (QVector< float > *dacvalues)
Public Member Functions
DacAdvantech (QString dbpath)
~DacAdvantech ()
Destructor.
bool connectDac (QString newdac)
bool resetDac (QString newdac)
bool setDacValue (QString newdac, int output, double value)
bool setDacRValue (QString newdac, int output, double rvalue)
float getDacValue (QString newdac, int output)
bool updateDBValues (QString newdac)
void setDbPath (QString _path)
Public Member Functions inherited from Dac
~Dac () override=default
Virtual destructor.
Additional Inherited Members
Public Attributes inherited from Dac
QString path
Path to the DAC database.
Detailed Description
Advantech DAC implementation.
Definition at line 37 of file DacAdvantech.h.
Constructor & Destructor Documentation
DacAdvantech()
DacAdvantech::DacAdvantech (QString dbpath) explicit
Create an Advantech DAC controller.
Parameters
dbpath Filesystem path to the DAC DB.
Definition at line 26 of file DacAdvantech.cpp.
References Dac::path.
~DacAdvantech()
DacAdvantech::~DacAdvantech ()
Destructor.
Definition at line 34 of file DacAdvantech.cpp.
References Dac::path, and QLOG_DEBUG.
Member Function Documentation
connectDac()
bool DacAdvantech::connectDac (QString newdac) virtual
Connect to the configured DAC device.
Parameters
newdac DAC identifier from the database.
Implements Dac.
Definition at line 144 of file DacAdvantech.cpp.
References Utils::EmitWarning(), getDescription(), getOutputs(), getOutputValues(), Dac::path, QLOG_DEBUG, and QLOG_INFO.
getDacValue()
float DacAdvantech::getDacValue (QString newdac, int output) virtual
Read the DAC channel value.
Parameters
newdac DAC identifier from the database.
output Output channel index.
Implements Dac.
Definition at line 547 of file DacAdvantech.cpp.
References Utils::EmitWarning(), QLOG_DEBUG, and QLOG_ERROR.
getDescription
void DacAdvantech::getDescription (QString description) signal
Emit a human-readable description of the device.
Parameters
description Device description string.
Referenced by connectDac().
getOutputs
void DacAdvantech::getOutputs (int outputs, QString mode) signal
Emit output count and device name.
Parameters
outputs Number of outputs.
mode Device name or mode string.
Referenced by connectDac().
getOutputValues
void DacAdvantech::getOutputValues (QVector< float > * dacvalues) signal
Emit current output values.
Parameters
dacvalues Pointer to output values.
Referenced by connectDac(), resetDac(), and updateDBValues().
resetDac()
bool DacAdvantech::resetDac (QString newdac) virtual
Reset the DAC device.
Parameters
newdac DAC identifier from the database.
Implements Dac.
Definition at line 342 of file DacAdvantech.cpp.
References Utils::EmitWarning(), getOutputValues(), and Dac::path.
setDacRValue()
bool DacAdvantech::setDacRValue (QString newdac, int output, double rvalue) virtual
Set a DAC channel value in raw units.
Parameters
newdac DAC identifier from the database.
output Output channel index.
rvalue Raw device value.
Implements Dac.
Definition at line 417 of file DacAdvantech.cpp.
References Utils::EmitWarning(), and QLOG_DEBUG.
setDacValue()
bool DacAdvantech::setDacValue (QString newdac, int output, double value) virtual
Set a DAC channel value in engineering units.
Parameters
newdac DAC identifier from the database.
output Output channel index.
value Value in engineering units.
Implements Dac.
Definition at line 483 of file DacAdvantech.cpp.
References Utils::EmitWarning(), and QLOG_DEBUG.
setDbPath()
void DacAdvantech::setDbPath (QString _path) virtual
Set the database path used by this device.
Parameters
_path Filesystem path to the DAC DB.
Implements Dac.
Definition at line 86 of file DacAdvantech.cpp.
References Dac::path.
showWarning
void DacAdvantech::showWarning (QString message) signal
Emit warnings to the UI.
Parameters
message Warning message.
updateDBValues()
bool DacAdvantech::updateDBValues (QString newdac) virtual
Sync or update database-backed settings.
Parameters
newdac DAC identifier from the database.
Implements Dac.
Definition at line 562 of file DacAdvantech.cpp.
References Utils::EmitWarning(), getOutputValues(), Dac::path, and QLOG_DEBUG.
The documentation for this class was generated from the following files:
DacAdvantech.h
DacAdvantech.cpp