OpticsBenchUI: MotorControlWidget Class Reference
MotorControlWidget Class Reference
UI » Motor UI
#include <MotorControlWidget.h>
Public Slots
void connectMotor ()
Connect to the selected motor.
void moveForward ()
Move forward by a relative amount.
void moveBackward ()
Move backward by a relative amount.
void moveAbsolute ()
Move to an absolute position.
void stopMotor ()
Stop the motor.
void getPosition (float position)
void getDescription (QString description)
void stopTimer ()
Stop periodic updates.
void refreshCurrentPosition ()
Refresh current position from DB after external updates.
Public Member Functions
MotorControlWidget (QVector< QString > *_actuatorList=0)
~MotorControlWidget ()
Destructor.
void setMotor (Motor *_motor)
void setActuatorList (QVector< QString > *_actuatorList)
Detailed Description
UI widget for motor control.
Definition at line 34 of file MotorControlWidget.h.
Constructor & Destructor Documentation
MotorControlWidget()
MotorControlWidget::MotorControlWidget (QVector< QString > * _actuatorList = 0)
Construct a motor control widget.
Parameters
_actuatorList List of actuator names (optional).
Definition at line 25 of file MotorControlWidget.cpp.
References connectMotor(), moveAbsolute(), moveBackward(), moveForward(), and stopMotor().
~MotorControlWidget()
MotorControlWidget::~MotorControlWidget ()
Destructor.
Definition at line 85 of file MotorControlWidget.cpp.
References QLOG_DEBUG.
Member Function Documentation
connectMotor
void MotorControlWidget::connectMotor () slot
Connect to the selected motor.
Definition at line 97 of file MotorControlWidget.cpp.
References Motor::connectMotor().
Referenced by MotorControlWidget().
getDescription
void MotorControlWidget::getDescription (QString description) slot
Update the description display.
Parameters
description Actuator description.
Definition at line 135 of file MotorControlWidget.cpp.
Referenced by setMotor().
getPosition
void MotorControlWidget::getPosition (float position) slot
Update the current position display.
Parameters
position Current position.
Definition at line 67 of file MotorControlWidget.cpp.
Referenced by setMotor().
moveAbsolute
void MotorControlWidget::moveAbsolute () slot
Move to an absolute position.
Definition at line 119 of file MotorControlWidget.cpp.
References Motor::moveAbsolute().
Referenced by MotorControlWidget().
moveBackward
void MotorControlWidget::moveBackward () slot
Move backward by a relative amount.
Definition at line 111 of file MotorControlWidget.cpp.
References Motor::moveBackward().
Referenced by MotorControlWidget().
moveForward
void MotorControlWidget::moveForward () slot
Move forward by a relative amount.
Definition at line 103 of file MotorControlWidget.cpp.
References Motor::moveForward().
Referenced by MotorControlWidget().
refreshCurrentPosition
void MotorControlWidget::refreshCurrentPosition () slot
Refresh current position from DB after external updates.
Definition at line 143 of file MotorControlWidget.cpp.
References Motor::refreshPositionFromDb().
Referenced by setMotor(), and MotorWindow::update().
setActuatorList()
void MotorControlWidget::setActuatorList (QVector< QString > * _actuatorList)
Set the list of available actuators.
Parameters
_actuatorList List of actuator names.
Definition at line 90 of file MotorControlWidget.cpp.
setMotor()
void MotorControlWidget::setMotor (Motor * _motor)
Attach the motor controller.
Parameters
_motor Motor controller instance.
Definition at line 73 of file MotorControlWidget.cpp.
References getDescription(), getPosition(), refreshCurrentPosition(), and stopTimer().
Referenced by MotorWindow::MotorWindow().
stopMotor
void MotorControlWidget::stopMotor () slot
Stop the motor.
Definition at line 128 of file MotorControlWidget.cpp.
References Motor::stopMotor().
Referenced by MotorControlWidget().
stopTimer
void MotorControlWidget::stopTimer () slot
Stop periodic updates.
Definition at line 139 of file MotorControlWidget.cpp.
Referenced by setMotor().
The documentation for this class was generated from the following files:
MotorControlWidget.h
MotorControlWidget.cpp