OpticsBenchUI: OpticsBenchUIMain.cpp File Reference
OpticsBenchUIMain.cpp File Reference
Main application window.
#include "OpticsBenchUIMain.h"
#include "Utils.h"
#include <QDesktopServices>
#include <QUrl>
#include <QScreen>
#include <QGuiApplication>
#include <functional>
Macros
#define DEBUG_LEVEL QsLogging::InfoLevel
Functions
void myMessageOutput (QtMsgType type, const QMessageLogContext &, const QString &str)
int main (int argc, char *argv[])
Detailed Description
Main application window.
Definition in file OpticsBenchUIMain.cpp.
Macro Definition Documentation
DEBUG_LEVEL
#define DEBUG_LEVEL QsLogging::InfoLevel
Definition at line 72 of file OpticsBenchUIMain.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 775 of file OpticsBenchUIMain.cpp.
References QsLogging::Logger::addDestination(), Utils::CurrentTimestampString(), DEBUG_LEVEL, QsLogging::Logger::instance(), QsLogging::DestinationFactory::MakeDebugOutputDestination(), QsLogging::DestinationFactory::MakeFileDestination(), myMessageOutput(), QLOG_DEBUG, QLOG_INFO, and QsLogging::Logger::setLoggingLevel().
myMessageOutput()
void myMessageOutput (QtMsgType type, const QMessageLogContext & , const QString & str)
Definition at line 673 of file OpticsBenchUIMain.cpp.
Referenced by main().